### ISSUE TITLE
The WebSocket rate limit has been hit, this should never happen

### ISSUE THREAD

**Issue by HRK44** [discordjs/discord.js#10089]
### Which package is this bug report for?

discord.js

### Issue description

I'm getting this error message time to time `The WebSocket rate limit has been hit, this should never happen`,

My app is doing quite a lot of requests but nothing crazy, getting members `await members.fetch()` prob 10req/s max and then add/remove user roles > could ramp up to 100req/s max, prob average less than 1req/s.

Socket restarts automatically afterwards but usually I get `Members didn't arrive in time` or other bunch of issues when it restarts, if you have any ideas on why this happens, would be appreciated thanks.

### Code sample
```
[1661756] 2024-01-14T10:04:23.412Z debug: [WS => Shard 0] The WebSocket rate limit has been hit, this should never happen
[1661756] 2024-01-14T10:04:23.412Z debug: [WS => Shard 0] Destroying shard
        Reason: none
        Code: 4008
        Recover: Reconnect
[1661756] 2024-01-14T10:04:23.412Z debug: [WS => Shard 0] Connection status during destroy
        Needs closing: false
        Ready state: 3
[1661756] 2024-01-14T10:04:23.912Z debug: [WS => Shard 0] Connecting to wss://gateway.discord.gg?v=10&encoding=json
[1661756] 2024-01-14T10:04:23.918Z debug: [WS => Shard 0] Waiting for event hello for 60000ms
[1661756] 2024-01-14T10:04:24.082Z debug: [WS => Shard 0] Preparing first heartbeat of the connection with a jitter of 0.036720235270546686; waiting 1514ms
[1661756] 2024-01-14T10:04:24.083Z debug: [WS => Shard 0] Waiting for identify throttle
[1661756] 2024-01-14T10:04:24.083Z debug: [WS => Shard 0] Identifying
        shard id: 0
        shard count: 1
        intents: 98819
        compression: none
[1661756] 2024-01-14T10:04:24.083Z debug: [WS => Shard 0] Waiting for event ready for 15000ms
[1661756] 2024-01-14T10:04:24.172Z debug: [WS => Shard 0] Tried to send a non-crucial payload before the shard was ready, waiting
[1661756] 2024-01-14T10:04:25.602Z debug: [WS => Shard 0] First heartbeat sent, starting to beat every 41250ms
[1661756] 2024-01-14T10:04:26.537Z debug: [WS => Shard 0] Heartbeat acknowledged, latency of 935ms.
[1661756] 2024-01-14T10:04:26.687Z debug: Failed to find guild, or unknown type for channel 118265xxx 16
[1661756] 2024-01-14T10:04:26.688Z debug: Failed to find guild, or unknown type for channel 118264xxx 16
[1661756] 2024-01-14T10:04:26.804Z debug: [WS => Shard 0] Shard received all its guilds. Marking as fully ready.
```

### Versions

"discord.js": "14.10.2",
node 20.10.0
typescript 4.8.2

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Guilds, GuildMembers

**Comment by didinele** [comment]
While you're certainly running into a bug with how the library tracks limits, the limit for WS is 120/60 seconds, you are doing way more than that and the strain is huge. You need to rethink your application.

Keeping this open to further investigate how it's possible to trigger the actual bug

**Comment by HRK44** [comment]
Noticed this log as well that happens before:
`[1661756] 2024-01-14T10:16:04.574Z debug: [WS => Shard 0] Was about to hit the send rate limit, sleeping for 3050ms`

**Comment by Renegade334** [comment]
> Keeping this open to further investigate how it's possible to trigger the actual bug

Think I've identified the root cause, which appears to be the way the rate limit counter is checked in `ws::WebSocketShard#send`. [[ref](https://github.com/discordjs/discord.js/blob/adfd9cd3b32cfabdcc45ec90f535b2852a3ca4a6/packages/ws/src/ws/WebSocketShard.ts#L372-L398)]

The way the logic is currently written, the shard's rate limit counter is only reset _once the counter reaches zero_.

If the rate limiter reaches zero before `resetsAt` is reached, the limiter triggers a timeout and works as intended. In the alternative case, though, the counter reaches zero, the script correctly identifies that no throttling is necessary, but resets the counter back to maximum, without taking into account any events sent in the last 60 seconds.
  ```js
  for (let i = 0; i < 128; i++) {
    sendWebsocketEvent()
    console.debug(activeWebsocketShard.sendRateLimitState)
    await require('node:timers/promises').setImmediate()
  }
  // { remaining: 119, resetAt: 1234567890 }
  // { remaining: 118, resetAt: 1234567890 }
  // ...
  // { remaining: 2, resetAt: 1234567890 }
  // { remaining: 1, resetAt: 1234567890 }
  // { remaining: 120, resetAt: 1234568024 }
  // { remaining: 119, resetAt: 1234568024 }
  // { remaining: 118, resetAt: 1234568024 }
  // ...
  // { remaining: 112, resetAt: 1234568024 }
  // [WS => Shard 0] The WebSocket rate limit has been hit, this should never happen
  ```

The fix would likely be to check `resetAt`, and reset the counter if necessary, prior to the logic check for whether the counter has reached zero. I've tested and this does work; however, this is still vulnerable to conditions where a large number of websocket messages are sent either side of `resetAt`.

There is another issue where once the rate limiter is hit, it essentially nukes the websocket's ability to respond to heartbeats, meaning that queueing a large number of websocket send events is essentially an indefinite killswitch for that shard, as even once it respawns, all of the delayed events will continue to race to the rate limit and prevent any further heartbeats from being sent for another sixty seconds. The rate limit probably needs to allow some headroom for essential events, and have `WebSocketShard#send` bypass the limiter for these.

**Comment by didinele** [comment]
> The way the logic is currently written, the shard's rate limit counter is only reset once the counter reaches zero.

That should be alright though, I thought of it this way by design to avoid any sort of async (as in, timeout/interval based, I wanted everything to be sequential and leveraging async/await as much as possible) checks/state adjustments.

> but resets the counter back to maximum, without taking into account any events sent in the last 60 seconds.

I don't really follow how this happens. Do you mean to say that multiple events sit here:

https://github.com/discordjs/discord.js/blob/adfd9cd3b32cfabdcc45ec90f535b2852a3ca4a6/packages/ws/src/ws/WebSocketShard.ts#L381-L385

after which, multiple hit this?

https://github.com/discordjs/discord.js/blob/adfd9cd3b32cfabdcc45ec90f535b2852a3ca4a6/packages/ws/src/ws/WebSocketShard.ts#L397

If so, that can't be right, because of 

https://github.com/discordjs/discord.js/blob/adfd9cd3b32cfabdcc45ec90f535b2852a3ca4a6/packages/ws/src/ws/WebSocketShard.ts#L397

which ensures everything runs sequentially - maybe I'm missing something and/or didn't understand your explanation properly!


> There is another issue where once the rate limiter is hit, it essentially nukes the websocket's ability to respond to heartbeats. This means that queueing a large number of websocket send events is essentially an indefinite killswitch for that shard, as even once it respawns, all of the delayed events will continue to race to the rate limit and prevent any further heartbeats from being sent for another sixty seconds. The rate limit probably needs to allow some headroom for essential events, and have WebSocketShard#send bypass the limiter for these.

This is known, #8918

**Comment by Renegade334** [comment]
Sorry for the less than clear explanation!

But yes, essentially. As things stand, the counter is only reset when it reaches zero, and when this happens, the shard will "forget" about any recent websocket events it's sent, even if those have occurred within the last 60 seconds and are therefore having an impact on rate limiting.

Changing the counter to reset every time `resetAt` is reached does correctly throttle a large number of requests if they're all made in quick succession, ie. within the same rate limit window. However, it's still vulnerable to failure if the timespan over which those requests are sent crosses over the moment when the counter is reset.

Fundamentally, any fix that keeps a static counter, rather than a rolling one, is going to be vulnerable to some sort of timing case.
