### ISSUE TITLE
add: checkboxes for form modals

### ISSUE THREAD

**Issue by KuezyIT** [discordjs/discord.js#10594]
### Which application or package is this feature request for?

discord.js

### Feature

I'm wishing for a feature that allows me to choose preselected options like checkbox menu within a single form modal for use after submission. This could be useful for application modals where users need to consent to some type of rules/they agree that they read through the requirements, or select multiple groups for specific role mentions, etc.

### Ideal solution or implementation

Something like adding interaction.field.getCheckboxSelection to the already other existing interaction fields.

**Comment by Amgelo563** [comment]
What you're mentioning is not possible on Discord, and since `discord.js` is simply a non official wrapper for the Discord API, it does not control what features Discord has.

You should instead request that to Discord (and once they add it, it can then be added to `discord.js`), or follow the existent discussions (eg https://github.com/discord/discord-api-docs/discussions/5883), since improved modals is a long desired feature.
