### ISSUE TITLE
Types for getSubcommand are wrong

### ISSUE THREAD

**Issue by abbytec** [discordjs/discord.js#10641]
### Which package is this bug report for?

discord.js

### Issue description

On typescript, if you use chatInputCommandInteraction.options.getSubcommand(true) you expect to receive a string, otherwise you expect to receive a string or null. But it is defined as follows:
public getSubcommand(required?: true): string;
public getSubcommand(required: boolean): string | null;

it should look like this (as the other getUser/getChannel/etc methods do):
public getSubcommand(required: true): string;
public getSubcommand(required?: boolean): string | null;

### Versions

Discordjs 14.16.3
Node v18.17.1
Typescript 9.6.7

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by abbytec** [comment]
https://github.com/discordjs/discord.js/blob/00dceb32ba02579b41cb039b508d4761b6d0c424/packages/discord.js/typings/index.d.ts#L1241

**Comment by Jiralite** [comment]
> On typescript, if you use chatInputCommandInteraction.options.getSubcommand(true) you expect to receive a string, otherwise you expect to receive a string or null. But it is defined as follows:
public getSubcommand(required?: true): string;
public getSubcommand(required: boolean): string | null;

This is correct. If the parameter is missing or is `true`, it will return a `string`, otherwise `string | null`.

> it should look like this (as the other getUser/getChannel/etc methods do):
public getSubcommand(required: true): string;
public getSubcommand(required?: boolean): string | null;

This does not reflect JavaScript, so this would be incorrect.

<hr>

There is no issue.
