### ISSUE TITLE
TypeError on request

### ISSUE THREAD

**Issue by Wodki** [discordjs/discord.js#2351]
**Please describe the problem you are having in as much detail as possible:**
I got this error below.
TypeError: Cannot read property 'options' of undefined
    at item.request.gen.end (/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:69:75)
    at then (/node_modules/snekfetch/src/index.js:263:21)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

**Further details:**

- discord.js version: 11.3
- node.js version: v8.9.0
- Operating system: Debian
- Priority this issue should have – please be realistic and elaborate if possible: Medium

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
I am fairly sure this bug was fixed with the 11.3 release.

In 11.2, the execute method was trying to read the ClientOptions from `this.client` which does not exists in the context of the SequentialRequestHandler. See [here](https://github.com/discordjs/discord.js/blob/11.2.0/src/client/rest/RequestHandlers/Sequential.js#L69)
Which has been fixed with #1904.

Looking at the line where your error is pointing to ([here](https://github.com/discordjs/discord.js/blob/11.3.0/src/client/rest/RequestHandlers/Sequential.js#L69)):
If `this.restManager.client` would be undefined, trying to set the timeout would throw an error before attempting to access the options.

The instance that threw this error is likely outdated, nuking node_modules and reinstalling should do the trick.
