### ISSUE TITLE
Steam Integration

### ISSUE THREAD

**Issue by ruchibuchi1** [discordjs/discord.js#2476]
Does anyone know how to send Stream chat messages from a discord bot, and can they point me to the right resources?

Thanks

**Comment by Dev-Yukine** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

**Comment by iCrawl** [comment]
This has nothing to do with our library so it does not belong here.

I'll go out of a limb and tell you what you need though because otherwise this is probably not going to end well.

<https://docs.tmijs.org/> is one of the things you should have a look at.
Again, this has nothing to do with discord.js specifically.
