### ISSUE TITLE
Members cache is not getting updated

### ISSUE THREAD

**Issue by Wodki** [discordjs/discord.js#2477]
**Please describe the problem you are having in as much detail as possible:**
The members cache after a member changes their avatar does not get updated.

**Include a reproducible code sample here, if possible:**
```js
const client = new Discord.Client({
	disabledEvents: [
		'PRESENCE_UPDATE',
		'TYPING_START',
		'RELATIONSHIP_ADD',
		'RELATIONSHIP_REMOVE',
		'VOICE_SERVER_UPDATE',
		'VOICE_STATE_UPDATE',
		'USER_NOTE_UPDATE',
		'CHANNEL_PINS_UPDATE',
	],
        fetchAllMembers: true,
});

client.login(token);
```

**Further details:**

- discord.js version: 11.3.2
- node.js version: 8.11.1
- Operating system: CentOS, Win32/64
- Priority this issue should have – please be realistic and elaborate if possible: high

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by bdistin** [comment]
a member changing their avatar would be an example of a PRESENCE_UPDATE... also:

__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
