### ISSUE TITLE
🐛 Bug: message.channel.nsfw

### ISSUE THREAD

**Issue by Lhermebr** [discordjs/discord.js#2498]
if the channel is named `nsfw`, the function `message.channel.nsfw` returns `false`.

Versions:

Discord.js - 11.3.2

Node.js - 8.9.4

npm - 5.6.0

Images:

![coolimage1](https://user-images.githubusercontent.com/25855744/39098004-9698c67c-463a-11e8-9baf-ee6b632c8a2f.PNG)
![coolimage2](https://user-images.githubusercontent.com/25855744/39098005-98d55a72-463a-11e8-860d-ae6882330415.PNG)

**Comment by rei2hu** [comment]
In my opinion, this is not the library's fault but rather the Discord's client's fault because the idea that any channel starting with nsfw is nsfw was a temporary measure before actual API support was added. This library actually did use the name to check the channel [at that time](https://github.com/discordjs/discord.js/blob/5ac22691d26cd5f396f574efb112f75d0eeeeed6/src/structures/interfaces/TextBasedChannel.js#L398)

However, now that the API has proper nsfw support for channels, that should be what is used. When you create a channel whose name starts with nsfw, you see that the request sent has `nsfw: false` which is why the API/library says it's false.
![image](https://user-images.githubusercontent.com/11600812/39099962-6c1cd5c2-4672-11e8-9a1c-11a6c98cf1ef.png)

So I think Discord is responsible for fixing this by making the client request with `nsfw: true` when creating a channel whose name starts with nsfw (or by not automatically interpreting channels whose names start with nsfw as nsfw, which might declare some channels as sfw when they are meant to be nsfw so it's not a good idea).
