### ISSUE TITLE
defineduser.guildMember.joinedAt is giving a TypeError

### ISSUE THREAD

**Issue by sweetcactussia** [discordjs/discord.js#2519]
**Please describe the problem you are having in as much detail as possible:**

I'm doing a userinfo command but when I want to use the `defineduser.guildMember.joinedAt` I get an `TypeError: Cannot read property 'joinedAt' of undefined`

**Include a reproducible code sample here, if possible:**

`var defineduser = message.mentions.users.first();`
``message.channel.send(`${defineduser.guildMember.joinedAt}`);``

**Further details:**

- discord.js version: 11.3.2
- node.js version: 8.11.1
- Operating system: Windows 8.1
- Priority : Medium - For any self-hosted bots, the bot would easily crash cause of that error.

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
[User](https://discord.js.org/#/docs/main/stable/class/User) has no property `guildMember`.

The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
