### ISSUE TITLE
bot crashing to unhandled error ([object object])

### ISSUE THREAD

**Issue by peachyfawx** [discordjs/discord.js#2555]
so trying to run my bot on an AWS ec2 server and it crashes overnight while I am asleep so when i wake up the next morning I find my bot down. when I check what caused the crash I am always greeted to 

events.js:173
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Client.emit (events.js:171:17)
    at WebSocketConnection.onError (/home/ec2-user/kalina/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:374:17)
    at WebSocket.onError (/home/ec2-user/kalina/node_modules/ws/lib/event-target.js:128:16)
    at WebSocket.emit (events.js:182:13)
    at _receiver.cleanup (/home/ec2-user/kalina/node_modules/ws/lib/websocket.js:211:14)
    at Receiver.cleanup (/home/ec2-user/kalina/node_modules/ws/lib/receiver.js:557:13)
    at WebSocket.finalize (/home/ec2-user/kalina/node_modules/ws/lib/websocket.js:206:20)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)

from the few friends I have talked to this isn't a problem with my code.  is anyone else experiencing this?

a sample of the code I am using:

bot.on('ready', () => {

    cron.schedule('0 5,11 * * 1', function(){
        sendMessageBat(embed6);
    });

    cron.schedule('30 7,13 * * 1', function(){
        sendMessageBat(embed7);
    });

    cron.schedule('0 8,14 * * 1', function(){
        sendMessageBat(embed8);
    });

    function sendMessageBat(msg) {
        fs.readFile('battery.json', 'utf8', function readFileCallback(err, data) {
            if (err) {
            } else {
                var dict = JSON.parse(data);
                for(var serverID in dict){
                    var channelIDs = dict[serverID];
                    for(var i in channelIDs){
                        bot.guilds.get(serverID).channels.get(channelIDs[i]).send(msg);
                    }
                }
            }
        });
    }
})

I am running 2 of these and the other part of the bot is just a command handler/section

**Comment by peachyfawx** [comment]
i forgot to mention that the versions i am running are the latest of everything

**Comment by kyranet** [comment]
Duplicated of #2523 and many other issues, this is not an issue with the library but rather in your side, handle your error event (mentioned in the linked issue) and this should not longer crash.

**Comment by ardentwolf** [comment]
This is bad design of discord.js good design has error levels and only crashes if it's fatal, this just crashes on any error, doesn't give you a code line, or any indication of what crashed.  PHP, javascript, doesn't matter, they all have features to not totally kill execution, especially of something running in a loop, just because of an error.   Pointing your bad design choices on end programmers is classic shifting the blame.  Think of it this way, someone else could make a library for discord, that is not going to crash a bunch of people's bots that then get "lots of duplicate" issues reported for crashing their bot.  

This is why people who are taught try catch throw type error handling often get it wrong.  They can cause more problems than they solve, where as a message might've been logged to error before, and crashed only if it was deemed fatal for some reason, now it's just going to be the least bullet proof program you've ever seen and crash at anything going even slightly awry.  

The only solution is either some one liner that isn't really clear that the client (a one liner which some are reporting doesn't work for them and they get the error anyway), would need an on error event or to have try/catch blocks around every line of code or a catch statement after any call.  That's just tedious and stupid.  What program have you ever seen that handles line by line any error ever happening?  The entire idea is absurd.  I've tried wrapping the entire program in a try catch block and it doesn't catch it, which is a stupid thing to have to try anyway.  The way this is programmed means tracking down bugs is hard and the system is extremely fragile, what a muck.  I honestly might switch libs because of this.

The error it was crashing on randomly every 2 days for me was Error: read ECONNRESET, so a networking error, what if chrome's default behavior was crash every time there was some network error.  What a dumb idea.
