### ISSUE TITLE
Weird Behavior when setting CUSTOM KEYS on message objects in DISCORD.JS

### ISSUE THREAD

**Issue by ridarf** [discordjs/discord.js#2668]
I'm trying to set custom keys in a Discord bot and attach it to a Discord Message Object, but it seems to be working only about 60-80% of the time, which is really disrupting my work-flow here.

Essentially, what I'm trying to do is make sure that only the specified message is the one people can react to to make a certain function work, however unfortunately it's very unreliable, and it seems that sometimes the message object is getting reset.

This is an example of what I'm trying to done, without getting too complicated. I've went to many people now and nobody has been able to figure out what's going wrong, or why...
```

bot.on("message", async message => {
if(message.content === `!test`){
    message.channel.send("This is a test message!")
        .then(msg => {
            msg.cookie = true;
            return msg;
        })
        .then(msg => {
            console.log(msg.cookie);
            return msg;
            })
        .then(async msg => {
            await msg.react('🍪');
        });
    };
});

bot.on("messageReactionAdd", async (messageReaction, user) => {
    let msg = messageReaction.message;
    if(msg.cookie){
        console.log("The cookie, it's there!");
    }else{
        console.log("Uh oh... the cookie is missing!");
    };
});
```
Now, if I do !test 15 times. Each time it will log "true" into the console from the second .then, but on average only 10-13 times will I get "The cookie, it's there!" and upon logging the messageReaction.message, it seems as though the object has completely reset itself. If someone could help me figure this all out it would be AMAZING. Thank you.

Using discord.js@11.3.2.

**Comment by ridarf** [comment]
[IMAGE PROOF](https://i.stack.imgur.com/6pCl5.png)

**Comment by TeeSeal** [comment]
Your `messageReactionAdd` listener listens to ALL messages. Not only the one coming out of your command. Hence if someone reacts to a message anywhere else where your bot is as well, the `no cookie` thing will pop up.

Also, you shouldn't rely on the state of the message object being preserved between multiple events. There are all sorts of things happening in the background that discord.js handles, causing data to be reset, especially on small things such as messages. It would be safer if you had a bucket of some sorts where you would keep the ids of the messages that have the `cookie` and work with that, instead of attaching a custom property to the message object.

**Comment by ridarf** [comment]
@TeeSeal It hadn't really occured to me, for whatever reason to create a local storage and use that rather than the active message. Thank you very much.
