### ISSUE TITLE
Merge `message.member` with `member.author`

### ISSUE THREAD

**Issue by cfanoulis** [discordjs/discord.js#2858]
I recently learn that getting the member object of the author needs a completly different property, which, in my eyes, is rather strange and disorientating ~~for noobs like me~~ for several people. I would really like to see `message.member` merged with `message.author`, keeping the `author` namespace and move the member prop under `message.author.member`.

**Comment by SpaceEEC** [comment]
See #1415

**Comment by bdistin** [comment]
author is a user, a user is the same no matter what context or guild. member is a member, members are unique to guilds, and are different to each guild. For example, you can have a different nickname in every guild, but you can only have one username service-wide.

A member correlates to exactly one user, which is why there is `member.user`, However, a user can correlate to anywhere from 0 to the total number of guilds your bot is in, which is why you can't have a `user.member` relationship. `user.member` isn't one-to-one, it's a one-to-many-or-zero relationship.

**Comment by cfanoulis** [comment]
Oops, never thought of that 😅 . OK, consider this closed
