### ISSUE TITLE
Emoji's display as garbled text on older clients

### ISSUE THREAD

**Issue by tenleftfingers** [discordjs/discord.js#2898]
**Is your feature request related to a problem? Please describe.**
Some clients interpret emoji's as gibberish. Could the alt-text description be displayed instead? I realise this may be a client-side issue but until I ask here I won't know.

**Describe the ideal solution**
I don't know if it's possible, but for older clients like WookieChat on Amiga, it would be great if they could be either detected and sent the alt-text instead.

**Describe alternatives you've considered**
Is there a way to send something that older clients will not display as garbled text?

**Additional context**
Emoji's display fine on webchat and modern terminal clients. But on older clients, the red car displays like this:
![fr_1_size880](https://user-images.githubusercontent.com/1757768/47040657-ae96c100-d17e-11e8-908e-deda277fba2c.jpg)

**Comment by appellation** [comment]
How is this an issue with Discord.js?  Is this a bot using Discord.js that is attempting to send a custom emoji?

We do not support user account automation or custom clients.

**Comment by Throne3d** [comment]
This issue came from <https://github.com/reactiflux/discord-irc/issues/192#issuecomment-430361174>, and I think there's been a misunderstanding in what exactly the request is.

Currently, if a text message in a discord channel includes a (non-custom) emoji, discord.js preserves the Unicode emoji in the message content. This is good behavior – you wouldn't want to convert the emoji into a textual equivalent without being asked to, it makes sense that you don't – but, as far as I know, the library provides no way to then convert the emoji into a textual equivalent on demand. This means that, in the specific case of discord-irc, we convey the emoji as an emoji into the IRC channels we're dealing with, which fails to render on lots of clients, because we don't have the text-to-emoji mapping that Discord uses.

Ideally, discord-irc would be able to ask discord.js for a version of the message's content which has the emojis replaced with one of the codes used to generate it (e.g. `:thumbsup:`, instead of the thumbs-up emoji). This seems like it could be within scope of the discord.js library, given that the desktop Discord app shows strings like this on hover (that is, if you write `:thumbsup:` in a message, and then hover over the emoji in the resulting message, Discord will show the text `:thumbsup:`).

**Comment by appellation** [comment]
similar to #1712

**Comment by Throne3d** [comment]
Oh, hm, I guess that answers the question that it's not really in scope, then – do you know where Discord gets its text-emoji mapping from, by any chance?

**Comment by appellation** [comment]
I would recommend the package referenced in 1712. I don't know how Discord specifically does it.
