### ISSUE TITLE
overwrites for GuildChannelStore#create seem to be broken, for user id's

### ISSUE THREAD

**Issue by Tylertron1998** [discordjs/discord.js#2905]
**Please describe the problem you are having in as much detail as possible:**
Passing in a user id to the channel overwrites doesn't seem to work - nothing is thrown, and the overwrite isn't given.

**Include a reproducible code sample here, if possible:**
```js
const channel = await message.guild.channels.create(`Mute-${member.user.discriminator}`, {
	parent: message.guild.settings.moderation.muteCatagory,
	reason: `Mute: ${reason.join(' ')}`,
	overwrites: [{
		allow: 'VIEW_CHANNEL',
		id: message.guild.settings.roles.staff // works fine
	}, {
		allow: 'VIEW_CHANNEL',
		id: '235831899312881665' // does not work
	}, {
		deny: 'VIEW_CHANNEL',
		id: message.guild.defaultRole.id // works fine
	}]
});

```

**Further details:**
- discord.js version: lastest master (just updated)
- Node.js version: v10.11.0
- Operating system: win
- Priority this issue should have – please be realistic and elaborate if possible: medium-high, a lot of moderation bots could rely on this

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
To stay consistent with the rest of the api, the property `overwrites` had been renamed to `permissionOverwrites`.
See: #2886

I tested creating overwrites for users and roles there, which seems to work for me.

Also as a note: Always specify the explicit hash you tested, because as soon there is a new commit in master, `latest` is not quite correct anymore.
