### ISSUE TITLE
Bot Randomly Deletes All Channels in a Server

### ISSUE THREAD

**Issue by DarkLink77689** [discordjs/discord.js#2906]
**Please describe the problem you are having in as much detail as possible:**

On my Discord server, I have made a bot that responds to a command with a TTS message. However I noticed that when the command was spammed, the bot suddenly crashed. In that moment, the bot deleted all of the channels in the server

**Include a reproducible code sample here, if possible:**
```js

// Suspicious code
 if(message.content == prefix + "chant") { message.channel.send("message", {tts: true}); }
```

**Further details:**
- Latest Discord JS and NODE js

**Comment by DarkLink77689** [comment]
Yeah,
The bot did remove all of them, it was in the audit logs.
There wasn't anything in the code resembling deleting servers, so I don't think that's the case.

**Comment by Lewdcario** [comment]
This will be closed since this is not reproducible, I can also not possibly fathom of what code would cause this in the library without the developer demanding it so. Consider that your token might be leaked and is being used maliciously. Feel free to comment again if you can find a code sample that will cause this issue.
