### ISSUE TITLE
Session invalidation fires the ready event without clearing timeouts and intervals

### ISSUE THREAD

**Issue by VikoRifeo** [discordjs/discord.js#2913]
**Please describe the problem you are having in as much detail as possible:**
When a session is invalidated and discord.js automatically makes a new one, it re-fires the `ready` event without clearing the client's timeouts and (more importantly) intervals. The `ready` event is the obvious place to set them (IMO, at least), but this makes that unsafe.

**Include a reproducible code sample here, if possible:**
This can't really be reproduced on demand, unfortunately.

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 10.12.0
- Operating system: macOS Mojave
- Priority this issue should have – please be realistic and elaborate if possible: medium, I guess?

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by TomSputz** [comment]
Thse `<Client>.setInterval` method is described as

> Sets an interval that will be automatically cancelled if the client is destroyed.

and imo, that means that if the client can reconnect, it should persist.

Is there any reason you can't just do `clearInterval` on the ready event yourself?

**Comment by appellation** [comment]
Clearing all timers would break the library. For example, heartbeats are negotiated outside of session identification, meaning that the library would cease to heartbeat whenever the session was invalidated.

**Comment by ViKomprenas** [comment]
In answer to @TomSputz's second question: I'd been discarding them. I can of course hold onto them and clear them in the ready handler, but that's really sidestepping the real problem here.

I agree with Tom that intervals should persist if the client can reconnect. I'll go further and say that session invalidation should be as invisible to the user as possible. Under that interpretation, `ready` shouldn't be re-fired during invalidation.

Of course, implementing that would probably be a breaking change (convenient timing, I suppose). And that's assuming it even makes sense to do -- you may disagree. At the very least, though, `ready` needs more documentation on precisely when it fires, and `setInterval`/`setTimeout` on precisely when they are cleared and when it is a good idea to set them.

**Comment by appellation** [comment]
The ready event could use a note saying that it will be fired once all guilds are available, which is a departure from the Discord API. However, multiple ready events should be expected as it is documented in the [Discord API documentation](https://discordapp.com/developers/docs/topics/gateway#ready). Node event emitters have the `once` method, so this isn't something that dramatically affects functionality if you're only concerned about the first ready event.

"Sets an interval that will be automatically cancelled if the client is destroyed" explicitly states when the interval is cancelled. Cancelling timers at any other time would be breaking for reasons explained above.

**Comment by appellation** [comment]
It sounds like you're expecting discord.js to hide the underlying connection state. I'm not a huge fan of this idea, since it seems important for the end user to be informed on whether they are successfully connected and authenticated. The point of using a library like discord.js is to make difficult things more convenient (for example, fetching all members in a guild), not to magically handle sessions such that the end user is unaware of whether they're actually connected.

I can see your confusion around what "destroyed" would mean, especially since there is a limited use-case. I would contend, however, that assuming "destroyed" to mean "invalidated session" is a bit of a stretch and a simple search of the docs would reveal the answer very quickly.  Regardless, the client timers API is not designed around a per-connection basis but instead designed to cleanup any timers the client may have created so the process can safely exit. Any timers that are dependent upon the websocket state are handled manually by listening to the relevant events (ready, reconnecting, resumed, etc.).

As I explained earlier, there is already a "once-per conceptual-session" event with the `once` method. There is no reason to add a different event just to replicate this functionality.

**Comment by ViKomprenas** [comment]
There is a difference between not telling the user whether they are authenticated or not and not telling the user whether, at this precise moment, the client has been briefly disconnected from Discord due to a normal network fluctuation and will reconnect as soon as possible, which is unlikely to be very long; and there is a difference between _that_ and not making the user think they have been completely logged out and back in whenever the network fluctuates.

With respect to "destroyed": It is a bit of a stretch, point taken, but that doesn't change the fact that I took it and ended up quite confused for a bit. If client destruction had a bigger role in the documentation, it would have come across clearer.

`once`ing ready events isn't a per-conceptual-session event. If the client deliberately logs out and back in, for instance, it doesn't happen again. I don't know why you would want to do that, but using our hypothetical conceptual-session-ready event is something I at least would do anyway for best practice reasons, which is why I did it in the first place.

This definitely needs clearer documentation, if nothing else.

**Comment by appellation** [comment]
There is no difference between brief disconnections and completely logging out; once the session is invalidated, you are for all intents and purposes unauthenticated from the API. The duration and commonality of these events has nothing to do with how they should be handled.

The only documented way to explicitly log out of the gateway is to destroy the client or exit the process. In both of these cases, you are not going to have to worry about a once ready listener not firing.

**Comment by iCrawl** [comment]
Closing as it is a stale issue, reopen or check open issues if this is still an issue.
