### ISSUE TITLE
'roleUpdate' event emits the edited role AND @everyone role

### ISSUE THREAD

**Issue by Dream-cake** [discordjs/discord.js#2959]
**Please describe the problem you are having in as much detail as possible:**

Whenever I updated a role the roleUpdate event gets emits the role that was updated then it does @everyone

**Include a reproducible code sample here, if possible:**
```js

client.on("roleUpdate", async (oldRole, newRole) => {
    
console.log(newRole);

});

```

**Comment by Darqam** [comment]
Would have been useful if you hadn't done ctrl+a -> delete, on the issue template which would provide a bunch of extra information which would be needed.

**Comment by SpaceEEC** [comment]
This seems to only happens if you edit the role from within the discord client; It does not happen if you edit the role via a bot.

This might be related to https://github.com/discordapp/discord-api-docs/issues/278.
If so, the correct place to report this seems to be [Discord-Testers](http://discord.gg/discord-testers).
(Looks like the client always patches the position of the everyone role to 0, likely a bug.)
