### ISSUE TITLE
Events listeners across instances of a client

### ISSUE THREAD

**Issue by owen-m1** [discordjs/discord.js#3031]
I am looking to have it so I can set up an on 'message' event listener that will last for a long period of time. However, due to the nature of my application I must delete the client after the user disconnects, to avoid memory leaks. Is it possible to save the event listener across different instances of a client (with the same token)?

**Comment by kyranet** [comment]
You don't need to destroy the client every time a user disconnects, if you refer to the bot, it auto-reconnects, you don't need to do that and defeats the purpose of the internal resume queue. And also...

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by owen-m1** [comment]
@kyranet I am referring to regular user accounts. My app lets users connect to a server, which creates the discord Clients, and I need to store them for long periods of time while keeping the events listening. However, the server will run out of memory when enough clients are stored.
