### ISSUE TITLE
Bot sending advertising

### ISSUE THREAD

**Issue by Maryannah** [discordjs/discord.js#3033]
**Please describe the problem you are having in as much detail as possible:**

I logged into my account this morning (5 minutes ago) to discover I got a private message from the bot I created, advertising for a student app. 

When I went on the testing channel (on which the bot is being tested), I also saw the message : 

![image](https://user-images.githubusercontent.com/46892394/51592003-d40a3800-1eee-11e9-80f2-8da471d51413.png)

I have looked online and there is **absolutely no mention** of something similar whatsoever, so I'm posting this issue here in hope of an answer. 

And if it wasn't obvious at first, no, I'm not the one who coded the advertising ...

**Further details:**
- discord.js version: **11.4.2**
- Node.js version: **8.11.3**
- Operating system: 
- Priority this issue should have – please be realistic and elaborate if possible: **minimal** : *just a question*

**Comment by tipakA** [comment]
how is sending messages unexpected behaviour

**Comment by fypos** [comment]
**Anyone** can log in with your token, which you are sharing in your [repository](https://github.com/Maryannah/discord-bots/blob/master/config.json). I would suggest that you regenerate your token and add your config file to your *.gitignore*.

**Comment by Maryannah** [comment]
@Fyk0 thank you very much for that information, didn't know that :) Have a nice day !

**Comment by almostSouji** [comment]
Since the topic is of quite some import i'm going to leave some resources here:  

GitHub/-Lab: <https://git-scm.com/docs/gitignore>
Heroku: <https://devcenter.heroku.com/articles/config-vars>
Glitch: <https://support.glitch.com/t/how-do-i-set-environment-variables/3921>
Repl.it: <https://repl.it/site/docs/repls/secret-keys>
Node: <https://medium.freecodecamp.org/heres-how-you-can-actually-use-node-environment-variables-8fdf98f53a0a>
Invalidate your current token: https://i.imgur.com/XtQsR9s.png at <https://discordapp.com/developers/applications>  

> Go to <https://discordapp.com/developers/applications> and then click on the application that corresponds with your bot
> Click "Bot" on the left side 
> Click the "Regenerate" button and then "Yes, do it!" on the popup.
