### ISSUE TITLE
sodium doesn't work as of the latest version, so proposing a changeover to libsodium, which already has a JS port anyway

### ISSUE THREAD

**Issue by coltongit** [discordjs/discord.js#3093]
The sodium package discord.js is using doesn't compile anymore due to a missing file error on the repo's part, so I'm proposing that discord.js switches over to `libsodium` instead, which we're already using the wrappers for, and won't be an issue with the current codebase. PR #3094 dictates what this change will do to discord.js as a whole (which isn't very much at all).

**Comment by amishshah** [comment]
The `sodium` package still compiles fine for me on Windows 10 so maybe you're just missing tools required for compilation? (there's also no issues on the repo indicating that the repo is at fault for missing files)

In your PR #3094 I really don't see the point of adding `libsodium-wrappers` - it shares the same codebase as `libsodium` (from what I can tell they're basically the same thing) so if you're able to install one you're able to install the other -- there's no need in supporting both if they have no discerning features and have the same installation requirements.

`sodium` on the other hand is a native library and should offer better performance than both of these libraries, so I think you'd be better making an issue at [their repo](https://github.com/paixaop/node-sodium/issues) if you're having troubles compiling it on your system.

**Comment by coltongit** [comment]
Multiple people have had the same trouble as I have and no one ever replies to them.

**Comment by amishshah** [comment]
That is pretty unfortunate, on Windows I've installed [windows-build-tools](https://www.npmjs.com/package/windows-build-tools) (you need the 2015 MSVS version so run `npm install --vs2015 --global windows-build-tools`.

If you're still unable to install it, I'd maybe open a new issue or directly mention the sodium maintainer in an existing issue to try and get it fixed.

**Comment by coltongit** [comment]
I've tried your command, but that just gets me an `EBADPLATFORM` error. I'm trying to compile the errant library in WSL.

**Comment by amishshah** [comment]
Sorry, I don't have any more ideas, you'll have to try sodium's issue tracker.

**Comment by vzwGrey** [comment]
What exactly even is your issue when compiling sodium? You have been very vague so far.

**Comment by vladfrangu** [comment]
Packages needed to compile sodium, on WSL included: `build-essential libtool-bin autoconf`.

Install these with your package manager, followed by `npm i sodium` or `yarn add sodium`. Any missing packages will be said in the error message that gets thrown by sodium.

**Comment by coltongit** [comment]
> What exactly even is your issue when compiling sodium? You have been very vague so far.

The issue is that when you get to the third .o file when compiling, it throws a g++ error: `libsodium.a: No such file or directory.`

**Comment by AbandonedCart** [comment]
@amishshah Is discord.js exclusively a Windows project?

**Comment by GamesProSeif** [comment]
There's no statement that proves Discord.js is only supported on Windows.
Sodium and such packages are *optional*, as you might've seen in the guide. Discord.js works on multiple platforms in a stable manner. Approved by a lot of users.

The mentioned alternative package (`libsodium`) is even listed now in the in the [master documentation landing page](https://discord.js.org/#/docs/main/master/general/welcome), in the optional packages section.
![optional packages](https://user-images.githubusercontent.com/45742587/66269355-1a6eaf80-e850-11e9-8601-fa99173d619c.png)

Also note that this issue is pretty old. It was opened on Feb 15, and it's Oct 6 now. So, there has to be a lot of changes that took place in both Discord.js and Sodium's libraries since that time. Hence why this issue was closed and not discussed afterwards.

**Comment by AbandonedCart** [comment]
@GamesProSeif If you look back through the thread, the issue was closed on Feb 15. It being Oct 6 today did not really impact that decision.

I am aware it is an optional package and removing it was the convenient solution for encountering similar issues. Simply removing things when they don't work on their own may work for you, but I prefer to at least attempt to investigate further when they suddenly stop working after years.

What I was trying to find out was whether or not this was the best option as a Mac user, since Windows might be the only basis for testing. I could not find any specific statement about it, but there also didn't seem to be much concern that the issue impacted Linux, Raspberry Pi, and Mac

**Comment by iCrawl** [comment]
Ubuntu 18.04 LTS / Node v12.11.1:
`sudo apt install libtool-bin`
`yarn/npm add/install sodium`

No issues.

macOS High Sierra / Node v12.11.1:
`brew install libtool autoconf automake`
`yarn/npm add/install sodium`

No issues.

Windows 10 (w/ MSVC buildchain) / Node v12.11.1:
`yarn/npm add/install sodium`

No issues.

Installation requirements found on here: https://github.com/paixaop/node-sodium#install, this was also posted by Vlad above.

**Comment by AbandonedCart** [comment]
@iCrawl So only older linux-based operating systems with the newest Node. Got it. It was a simple question that was already answered. At this point, it just comes off as hostility.

**Comment by iCrawl** [comment]
The "Linux-based" operating system does not matter at all here. And "older" is not even a truthy statement considering Mojave is just one version above High Sierra and Ubuntu 18.04 is only one below 18.10 and LTS, what are you trying to say here?

It also works fine with Node 10 (which is LTS) on all those systems.

It was not already answered because he did not go through all that testing, which I did simply to assure you this works fine on all systems and not "just windows".

**Comment by AbandonedCart** [comment]
@iCrawl Older doesn't mean archaic. It simply means that it is not the current version. LTS versions are not necessarily current even when it is the newest, either. They are milestone versions that will be supported for a longer period than the regular releases.

You do not need a passing build to support a platform, much like you do not necessarily support a platform just because it can be built. "Discord.js works on multiple platforms in a stable manner." answered the question.

**Comment by iCrawl** [comment]
I'll just close this issue up, this discussion is pointless, considering I just told you it works fine on the "latest" (as of posting this) too.

If you want to coin and mince words, you can do that, but please don't fill the issue tracker with it.
If there still is a genuine problem, open a new issue.
