### ISSUE TITLE
channel.fetchMessage not finding message when getting the channel through guild.channels

### ISSUE THREAD

**Issue by NyaStone** [discordjs/discord.js#3133]
I've been trying to fetch a message without needing to know the channel it's in
`return new Promise (function(resolve, reject) {
    guild.channels.forEach(chann => {
      if (chann.type == 'text') {
        chann.fetchMessage(msgId)
        .then(msg => {
          resolve(msg);
        })
        .catch(console.log());
      }
    });
    reject(msgId);
  });`

But it's unable to find an existing message, upon further investigation it's not able to find a message at all if I get the channel by using guild.channels

**Comment by Darqam** [comment]
If the channel with the message is inside that guild then it will be able to fetch just fine. If you have a problem with your code, I recommend you go ask in the [discord server](https://discord.gg/bRCvFy9).

**Comment by NyaStone** [comment]
I tried replacing the bit of code to only look in the message I am writing in by using `message.channel.fetchMessage('messageId')` 
This way it worked.
Then I ran into the same issue again when finding the message like this and retrying to find it again but by using a find on `guild.channels.find` and then use `channel.fetchMessage(messageId)` on it.

**Comment by SpaceEEC** [comment]
You always need a channel (id) when fetching a message, there is no way around that.
Fetching a message id in every channel does not sound like an ideal solution, you should store the channel id along the message id, if somehow possible.

Since this is not a bug report or enhancement suggestion, this should take place in our [Discord server](https://discord.gg/bRCvFy9).
