### ISSUE TITLE
IP Discovery failing

### ISSUE THREAD

**Issue by thiakil** [discordjs/discord.js#3137]
**Please describe the problem you are having in as much detail as possible:**
Full context on Discord https://discordapp.com/channels/222078108977594368/222081003253006336/553515985001512980

While helping Chaz, I found that [this line](https://github.com/discordjs/discord.js/blob/1673b6f8f5bc53a30e2f2ef1123057d4e50c37c8/src/client/voice/networking/VoiceUDPClient.js#L147) needed to have `readUIntLE` changed to `readUIntBE`, or the port sent to the WS connection is wrong.

This is in contrast to the API docs which do say LE - so I wanted to raise it here just in case it's a Node weirdness.

**Include a reproducible code sample here, if possible:**
https://pastebin.com/bBCTfpm5
Also pls see Discord

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 10.7.0
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by amishshah** [comment]
I'm not really sure this is a problem, our current code works for basically every other user, and other libraries also read it as LE -- maybe the fix was just coincidental?

**Comment by thiakil** [comment]
Don't most other users send voice data? Perhaps the voice gateway can realise this and sends back on the port the voice data came from.

I can assure you, the port number sent (as originally decoded) did not match the outbound port in Wireshark, whereas flipping to big endian did. No voice data was received (using the code in the pastebin) before I made the BE switch.

**Comment by thiakil** [comment]
[discord-udp.pcap.zip](https://github.com/discordjs/discord.js/files/2948390/discord-udp.pcap.zip)

Packet capture of what I'm seeing. My NAT will be using the same external port. Sydney voice gateway.

Adding a little extra debug info to discord.js for UDP packet:
```
socket info { address: '0.0.0.0', family: 'IPv4', port: 54732 }
Last two bytes:  <Buffer d5 cc>
parsed 52437 ccd5
```

`54732 == D5CC`

**Comment by Seia-Soto** [comment]
UDP packets can be sent without IP address, I think it is not problem. Please confirm below links before reply :D

- https://superuser.com/questions/1182779/receiving-udp-packets-without-port-forwarding
- https://networkengineering.stackexchange.com/questions/6679/why-no-source-and-destination-ips-in-udp-datagram

**Comment by iCrawl** [comment]
Closing as it is a stale issue, reopen or check open issues if this is still an issue.

**Comment by tete1030** [comment]
I have the same problem. It's really weird. My computer is behind NAT and can not receive any UDP packets except for the first one (the reply of IP discovery packet). However by using `tcpdump` I can see that all packets have arrived at the WAN port of my router. 

I found that the port in all packets except for the first one is different from that used in IP discovery packet. Specifically, they are endian-reversed. That's why those packets were not forwarded to the destination computer since the router can not find matched UDP hole in conntrack during routing. 

After changing `readUIntLE` to `readUIntBE` the problem is solved.

Another thing needed to be noted is that, when I didn't change `readUIntLE` to `readUIntBE`, if I change the server region to `Singapore` or `US West` instead of `Japan` which I usually use, it occasionally is able to receive all UDP packets. I'm not sure why this is happening if `readUintLE` is wrong. An assumption is that it coincidentally used a port that satisfies `little-endian == big-endian`, or the Discord servers are inconsistent on this, considering the IP discovery packet format in discord.js is not current [standard format](https://discord.com/developers/docs/topics/voice-connections#ip-discovery). Besides, in standard format the port is big-endian.
