### ISSUE TITLE
<Channel>.overwritePermissions(...) changes name 

### ISSUE THREAD

**Issue by MrAugu** [discordjs/discord.js#3138]
**Please describe the problem you are having in as much detail as possible:**
When `<Channel>.overwritePermissions(<Role>, ...)` is used, this will change name of the channel to a `.toLowerCase()` version of `<Role>.name`.

**Include a reproducible code sample here, if possible:**
```js
const mutedRole = message.guild.roles.find(r => r.name === "Muted");
message.guild.channels.forEach(async (channel, id) => { // eslint-disable-line
  await channel.overwritePermissions(mutedRole, {
    SEND_MESSAGES: false,
     ADD_REACTIONS: false
  });
});
```

**Further details:**
- discord.js version: v12 Master Branch (Commit: 1673b6f8f5bc53a30e2f2ef1123057d4e50c37c8)
- Node.js version: v11.9.0
- Operating system: Ubuntu 16.04 LTS
- Priority this issue should have – please be realistic and elaborate if possible: Medium

- [x] I have also tested the issue on latest master, commit hash: 1673b6f8f5bc53a30e2f2ef1123057d4e50c37c8

**Comment by SpaceEEC** [comment]
You are passing incorrect parameters to [`GuildChannel#overwritePermissions`](https://discord.js.org/#/docs/main/master/class/GuildChannel?scrollTo=overwritePermissions), you are supposed to pass an options object, with `permissionOverwrites` and `reason` properties.
Under the hood this method will just call [`GuildChannel#edit`](https://discord.js.org/#/docs/main/master/class/GuildChannel?scrollTo=edit) with the object you passed.
Since [`Role`](https://discord.js.org/#/docs/main/master/class/Role) has a [`name`](https://discord.js.org/#/docs/main/master/class/Role?scrollTo=name) (and [`position`](https://discord.js.org/#/docs/main/master/class/Role?scrollTo=position)) property, doing so will edit both of those properties.

You meant to use [`GuildChannel#updateOverwrite`](https://discord.js.org/#/docs/main/master/class/GuildChannel?scrollTo=updateOverwrite) which behaves like [`GuildChannel#overwritePermissions`](https://discord.js.org/#/docs/main/stable/class/GuildChannel?scrollTo=overwritePermissions) on stable.
