### ISSUE TITLE
What is Discordjs? Is it for making discord emojis?

### ISSUE THREAD

**Issue by frostylosty** [discordjs/discord.js#3152]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**
```js

// Place your code here

```

**Further details:**
- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

- [x] I have also tested the issue on latest master, commit hash:

**Comment by Fyk0** [comment]
what the fuck

**Comment by aiospos** [comment]
what the fuck

**Comment by vladfrangu** [comment]
Discord.js is a simple to use API wrapper for Discords API. You *can* also make emojis using it, but it isn't just for that.

**This issue tracker is only for bug reports and suggesting enhancements.**
If you have a question, please ask it in the **[Discord Server](https://discord.gg/bRCvFy9)** instead of opening an issue – you'll be redirected there anyways.
