### ISSUE TITLE
Empty reactions results

### ISSUE THREAD

**Issue by mindhalt** [discordjs/discord.js#3153]
I'm trying to get reactions to one of the pinned messages. I've googled similar [issue](https://github.com/discordjs/discord.js/issues/2413) but solution didn't help.

This piece of code - works as expected and described in mentioned issue:
```typescript
channel.fetchMessages()
  .then(messages => {
    channel.fetchMessage(<hardcoded id of the pinned message>)
      .then((message: Message) => {
        console.log('Message:', message.content);
        console.log('Reactions:', message.reactions.array());
      });
  });
```
or
```typescript
channel.fetchMessage(<hardcoded id of the pinned message>)
  .then((message: Message) => {
    console.log('Message:', message.content);
    console.log('Reactions:', message.reactions.array());
});
```
Returns text of the message and array with reactions to it.

This piece of code - works in unexpected way:
```typescript
channel.fetchPinnedMessages()
  .then(messages => {
    console.log(messages.first().id);
    channel.fetchMessage(messages.first().id) // or hardcoded id of the pinned message
      .then((message: Message) => {
        console.log('Message:', message.content);
        console.log('Reactions:', message.reactions.array());
      });
  });
```
Returns text of the message and EMPTY array of reactions.

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 11.11.0
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible: Normal

- [x] I have also tested the issue on latest master(with code modifications described in Wiki), commit hash: df1889ab4902416de2bf6b3c144d55e35dbf116f

**Comment by almostSouji** [comment]
This is the case due to API limitations and appropriately documented at <https://discord.js.org/#/docs/main/master/class/MessageStore?scrollTo=fetchPinned> as `The returned Collection does not contain any reaction data of the messages. Those need to be fetched separately.`

**Comment by izexi** [comment]
Reiterating what @almostSouji just commented, due to an API limitation fetchPinned returns Messages with empty `reactions` Collections.

Although, you did attempt to fetch the message separately, this is where the issue arises. TextChannel.fetchPinnedMessages() will also cache the fetched messages.
https://github.com/discordjs/discord.js/blob/be2f78851f55b6e3e9a5dfcfa7af78e039ba3954/src/structures/interfaces/TextBasedChannel.js#L265
Therefore, when you try and fetch the message separately it will just return the already cached message with an empty Message.reactions collection.
https://github.com/discordjs/discord.js/blob/be2f78851f55b6e3e9a5dfcfa7af78e039ba3954/src/client/rest/RESTMethods.js#L485-L486

A hacky workaround would be to *uncache* the message by doing `channel.messages.delete(messages.first().id);` before attempting to fetch it.
I will be opening a PR soon on the master branch that allows the developer to pass a `cache` parameter within MessageStore.fetchPinned(), similiarly to how it is on MessageStore.fetch(...)

**Comment by almostSouji** [comment]
Was about to edit the response due to not reading the issue correctly, Above is the gist of it.
However I'd propose to use <https://discord.js.org/#/docs/main/stable/class/Collection?scrollTo=sweep> instead to uncache (also since this issue might come up in google searches for people with more than one message being fetched)
```js
// discord.js 11.4.2+
txtchannel.messages.sweep(message => fetchedMessages.has(message.id))
// uncaches all messages from the channel that are in the fetchedMessages Collection
```
After this you can fetch the Message via `txtchannel.fetchMessage/s` or `messagestore.fetch` respectively (for master)

We will add the requirement to uncache to the documentation, thanks for the pointer!

**Comment by mindhalt** [comment]
Yeah, I had a thought that it might be related to cached messages. Thanks guys for quick response.
@almostSouji tried your solution - worked like a charm.
