### ISSUE TITLE
messageUpdate: Partial Members are still null

### ISSUE THREAD

**Issue by Jyguy** [discordjs/discord.js#3263]
**Please describe the problem you are having in as much detail as possible:**
Having partials enabled for `GUILD_MEMBER` does not seem to work for `Client#messageUpdate`. I have not encountered any other cases with other events, but I am sure that uncached member objects are null in that event.

If I am misunderstanding what the purpose of the `GUILD_MEMBER` partial option is, please let me know. There also might be some other condition for it to be null, as I am not sure if this "condition" is being uncached. All I know is that this occurs from time to time.

**Include a reproducible code sample here, if possible:**
```js
const Discord = require('discord.js');
const client = new Discord.Client({
  partials: ['GUILD_MEMBER']
});

client.on('ready', () => console.log('I am ready!'));

client.on('messageUpdate', (oldMessage, newMessage) => {
  console.log(newMessage.member); // Will be null if uncached
});

client.login('token');
```

**Further details:**
- discord.js version: master
- Node.js version: v11.14.0
- Operating system: Manjaro v18.0.4
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [x] I have also tested the issue on latest master, commit hash: 75d5598fdada9ad1913b533e70d049de0d4ff7af

**Comment by izexi** [comment]
PartialTypes.GUILD_MEMBER isn't used within the `messageUpdate` event. 
It is used to ensure that you receive the `guildMemberRemove` event for uncached members (by passing a partial instance of a member) along with Guild#me and Guild#owner.

The only PartialTypes that are being used here is `USER` and `CHANNEL` (for DMs). So, if you wanted to retrieve Message#member within this event you will need to use [GuildMemberStore#fetch()](https://discord.js.org/#/docs/main/master/class/GuildMemberStore?scrollTo=fetch) passing the User instance, keep in mind that you will need to call fetch beforehand on the partial message in order to access the author property.

**Comment by Jyguy** [comment]
Thank you for the clarification, closing this issue.
