### ISSUE TITLE
Odd error thrown when attempting to send multiple avatarURLs

### ISSUE THREAD

**Issue by Vistril** [discordjs/discord.js#3267]
**Please describe the problem you are having in as much detail as possible:**
When attempting to send a message of the URL's of every user in the guild, it only sends about a third and throws this error: 
"TypeError: Cannot destructure property `reply` of 'undefined' or 'null'."
 I don't know how that's in relation at all to the code sample below.

**Include a reproducible code sample here, if possible:**
```js
let b = msg.guild.members.map(x => x);
for (let i in b) {
   client.channels.get('channel id').send(b[i].user.avatarURL)
}
```

**Further details:**
- discord.js version: ~~11.4.2~~ happens on new release 11.5.0 too 
- Node.js version: v8.15.0
- Operating system: Ubuntu 16.04.5 LTS
- Priority this issue should have – please be realistic and elaborate if possible:
Decently low, not many other people should want to mass send profile pictures of members in their guild

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by GamesProSeif** [comment]
I used the same code sample on my guild which has 4 members only, and the expected output was achieved. I tested it in [discord.js@11.4.2](https://github.com/discordjs/discord.js/releases/tag/11.4.2), [discord.js@11.5.0](https://github.com/discordjs/discord.js/releases/tag/11.5.0), and in the [master branch](https://github.com/discordjs/discord.js).

If anything is going to happen, you will get rate limited due to the repetitive API call (API spam); as you are sending a message containing the avatar URL for every member.

Are you doing anything rather than that code sample? Like some side functions or events might be triggered without notice containing [Message#reply](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=reply).

**Comment by Vistril** [comment]
I expected being ratelimited, but shouldn't Discord resume the buffer?
Is there a ratelimit on requests for profile pictures?
I haven't modified .reply in anyway, and the code in the sample is all that's being run

**Comment by Darqam** [comment]
Although it might be worth looking into it, you realize that code is crazy api spam right? You would be far better off pushing those to an aray or something and sending a concatenated string which would make far fewer api calls.

**Comment by tipakA** [comment]
I ran code from example and indeed got the error.
However, interestingly enough, when i replaced sending with logging to console, and then ran it in same guild in same minute, error wasn't thrown.

**Comment by Vistril** [comment]
It might be related to the large amount of API calls. I still don't understand the relation with [Message#reply](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=reply), though.

**Comment by SpaceEEC** [comment]
Could you please show the stacktrace of the error and the string being send?
I can not see how this would happen when sending a string.

**Comment by KinectTheUnknown** [comment]
It could be possible that a Member does not have a custom avatar since ur using `User.avatarURL` as opposed to `User.displayAvatarURL`. Sending `undefined` gives an "Can't send empty message" error.

**Comment by amishshah** [comment]
Can you confirm if @KinectTheUnknown's comment was valid?
