### ISSUE TITLE
messageReactionRemove not firing for messages with pre-existing reactions.

### ISSUE THREAD

**Issue by ashlin4010** [discordjs/discord.js#3281]
**Message Reaction Not Updating Correctly**

MessageReaction.count is off by one when a message with a pre-existing reaction has it's reaction removed and re-added. 

**Steps to reproducible:**

Send a message and add a reaction.
Run code below.
Remove previously added reaction: Expected messageReactionRemove should fire but does not.
Add same reaction to the message: Expected  messageReaction.count should 1 but is 2.

```js
const Discord = require('discord.js');
const client = new Discord.Client();

client.on('ready', () => {
    console.log('Bot ready!');

    // all text channels for the first guilds.
    let textChannels = client.guilds.first().channels.array().filter(value => {return value.type === "text"});

    // loads the last 20 messages of each text channel.
    for(let channel of textChannels){
        channel.fetchMessages({ limit: 20 })
            .then(messages => console.log(`Received ${messages.size} messages`))
            .catch(console.error);
    }
});

client.on('messageReactionAdd', messageReaction  => {
    console.log("ReactionAdd: " + messageReaction.count);
});

client.on('messageReactionRemove', messageReaction  => {
    console.log("ReactionRemove: " + messageReaction.count);
});

client.on('messageReactionRemoveAll', messageReaction  => {
    console.log("RemoveAll: " + messageReaction.count);
});

client.login('token');
```

**Further details:**
- discord.js version: 11.5.0
- Node.js version: v10.15.1
- Operating system: Windows 10

- [x] I have also tested the issue on latest master, commit hash: abebeac193f70e25c842cf4e51e12dd53e1096ca

**Comment by izexi** [comment]
The `messageReactionRemove` event relies on [MessageReaction#users](https://github.com/discordjs/discord.js/blob/stable/src/structures/Message.js#L588), which will not be initially populated on uncached messages. As for a solution, you will need to call [MessageReaction#fetchUsers()](https://discord.js.org/#/docs/main/stable/class/MessageReaction?scrollTo=fetchUsers) after fetching the Message itself. Since you will be doing this iteratively for 20 messages (for n amount of reactions on each message) on every TextChannel on a Guild this could end up getting a bit API spammy so you may want to look into using the `raw` event instead, [here's](https://discordjs.guide/popular-topics/reactions.html#emitting-the-event-s-yourself) a guide to help you work through that. If you're willing to transfer over to the master branch you can make use of [Partials](https://discord.js.org/#/docs/main/master/topics/partials) to avoid having to work with the `raw` event, keep in mind that there are breaking changes from stable to master (most of them are covered [here](https://github.com/discordjs/guide/blob/v12-changes/guide/additional-info/changes-in-v12.md)).

**Comment by ashlin4010** [comment]
Awesome thanks that's exactly what I needed
