### ISSUE TITLE
Member Mute & Defean in fetchAuditLogs & on("guildMemberUpdate")

### ISSUE THREAD

**Issue by WILDDIP** [discordjs/discord.js#3323]
**Please describe the problem you are having in as much detail as possible:**
`MEMBER_UPDATE` in `AuditLogAction` doesn't detect, when anyone Mute(unmute) or Defean(undefean) other members.

`Client` event `guildMemberUpdate` doesn't detect this too.

**Include a reproducible code sample here, if possible:**
```js
client.on(`guildMemberUpdate`, async (client, oldMember, member) => {
  if (oldMember.serverMute !== member.serverMute) return console.log(`${member.user.tag} has been muted!`);
  // Doesn't work!

});

```
```js
/**
 * @param { Discord.GuildMember } member
 */
let entry = await member.guild.fetchAuditLogs({type: 'MEMBER_UPDATE'}).then(async audit => audit.entries.first());
if (entry.executor.id === member.user.id) return;

let channel = member.guild.channels.find(c => c.name === `logs`);
if (!channel) return;
channel.send(`${entry.executor} muted ${member.user}`);
// Doesn't work!

```

**Further details:**
- discord.js version: 11.5.1
- Node.js version: 11.12.0
- Operating system: Windows 10 x64
- Priority this issue should have: low

- [x] I have also tested the issue on latest master, commit hash: [`405bdb5`](https://github.com/discordjs/discord.js/commit/405bdb5b558eff478d0bde739cee1ee8e40c330b)

**Comment by almostSouji** [comment]
1) Server mute and deafen emit as `voiceStateUpdate` not as `guildMemberUpdate`
2) Neither of the two events emit the client, but only the guild member* prior to and after the changes as only two parameters in that exact order
3) Does the second approach depend on the first? In that case that's why it doesn't get executed, the muting does not emit `guildMemberUpdate`.

Generally your audit logs checks are insufficient, `entry.changes` will hold the changes applied to the guildmember when `MEMBER_UPDATE` is logged. 
```js
{ key: 'deaf', old: true, new: false }
```
```js
{ key: 'mute', old: true, new: false }
```
These are the respective changes entries for deafen and mute.

Sidenote: self server mutes can not happen, normal self mutes do not produce audit logs
The same applies to server deafen.

\**applies for 11.5.x, 12.0.0-dev emits a VoiceState which works a little differently*

In general: If things don't work out as you expect, please try to join the Discord server (https://discord.gg/bRCvFy9) and ask your question there before opening an issue.

**Comment by WILDDIP** [comment]
thx
