### ISSUE TITLE
Green checkmark MessageReaction not collected properly

### ISSUE THREAD

**Issue by pandaniell** [discordjs/discord.js#3394]
In the below example, the green checkmark is not included in the collection when not placing any reaction manually, the red cross is collected regardless of users reacting to it or not, tested on the latest version of Master
```typescript
const msg = (await message.channel.send('something')) as Message;

const validReactions = ['✅', '❌'];
for (const reaction of validReactions) await msg.react(reaction);

try {
  const filter = (reaction: MessageReaction): boolean => validReactions.includes(reaction.emoji.name);
  const results = await msg.awaitReactions(filter, { time: 3e4 }); // 30 seconds

  console.log(results);

  await msg.edit(
    `✅: ${results.get('✅').count - 1}\n❌: ${results.get('❌').count - 1}`,
  );

  msg.reactions.removeAll();
} catch (error) {
  console.log('Vote.ts', error); // Cannot read property 'count' of undefined
}
```

**Comment by Androz2091** [comment]
I confirm the problem. I tested the code in javascript (and not in typescript) and it's the same, when the collector ends only the red cross reaction appears and the green cross is not detected. On the other hand, a `console.log(message.reactions);` returns the both reactions.

**Comment by SpaceEEC** [comment]
You are observing a race condition here.

The bot adds the two reactions `✅` and `❌` and waits for the REST call to finish before proceeding each.
Those rest calls are followed by a gateway `MESSAGE_REACTION_ADD` packet at some point in the future (the race condition part).

In your case the `✅` reaction was already received before you created the collector and the `❌` was not and therefore the former is missing.

What you could do is:
- Use a ternary and default to `0` 
- Add the reaction after creating the collector (so you receive your bot's reactions)
- Use `Message#reactions` to read the reactions from
  Note that in this case you might want to also account for somebody else removing your bot's reactions. (Otherwise you would still get that error)
