### ISSUE TITLE
Unable to get user's avatar via ID if they have default avatar

### ISSUE THREAD

**Issue by Salvation5051** [discordjs/discord.js#3523]
Whenever I try to get someone's avatar via their ID with the following code, in case they have the default avatar it won't work

```js
client.fetchUser('ID').then(u => { 
   this.storeValue(u.avatarURL, 1, "ID", cache)
})
```

**Further details:**
- discord.js version: Latest
- Node.js version: Latest
- Operating system: Linux

**Comment by Monbrey** [comment]
This is expected behavior. `User#defaultAvatarURL` provides a fallback which will return the default avatar if they do not have one set.

This issue tracker is only for bug reports and enhancement suggestions. If you need help with discord.js installation or usage, please go to the discord.js Discord server instead: https://discord.gg/bRCvFy9

**Comment by devsnek** [comment]
You're probably looking for displayAvatarURL: https://discord.js.org/#/docs/main/stable/class/ClientUser?scrollTo=displayAvatarURL

**Comment by Salvation5051** [comment]
> You're probably looking for displayAvatarURL: https://discord.js.org/#/docs/main/stable/class/ClientUser?scrollTo=displayAvatarURL

Thanks!
It was the solution
