### ISSUE TITLE
Error : Incorrect Login Details were Provided

### ISSUE THREAD

**Issue by EnZWebAppZ** [discordjs/discord.js#3528]
My Bot works locally but when it goes on my VPS it seems to be unable to connect.
Have tried regenerating new Token but the error remains.
What could be the issue here?

**Comment by Monbrey** [comment]
The issue template exists for a reason, please do not ignore and remove it.

If you need help with discord.js installation or usage, please go to the discord.js Discord server instead: https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions.

When you do go to the Discord server, please provide the actual error you're receiving instead of expecting us to magically know the problem you're having without providing any information.
