### ISSUE TITLE
role.serialize() not working

### ISSUE THREAD

**Issue by SammyWhamy** [discordjs/discord.js#3567]
The problem I'm experiencing:
When I use the method .serialize() on a role object, it returns an error.

**Include a reproducible code sample here, if possible:**
```js
let role = message.guild.roles.get("640015756657950720");
role.name
// -> shows the name of this role
role.serialize()
// -> RangeError: Invalid permission string or number.
```

**Further details:**
- discord.js version: 11.5.1 (Latest)
- Node.js version: 10.15.3
- Operating system: Windows 10
- Priority this issue should have: Low to mid

![image](https://user-images.githubusercontent.com/45788465/68432661-2a621200-01b5-11ea-957b-7cf56bf24c4d.png)

**Comment by bdistin** [comment]
what does `role.permissions` give you?

**Comment by SammyWhamy** [comment]
`role.permissions` returns `104193601` in the case of this role.

**Comment by SpaceEEC** [comment]
This likely is because you (or some dependency you are using) added enumerable properties to `Object.prototype`.

A short example to reproduce this:
```js
const Discord = require('discord.js');

// Works, logs the expected object
console.log(new Discord.Permissions(104193601).serialize());

Object.prototype.noop = function noop() { return this; };

// Throws your error: RangeError: Invalid permission string or number.
console.log(new Discord.Permissions(104193601).serialize());
```

The ideal solution for this is to simply not mess with native prototypes.

If you can't (or simply don't want to), you can add them non-enumerable.
For my example that would be using: `Object.defineProperty(Object.prototype, 'noop', { value: function noop() { return this; } });`

---

Regardless of that, we should probably guard `for..in` loops in our code-base. (Or just get rid of them completely)
Guards are already added in some places, but not all of them, permissions being one of them.
