### ISSUE TITLE
`C:\DODM\node_modules\discord.js\src\structures\MessageAttachment.js:28     this.id = data.id;                    ^  TypeError: Cannot read property 'id' of undefined`

### ISSUE THREAD

**Issue by goldentg** [discordjs/discord.js#3592]
asked on discord, no one could help 
```
  const attachment = new Discord.MessageAttachment('https://i.imgur.com/fO81mhz.jpg');

	member.send(Attachment);
```

**Comment by almostSouji** [comment]
Leaving this here In case the issue comes up for someone via search:
- The [MessageAttachment](https://discord.js.org/#/docs/main/stable/class/MessageAttachment) class is used for received embeds and includes a client reference, as well as an attachment id.
- The [Attachment](https://discord.js.org/#/docs/main/stable/class/Attachment) class is what you should be using on v11.
- On v12 these two classes were merged into MessageEmbed.

---
If you need help with discord.js installation or usage, please go to the discord.js Discord server:
  https://discord.gg/bRCvFy9
