### ISSUE TITLE
<Role>.members should be MemberStore

### ISSUE THREAD

**Issue by AseCoder** [discordjs/discord.js#3611]
**Is your feature request related to a problem? Please describe.**
when i want all the members that have a role in a guild, i do `<Role>.members`. if all the guild's members are not cached, this wont work, as `<Role>.members` is a Collection of the **cached** members. the members could be fetched if it was a MemberStore.

**Describe the ideal solution**
change `Role.members` to a MemberStore

**Describe alternatives you've considered**
an alternative solution that i have considered is to fetch all the members in a guild and then filter out the ones who dont have the role, but this is inefficient.

**Comment by Monbrey** [comment]
In theory what you're asking for makes sense, but in practice it doesn't quite work like that - the API doesn't allow us to fetch only members that have a certain role. That's why a `RoleMemberStore` doesn't exist.

Your alternative solution is closer to correct, but there's no need to filter yourself. Fetch all members using `GuildMemberStore.fetch` then access `<Role>.members` - it's just a getter that does the filtering for you.
