### ISSUE TITLE
"bot.messages" Collection

### ISSUE THREAD

**Issue by dhBunny** [discordjs/discord.js#3615]
Add a `bot.messages` collection.
It would have the same methods as a `Message` (edit, delete, etc)

It would be using the Message ID, and since Discord.js has a lot of features, I am surprised it hasn't got this feature. 
This feature would be useful for editing messages that were sent some time ago and an user wants to edit the message. 

**Example:**
```js
bot.messages.get('123456789').edit('Hello!' This message is edited!');
```

**Comment by Darqam** [comment]
Why not use `channel.messages` collection? To find a message you need the channel since message ids aren't guaranteed to be unique (discord wide).

You can always go `<client>.channels.get('channelId').messages.get('id')` (or use <channel>.messages.fetch() for the uncached ones.

So I'm not quite sure how the suggestion you bring up would function differently than what is already in place.

**Comment by dhBunny** [comment]
Oh! I didn't know that existed, sorry. Thank you very much!
