### ISSUE TITLE
TS2339: Property 'send' does not exist on type 'Channel'.

### ISSUE THREAD

**Issue by stevemarksd** [discordjs/discord.js#3622]
Just installed this lib and I'm getting `TS2339: Property 'send' does not exist on type 'Channel'.` I guess you need to update the types.

**Comment by tipakA** [comment]
And that is completely correct. [Here are the docs.](https://discord.js.org/#/docs/main/master/class/Channel)

Since [CategoryChannel](https://discord.js.org/#/docs/main/master/class/CategoryChannel), [TextChannel](https://discord.js.org/#/docs/main/master/class/TextChannel), [VoiceChannel](https://discord.js.org/#/docs/main/master/class/VoiceChannel) and other types *extend* [GuildChannel](https://discord.js.org/#/docs/main/master/class/GuildChannel), which itself *extends* [Channel](https://discord.js.org/#/docs/main/master/class/Channel), there is no way there will be `send` for all of them. You can't send messages to voice channels nor categories.

**Comment by vzwGrey** [comment]
The `Channel` class does not have a `send` method, because categories and voice channels are also a child classes of the `Channel` class. When you're certain you have a *text* channel you can cast it to a TextChannel like so:
```ts
(channel as TextChannel).send('hello!');
```
You have to import `TextChannel` from the discord.js library for it to work.

For further questions please come by the [official Discord server](https://discord.gg/bRCvFy9).

**Comment by stevemarksd** [comment]
the tutorial says this: https://discordjs.guide/popular-topics/common-questions.html#how-do-i-send-a-message-to-a-certain-channel I guess the tutorial is wrong in this case.

I think the casting solution is just a hack, not a proper solution or I am wrong?

**Comment by tipakA** [comment]
Tutorial is written for JavaScript, not TypeScript.

**Comment by stevemarksd** [comment]
then you have no type safety. 

The proper way to do it, would be like this:

```
if(channel.type === ChannelType.text){
   channel.send(`bla`)
}
```

your channel will be of type: TextChannel|CategoryChannel|VoiceChannel

Casting is a hack because loses all the benefits of typing.

**Comment by didinele** [comment]
Would be lovely if you gave more context.

For instance, accessing the channel property from a message results in a TextBasedChannel, which does have the send method.
This is the case for a lot of other situations, so I'm assuming you're running get on a ChannelStore/Collection, in which case, there's no way for d.js to tell the type of the channel.

Also, you never mentioned the version you're on, master had its typings pretty much refactored, and they are much more accurate, however, those changes will not be backported to any other version.

**Comment by stevemarksd** [comment]
im on the 12.0.0-dev version. What context would you need?

I'm basically trying to follow the guide from here: 

```
const channel = <client>.channels.get('<id>');
channel.send('<content>');
```

**Comment by didinele** [comment]
wonderful, and how do you want us to figure out the type of that channel again?
`<client>.channels` is a `ChannelStore`, which extends `DataStore`.. which extends `Collection`, which... extends the nodejs `Map`

`<client>.channels` ends up being a `Map<string, Channel>`

so anyway, if you think you have a solution feel free to PR, but spoiler alert, there's nothing you can do about it, that isnt "hacky", so for that blessed get method you'll simply have to use `as` all the time.

**Comment by Kyriakos03** [comment]
Discord.js new version doesnt working

**Comment by stevemarksd** [comment]
@didinele as i've said there is no way to put a key called type in the channel you return?

**Comment by almostSouji** [comment]
> Discord.js new version doesnt working

Please be either more specific, if it has anything to do with this specific topic, or, preferably come to the discord server: https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.

**Comment by didinele** [comment]
No, there isn't a way, we have a map, the element returned cannot be determined inside of the typings.

**Comment by rahultrivedi180** [comment]
```typescript
const channel: TextChannel = discordClient.channels.cache.get('channel id') as TextChannel;
await channel.send('content');
```

Worked for me
