### ISSUE TITLE
Custom Status instead of Game name

### ISSUE THREAD

**Issue by lars0403** [discordjs/discord.js#3639]
**Please describe the problem you are having in as much detail as possible:**
I was getting the game names of the users on my server until recently.
After Custom Statuses came out, I mostly get "Custom Status" as an output.

**Include a reproducible code sample here, if possible:**
```js

msg.author.presence.game
// It returns Custom Status even if they are playing a Game.

```

**Further details:**
- discord.js version: 11.5.1
- Node.js version: 12.12.0
- Operating system: Windows Server
- Priority this issue should have – please be realistic and elaborate if possible: Normal Priority

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
You are just getting "Custom Status" because that's because of how Discord implemented it.
(Although they eventually:tm: are going to fix that)
But for now the custom status text is to be found in [`Game#state`].

Regarding the "not being able to name of games", that's because discord.js does not support multiple activities yet.
Discord sends the current `game` and an array of `activities` ([docs]), the latter is currently not handled by us.

[`Game#state`]:https://discord.js.org/#/docs/main/stable/class/Game?scrollTo=details
[docs]:https://discordapp.com/developers/docs/topics/gateway#presence-update-presence-update-event-fields

**Comment by lars0403** [comment]
Ah that's good to know.
Thanks for the info
