### ISSUE TITLE
Emojis limit.

### ISSUE THREAD

**Issue by Sid-Athos** [discordjs/discord.js#3669]
Hello friends,

My bot has a command which allows him to create emojis using an url, and it happens that the API doesn"t allow me to set the limit of emojis that can be uploaded according to the server levels.

So far the code was like this :

`if ( msg.guild.emojis.size < 50 )
{`

And it would be great if I could just do this :

`if ( msg.guild.emojis.size < msg.guild.emojis.emojisLimit )
{`

**Comment by tipakA** [comment]
Considering that you mention API returning error, *without seeing error* i'm going to assume that this is not a problem with library. Nowhere in code for creating emotes, both on stable and master i can find anything that would in any way indicate any hardcoded limit. Methods resolve passed arguments and call REST methods to perform API calls.
If the problem is that API does not allow bots to create emotes after 50, no matter how many emote slots server has, then it's more of an API problem. On the other side, i don't really see how it would do so, as desktop client performs calls on the same API.

**Comment by Monbrey** [comment]
11.5-dev and master both include `<Guild>.premiumTier` which would allow you to determine what the unlocked limit is.

**Comment by Sid-Athos** [comment]
Thank you sir
