### ISSUE TITLE
messageUpdate is not triggered on some embeds

### ISSUE THREAD

**Issue by Renari** [discordjs/discord.js#3685]
**Please describe the problem you are having in as much detail as possible:**
The `messageUpdate` event is not triggered when embeds are added to messages with Pixiv url.

**Include a reproducible code sample here, if possible:**
```js

const DISCORD_TOKEN = '';

const Discord = require('discord.js');
const discordClient = new Discord.Client();

discordClient.login(DISCORD_TOKEN).then(() => {
  discordClient.on('messageUpdate', (message) => {
    console.log('called on ' + message.content);
  });
});

```

**Further details:**
- discord.js version: 11.5-dev
- Node.js version: 12.14.0
- Operating system: W10
- Priority this issue should have – please be realistic and elaborate if possible: medium

- [x] I have also tested the issue on latest master, commit hash:

**Comment by Renari** [comment]
This appears not to happen on master.

**Comment by Jyguy** [comment]
According to my testing, it seems that if Discord has already processed a link's specific embed recently (presumably in their cache), it will not emit the `MESSAGE_UPDATE` event for future messages that contain the same link's embed.

For example: the first time a user sends a message with the link https://www.google.ca/ and the embed processes; Discord will emit the event. However, the future messages with the _same link_ will still load the embed with the exception of emitting the event until what I am assuming is the link/embed being removed from their cache.

I do not believe this is an issue with Discord.js since the library cannot do anything about this (afaik)

**Comment by Renari** [comment]
Going to close this, since it isn't a bug, as Jyguy said if an embed is still in Discords cache the embed is sent with the original message, if not it's sent with the message update event.
