### ISSUE TITLE
dead ffmpeg farm after client reconnect

### ISSUE THREAD

**Issue by Roki100** [discordjs/discord.js#3770]
**Please describe the problem you are having in as much detail as possible:**
if using d.js internal music modules, everything works fine but after client gets disconnected from discord and gets reconnected, ffmpeg processes are not being despawned but these take 0% cpu, are attached to no dispatcher/connection (from what i found) and just taking memory causing the bot to be huge memory leak
^ thats what i think and my tests points at

**Include a reproducible code sample here, if possible:**
```js

i dont think thats code-related

```

**Further details:**
- discord.js version: 11.5.1
- Node.js version: 10.4.1
- Operating system: ubuntu 16.04
- Priority this issue should have – please be realistic and elaborate if possible: medium

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Deivu** [comment]
I assume this has something to do with re-indentifies as resumed sessions don't disconnect on going voice sessions.

**Comment by amishshah** [comment]
@Roki100 out of curiosity, are you able to replicate this on master?

**Comment by Roki100** [comment]
didnt tried yet, but i will try to replicate it on master after i will be back home (going to sleep rn)

**Comment by Roki100** [comment]
okay so, i have tried testing music bot locally on master, and when im calling `<StreamDispatcher>.end()` ffmpeg does not despawn for some reason, thats what i managed to do:
![34419-Taskmgr_2020-02-22_15-22-59](https://user-images.githubusercontent.com/35699619/75094005-3e285d00-5587-11ea-992f-9dbd120f2948.png)
i simply queued some songs and skipped them via command, new ffmpegs was spawning, old ones was not despawning
tested on commit `bbdbc4cfa789383b7b3dbecf5e6b8401ea2dd998`/`fe7df70`

**Comment by Roki100** [comment]
okay so after doing a **really long** tests on v12 it seems the issue still occur for me

**Comment by amishshah** [comment]
Hi there,

We're working on a new implementation of Discord's Voice API that has better playback quality and is more reliable than what we currently support in Discord.js v12 - check it out at https://github.com/discordjs/voice!

The new library solves many of the issues that users are facing, and as part of this, we're dropping built-in support for voice in our next major release. We have a PR (https://github.com/discordjs/discord.js/pull/5402) that adds native support for our new voice library - once this PR is merged, this issue will be closed.

You can still use our new voice library before that PR lands - just take a look at [our music bot example](https://github.com/discordjs/voice/tree/main/examples) to see how to get started upgrading your voice code. By using the boilerplate music player in the example, you can make it even easier to upgrade your code.

Note that the PR above only reduces some of the boilerplate code you'd otherwise have to write - you do not have to wait for the PR to be merged to start using the new voice library.

-----

If you have any questions about this, feel free to:

- [Make an issue](https://github.com/discordjs/voice/issues) if you have found a bug in the new voice library
- Use [GitHub Discussions](https://github.com/discordjs/voice/discussions) or join our [Discord server](https://discord.gg/djs) (we have a new channel, `#djs-new-voice`, specifically for this!) to ask general questions about the library, give feedback on the library, and get support with upgrading to it
