### ISSUE TITLE
Support arguments for broadcastEval

### ISSUE THREAD

**Issue by Androz2091** [discordjs/discord.js#3788]
**Is your feature request related to a problem? Please describe.**
We can't pass arguments as additional parameters when using a function for `ShardClientUtil#broadcastEval()`.

**Describe the ideal solution**

It would be nice if we could do something like that:
```js
client.shard.broadcastEval((channelID, param2, param3) => {
    return this.channels.get(channelID);
}, "618121508929142833", "param2", "etc...");
```

**Describe alternatives you've considered**
Actually we can use:
```js
client.shard.broadcastEval(`this.channels.get('${channelID'}`);
```
but sometimes that's complicated:
```js
const embed = new Discord.MessageEmbed()
.setAuthor("Something with a '");

// Stringify and escape the '
const stringEmbed = JSON.stringify(embed).replace(/'/g, "\'");

client.shard.broadcastEval(`
    let embed = JSON.parse('${stringEmbed}');
    this.channels.cache.get('${channelID}').send({ embed });
`);
```
will become:
```js
const embed = new Discord.MessageEmbed()
.setAuthor("Something with a '");

client.shard.broadcastEval((embed, channelID) => {
    this.channels.cache.get(channelID).send(embed);
}, embed, channelID);
```

It would be very simpler if we could pass arguments.

Puppeteer allows this for the [`page#evaluate()`](https://github.com/puppeteer/puppeteer/blob/v2.1.1/docs/api.md#pageevaluatepagefunction-args) method.

**Comment by appellation** [comment]
I like the idea, but I would be hesitant to support this being added into the library. `broadcastEval` relies on (de)serialization to pass messages to and from your shards, and accepting parameters of arbitrary types opens the door for a ton of inconsistency on your end. Take, for example:

```js
class Foo {
  a = 'bar';

  toString() {
    return 'baz';
  }
}
```

Passing an instance of the class would likely result in the value `'baz'` being passed into your function callback, which may or may not be what you expect. Furthermore, this would also rely on Discord.js performing the serialization of the function and all the parameters correctly.

While this is definitely doable, I think that passing a string into `broadcastEval` is probably the safest method of achieving this result.

---

As to your specific example, you can always instantiate the embed in the broadcasted code rather than in your client. This would save you the trouble of serializing it yourself.

**Comment by Androz2091** [comment]
Ok, I understand. I didn't know it wasn't possible to pass anything other than a string from one shard to another. Indeed, Puppeteer's `page#evaluate()` method doesn't have this problem, everything is in the same process. It seemed cleaner to me to pass a function (it would allow syntax highlighting and auto formatting with Prettier for example), to avoid large blocks of string in the code, but you're probably right, passing a string is probably the safest way for `broadcastEval`.
