### ISSUE TITLE
Experiment with private fields (Remove .token property from everything)

### ISSUE THREAD

**Issue by AlexejheroYTB** [discordjs/discord.js#3801]
1. No one uses it - The token property is the same as the token used in bot.login, so that can just be used instead
2. It's problematic for open evals - Open evals are very hard to implement because every object has a .token property

**Suggestion**
Remove the token property on objects, or at least make it inaccessible from outside the class.

**Comment by DevYukine** [comment]
1. Thats for internal usage, d.js needs to use the token **after** you login for rest calls (such as fetching messages from a channel)

2. **Don't ever have an open eval**, eval is very insecure in itself and is not made to be open, dont even try to get around that even with "libraries" which allow to sandbox your enviroment you can **never** be sure that users can't escape it so you should not make an eval open and also d.js is not responsible for you having such a feature.

**Comment by tipakA** [comment]
`client.token` is used for every call to the api.
Removing it because it makes your open eval problematic does not solve the problem - you're giving access to most powerful tool your bot has. `client.token` is honestly one of least interesting things someone could get with open eval.
Javascript does not have a concept of private properties, so there is no way to make it inaccessible from outside

**Comment by kyranet** [comment]
> how is that supposed to work? in javascript there is no such thing as access modifiers (atleast not in the current nodejs v8 version)

Private fields (supported since Node.js 12.4.0, [check here](https://node.green/#ESNEXT-candidate--stage-3--instance-class-fields-private-instance-class-fields-basic-support)):

```javascript
class A {
	#thing;
}
```

We're targetting Node.js 12 soon in master, this is doable, though we'll need to change some things around since REST needs to access to the token.

**Comment by AlexejheroYTB** [comment]
For node 8, closures can simulate private properties

**Comment by AlexejheroYTB** [comment]
I do not have an open eval, but I have to rely on a Google library to disallow code injection... (which has its bugs...)

**Comment by kyranet** [comment]
> For node 8, closures can simulate private properties

<details>
<summary>No. They're flawed, which is why most JS engines went for a WeakMap approach</summary>

```javascript
// IIFE to "hide" the weakmap. In single-class structures this is not needed.
(function Client() {
	const weakmap = new WeakMap();

	return class Client {
		constructor(options) {
			this.options;
			// Do constructor's stuff
		}

		login(token) {
			weakmap.set(this, token);
			// Do login stuff
		}
	}
})();
```

</details>

Besides, we're targeting latest LTS, which currently is Node.js 12, if we go into private fields, we'll do with `#token`, not with [WeakMaps](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap) or [closures](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures).

**Comment by iCrawl** [comment]
>I do not have an open eval, but I have to rely on a Google library to disallow code injection... (which has its bugs...)

Sounds like a XY problem.

We are most likely going to experiment with private fields but certainly not anytime soon nor because of `this` specific use/edge case.

**Comment by AlexejheroYTB** [comment]
Not an XY problem. I'm using Google's Blockly library to allow users to make their own bot using puzzle pieces. Unfortunately, despite all my efforts, Blockly sometimes allows code injection due to bugs.

**Comment by tipakA** [comment]
That's exactly an XY problem.
You're trying to "secure" Blockly by modifying discord.js to not allow access to token.

**Comment by iCrawl** [comment]
That is exactly what makes it XY.

Another library has bugs/issues, hence *we* should change something to "fix" that library.

**Comment by AlexejheroYTB** [comment]
I'm not trying to "fix" the library, I'm trying to minimize the damage in case something unexpected happens. That's why I didn't even bring it up.

**Comment by DevYukine** [comment]
I dont think you exactly get what ICrawl and tipakA are trying to say, this library should not do changes for you because it could "damage" your application which relies on an external library that lets people inject code. This is not an **issue** with discord.js but with Google's Blockly library and we should not do such changes since it would also be a major change (atleast for the Client#token property remove).

**Comment by AlexejheroYTB** [comment]
This is not about my bot. _That's why I didn't bring it up in the first place..._ There are other bots out there which struggle with open evals sandboxing. 
Plus, there is no reason to leave it public, when possible otherwise.

**Comment by iCrawl** [comment]
This won't happen before a complete rewrite of the library, so I'm going to close this as we move forward and decide how we will implement this.
