### ISSUE TITLE
TextChannel#createWebhook() is not a function

### ISSUE THREAD

**Issue by realCartar** [discordjs/discord.js#3856]
Hello, I stumbled across of a bit of annoying 'bug' with discord.js as seen; the issue is `TextChannel#createWebhook() is not a function`, although according to [discord.js's docs](https://discord.js.org/#/docs/main/stable/class/TextChannel?scrollTo=createWebhook) it obviously is.. It does however execute the function normally (creating the necessary webhooks) although, it seems to be spamming my console with that TypeError.

All I'm doing is looping through all channels in a guild and creating a webhook underneath them like so:

```js
guild.channels.forEach(async x => {
    const fetchWebhooks = await x.guild.fetchWebhooks();
    const botWebhooks = fetchWebhooks.filter(wb => wb.owner.id === client.user.id);
    if(botWebhooks.size > 0) return;
    x.createWebhook('e', 'https://cdn.ethan-san.com/damn');
});
```
From what I can tell there is really nothing I can do to stop the TypeError from occuring,, as I don't really understand how d.js is laid out in the fact- I'm not sure where to fix the error within it's code.

**Comment by RDambrosio016** [comment]
**If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions.
You won't receive any basic help here.**

Please dont use the issue tracker for this, this is due to the fact that not all channels in a guild are in fact text channels, some are categories and voice channels, cant make webhooks for those

**Comment by realCartar** [comment]
@RDambrosio016 

Ah, thank you.. I'll keep that one in mind as well.
