### ISSUE TITLE
Reaction collector break when i set a long expiration time

### ISSUE THREAD

**Issue by wingofbluesky** [discordjs/discord.js#3927]
I create a reaction collector that expired after a day . But a day passed and nothing happened . Everything work find when i set the expiration time shorter like 1 minute or 1 hour .
Here my code:

```js

const collector = messageReaction.createReactionCollector(filter, { time: 86400000 });

collector.on('end', collected => {
          messageReaction.delete()
});
```

- discord.js version: 12.0.1
- Node.js version: 12.16.1
- Operating system: Window 10

**Comment by CrynesSs** [comment]
If your bot reconnects every few hours then the collector gets dumped and all events with it too. If you want a consistent collector, that persists you need to define one message object that you want to listen to in a .json file and call this everytime you start the bot. Then it should reliably collect em. There is just no point in having a 24h collector for reactions because in most cases you want to work with the right away. If it is for polls just save the collected data every 2-5min in a DB and reset the collector to minimize loss.
