### ISSUE TITLE
lib sometimes passes invalid Message object

### ISSUE THREAD

**Issue by adrifcastr** [discordjs/discord.js#3929]
**Please describe the problem you are having in as much detail as possible:**
Functions which use `message` as parameter and then access the `.delete()` method sometimes throw an error because the passed message object is not a valid message object, even though it should be.
![Screenshot_20200311-125140_Discord](https://user-images.githubusercontent.com/22133246/76414718-2aa72f80-6398-11ea-9a15-abdf882224ed.jpg)

**Include a reproducible code sample here, if possible:**

```js
function Del(message) {
    message.delete();
}
```

**Further details:**

- discord.js version: 12.0.2
- Node.js version: 12.16.1
- Operating system: Windows 10/Ubuntu 19.04
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
The cause for this error is a misconception on your end, and the reproducible code sample unfortunately not reproducible at all.

This is not caused by an invalid Message object, as you assume, but an invalid __options__ object, which is the first (optional) parameter of the Message#delete call. The optional nature of this parameter is further why that'll never be reproducible with the provided sample.

The error instead suggests that you updated from v11 and your code base still uses `<Message>.delete(time)`, whereas v12 requires you to pass in an options object 

```diff
- message.delete(5000);
+ message.delete({ timeout: 5000 });
```

Update guide: <https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=delete>
Docs: <https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=delete>

---

**Regarding breaking changes in version 12 and updating:**
- Major versions are prone to breaking changes as per [semantic versioning](https://semver.org/#spec-item-8)
- We have an extensive guide on updating from version 11 to version 12 at [discordjs.guide](https://discordjs.guide/additional-info/changes-in-v12.html?v=12)
- Should you wish to restore your bots functionality immediately without updating your code base please un-and re-install the library in the previous non-breaking version, 11.6.2
```
$ npm remove discord.js
$ npm install discord.js@11.6.2
$ npm list discord.js
```
The last command should print `-- discord.js@11.6.2` if your installation was successful

---

If you still have questions about discord.js installation or usage please visit the Discord server at <https://discord.gg/bRCvFy9>. This issue tracker is just for bug reports and enhancement suggestions.

**Comment by adrifcastr** [comment]
Ah I was on v12 ever since v12 was a thing but I just recently saw saw that there is a timeout option so your explanation is absolutely correct, I have passed an invalid argument, sorry for the trouble, closed.
