### ISSUE TITLE
User typing methods not working

### ISSUE THREAD

**Issue by codetheweb** [discordjs/discord.js#3938]
**Please describe the problem you are having in as much detail as possible:**

I'm trying to use the method `User.typingDurationIn()`, but it always returns `-1` no matter what.  It appears a Map is inited in the [TextChannel constructor](https://github.com/discordjs/discord.js/blob/76634db9bec10f52521d77fac970406fa8b3f36a/src/structures/TextChannel.js#L27) but is never updated.  Doing a quick search for the [`_typing` attribute](https://github.com/discordjs/discord.js/search?q=_typing&unscoped_q=_typing) yields similar results.

**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```

**Further details:**

- discord.js version: 12.0.2
- Node.js version: 12.14.1
- Operating system: macOS
- Priority this issue should have – please be realistic and elaborate if possible: low

- [ ] I have also tested the issue on latest master, commit hash:

**Note**: I tried first asking this question on the Discord server, but got banned soon after asking it.  If this was accidental, my Discord username is also `codetheweb`.

**Comment by LxveFades** [comment]
This is most likely occuring because of discord.js not writing any data to the `Channel#_typing` Map once the `Typing Start` indicator has been sent to the gateway. Discord does not provide the data of when the user stops typing, however it sends a `Typing Indicator` every 10 seconds when a user does indeed start typing (if I recall correctly), which can be used to provide an _estimated_ time of how long the user was typing for. Handling this kind of data was present in v11, but was removed in v12, however the methods were overlooked in v12, and were not removed along with it.
***
Was able to reproduce this bug through the `Client#typingStart` event by using `User#typingDurationIn()`, `User#typingIn()`, and `User#typingSinceIn()`. All of the above return falsy values in all cases.
```js
// Sample code
client.on("typingStart", (channel, user) => { 
   user.typingDurationIn(channel)  // -> -1
   user.typingIn(channel)         // -> false
   user.typingSinceIn(channel)   // -> null
})
```
***
The way to go about this is the same way that v11 did it, but with an increased timeout time, since the API now sends packets every 10 seconds, instead of 5s.
```js
module.exports = (client, { d: data }) => {
  const channel = client.channels.cache.get(data.channel_id);
  const user = client.users.cache.get(data.user_id);
  const timestamp = new Date(data.timestamp * 1000);

  if (channel && user) {

    if (channel.type === 'voice') {

      client.emit(Events.WARN, `Discord sent a typing packet to a voice channel ${channel.id}`)
      return;
    }

    if (channel._typing.has(user.id)) {

      const typing = channel._typing.get(user.id);

      typing.lastTimestamp = timestamp;
      typing.resetTimeout(tooLate(channel, user));

    } else {

      channel._typing.set(user.id, new TypingData(client, timestamp, timestamp, tooLate(channel, user)))
      client.emit(Events.TYPING_START);
    }
  }  
};

class TypingData {

  constructor(
    client,
    since,
    lastTimestamp,
    _timeout
  ) {

    this.client = client;

    this.since = since;

    this.lastTimestamp = lastTimestamp;

    this._timeout = _timeout;
  }

  resetTimeout(_timeout) {

    this.client.clearTimeout(this._timeout);
    this._timeout = _timeout;
  }

  get elapsedTime() {

    return (Date.now() - this.since) - 3000;
  }
}

function tooLate(channel, user) {

  return channel.client.setTimeout(() => {

    channel.client.emit(Events.TYPING_STOP, channel, user, channel._typing.get(user.id));
    channel._typing.delete(user.id);
  }, 10000);
}
```

A PR has been submitted, and is waiting approval.

**Comment by codetheweb** [comment]
👍 thanks for looking into this.
