### ISSUE TITLE
Missing TypeScript definitions for `ws`

### ISSUE THREAD

**Issue by chaucerbao** [discordjs/discord.js#4011]
Compiling from TypeScript throws this error:

```
node_modules/discord.js/typings/index.d.ts:18:30 - error TS7016: Could not find a declaration file for module 'ws'. '/.../node_modules/ws/index.js' implicitly has an 'any' type.
  Try `npm install @types/ws` if it exists or add a new declaration (.d.ts) file containing `declare module 'ws';`
```

Seems like the type definitions for `ws` need to be included with the distribution.

**Comment by ItsPapaia** [comment]
Or... install `@types/ws` as a dev dependency

**Comment by iCrawl** [comment]
Dependencies you need to develop your bot should be installed on your own.

**Comment by chaucerbao** [comment]
I can get rid of the error message by installing `@types/ws` myself, like @ItsPapaia suggested, but I'm not using the `ws` package at all. I'd only be installing it because the compiler is complaining; it's not a dependency that I, myself, am using.

The error points to it being a package that Discord.js is using.

`node_modules/discord.js/typings/index.d.ts:18:30`

Am I reading that wrong?

@iCrawl

**Comment by iCrawl** [comment]
Yes, if you are using Typescript its your responsibility to install the needed dependencies.

A library should never depend on any kind of typings and directly "ship" or install them.

**Comment by ItsPapaia** [comment]
Just skip lib check (`skipLibCheck` in tsconfig)

**Comment by chaucerbao** [comment]
I understand the need to install type definitions for libraries a project is using directly, but if a project is also responsible for the definitions used by all sub-packages, that seems like it could be unwieldy.

Since Discord.js is using (and more importantly, exporting) WebSocket definitions, would it be appropriate to include those same definitions?

https://stackoverflow.com/a/46011417

**Comment by chaucerbao** [comment]
I can work around the issue, @ItsPapaia, so this is not a blocker by any means. But I would prefer to have a complete package, if sensible.

**Comment by ItsPapaia** [comment]
It is private, not a parameter, and should not be touched by the user anyway.

**Comment by iCrawl** [comment]
This was, again, already discussed previously and decided against.

**Comment by fspoettel** [comment]
> This is a pretty established standard in the Typescript community.

May I ask where this best practice is described or for some examples of packages that do this? Anecdotally, I have not encountered a package that works like this besides `discord.js` but numerous packages that _do_ bundle `@types` packages for direct dependencies. I'm now a bit confused whether this is selection bias on my side.

I found a chapter discussing this topic in the TypeScript handbook and fwiw [it seems to recommend](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package) the opposite of this practice as well:

> All dependencies are managed by npm. Make sure all the declaration packages you depend on are marked appropriately in the "dependencies" section in your package.json.
[...]
> If your type definitions depend on another package:
   - Don’t combine it with yours, keep each in their own file.
   - Don’t copy the declarations in your package either.
   - **Do depend on the npm type declaration package if it doesn’t package its declaration files.**

**Comment by iCrawl** [comment]
This page didn't exist back then, so obviously there were no "official" guidelines in this direction.

At the end of the day this decision is taken by many package developers to not ship useless dependencies into JavaScript land for non-TS users.

Take `@types/node` as an example, while you do need it yourself since you work with node, we do too. Should we depend on it too?

Then there's people who are super meticulous about bundle size and all that (yes, even in node) and complain once we have deps that only affect development (since that's what types are at the end of the day) listed as our normal dependencies, which makes it harder for them to prune or get rid of when installing only prod deps.

So far there have only been a handful of people out of everyone using TypeScript with discord.js having a stronger and different opinion on this and that is totally fine too, but I don't think it will change much on how we operate around this issue.

**Comment by Jameskmonger** [comment]
It looks like `ws` is only in the Discord typings file to put a single property on an interface which is used in a private method.

This could be fixed by reducing the published typings file to match the public interface, besides that it's unusual for a  package to ship with typings that require other typings to be installed lest your build breaks. Maybe a note in the readme to explain this would be good rather than the implicit dependency.

If the concern is bundle size, I'm unsure why anyone would be shipping `.d.ts` files with their finished product.
