### ISSUE TITLE
role.setHoist() sometimes fails

### ISSUE THREAD

**Issue by Mloren** [discordjs/discord.js#4063]
Calling setHoist() on several different roles in a row can sometime fail.
No error occurs, the role just doesn't get hoisted, or in some cases, appears to be hoisted for a fraction of a second and then returns to no longer being hoisted.

More info and code to reproduce here:
https://hastebin.com/udijipejaf.coffeescript

**Comment by SketchyLxve** [comment]
I believe that you are getting ratelimited, since you said, and I quote,
> Sometimes this bug happens immediately, sometimes it takes 20 or so attempts.
You can use the `Client#rateLimit` event in order to check whether or not you're being ratelimited.
<https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-rateLimit>

**Comment by SpaceEEC** [comment]
I think this is a race condition caused by discord.js always sending all properties instead of just what is being updated:
https://github.com/discordjs/discord.js/blob/828640ca263db2c95ed21e7353a2746fe6ac9fb8/src/structures/Role.js#L198-L207

The cache is only updated by gateway events to avoid inconsistent state and multiple `<thing>Update` events.

To give you the already updated object we return a patched copy:
https://github.com/discordjs/discord.js/blob/828640ca263db2c95ed21e7353a2746fe6ac9fb8/src/structures/Role.js#L208-L212

---

That way there are two ways to fix this issue here on your end:

1. (Better)
Patch all properties you want at once.
`role.edit({ hoist: false, color: 0 })` or `role.edit({ hoist: true, color: 0x22dd66 })`

2. (Worse)
Use the returned patched copy to update the second property:
`role.setHoist(false).then(patchedRole => patchedRole.setColor(0))`
or
`role.setHoist(true).then(patchedRole => patchedRole.setColor(0x22dd66))`

---

This is also possibly to fix on our end by only patching the properties actually being updated.
Changing this consistently all over our code base is probably not a too simple thing to do however.

**Comment by iCrawl** [comment]
This issue has been stale for a while, if this problem still exists or you can still easily replicate it on `v13` (current master or `discord.js@dev` on NPM), please reopen it as a new issue.
