### ISSUE TITLE
lastMessage property exists in TextChannel's docs but not its structure file

### ISSUE THREAD

**Issue by SyntleLmao** [discordjs/discord.js#4093]
**Please describe the problem you are having in as much detail as possible:**
the [`lastMessage`](https://discord.js.org/#/docs/main/stable/class/TextChannel?scrollTo=lastMessage) property exists on TextChannel's documentation but not in its structure file
**Include a reproducible code sample here, if possible:**

```js
const channel = client.guilds.cache.get('GUILD_ID').channels.cache.get('CHANNEL_ID');
console.log(channel.lastMessage) // Output: null
```

**Further details:**

- discord.js version: 12.1.1
- Node.js version: 12.16.1
- Operating system: Debian 9
- Priority this issue should have – please be realistic and elaborate if possible: High

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Jyguy** [comment]
`TextBasedChannel#lastMessage` depends on the cache of messages; you won't be able to get the value if the last message is not cached (hence it is nullable). Anyhow:

The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
