### ISSUE TITLE
add user .canDirectMessage or user.canDM

### ISSUE THREAD

**Issue by SunGame7** [discordjs/discord.js#4122]
I created a bot which can DM users, I am using the latest release of node and discord.js but basically there is a Deprecation Warning when I DM users who the bot can't (due to user privacy settings). Basically I want there to be a way to check if the bot can send messages to a user, displayed as a property of the user. Now, I don't really have code and haven't really experimented with this using the Discord API but I hope there is some way for this to work.

**Comment by RDambrosio016** [comment]
This is not possible, the API does not provide a way of checking if you can DM a user beforehand, you can only send and catch the rejection

**Comment by Androz2091** [comment]
I see a lot of people who need this, me first. Using a catch is a solution but not as good as using a `if`. I've had errors like this (basic example, it was more complex):
```js
message.member.send("Hello").then((sentMessage) => {
     sentMessage.editt("Coucou");
}).catch((error) => {
    // editt is not a function
    message.channel.send("Your DMs are disabled!");
});
```
And the "Your DMs are disabled!" was sent, because there was an error (sentMessage.editt is not a function) even if the member DMs were turned on. A "if" would have been more comfortable. 😅 

I'm not really aware, does anyone know if there's ever been an issue on the repo of the Discord API Docs? And if so, what was their response?

**Comment by Monbrey** [comment]
I'm confident this has been asked of Discord several times.
As far as I know it's been denied, as making an additional API request to query their DM setting wouldnt actually be beneficial to the API - they'd rather it just failed.
It's worth noting they also don't expose any other notification or privacy settings of GuildMembers to bots.

**Comment by Androz2091** [comment]
Yes, I see. Anyway, thank you for your answer.
