### ISSUE TITLE
displayAvatarURL() and avatarURL() send .gif avatar to .webp

### ISSUE THREAD

**Issue by CtrlVersa** [discordjs/discord.js#4135]
Hello, i have a problem with discord.js, when i do `displayAvatarURL()` or `avatarURL()` my Discord bot returns an .webp image for animated profile picture I've tried to make `displayAvatarURL({format: gif})` or `avatarURL({format: gif})`, the bot send an gif image, but for .png or .jpg image, it does not return avatar. Just blank. Thank's for help

**Comment by Monbrey** [comment]
You can use the `dynamic: true` option to return a gif only when animated.

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
