### ISSUE TITLE
setParent() function does not lock permissions

### ISSUE THREAD

**Issue by MilSci** [discordjs/discord.js#4144]
**Please describe the problem you are having in as much detail as possible:**
When running a setParent() function with lockPermissions() being true, it fails to actually sync the permissions with the parent's permissions

**Include a reproducible code sample here, if possible:**

```js
chan.setParent(config.server, { lockPermissions: true})
//chan is a fetched channel
//config.server is the ID to the category
```

**Further details:**

- discord.js version: v12
- Node.js version: v12
- Operating system: Windows x86-64
- Priority this issue should have – please be realistic and elaborate if possible:
Can be a larger issue since most people might use this feature to create new channels

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Monbrey** [comment]
Cannot replicate this on Discord.js v12.2.0

I'd also like to ask how you're running Discord.js v12 on Node v10, given that Node v12 is the minimum requirement.

**Comment by redbrain** [comment]
I'm having this issue as well.

**Comment by almostSouji** [comment]
The proper fix to this issue will take some time, as it requires us to restructure how #setParent works internally, i will do so in the linked issue above.

For now you can use a work-around approach of setting the overwrite to the overwrites of the to-be parent channel alongside the parent during an #edit instead of #setParent call as shown below:

```js
const parent = guild.channels.resolve(<parent_id>)
const data = {
	parentID: parent.id,
	permissionOverwrites: parent.permissionOverwrites
}
channel.edit(data)
```

<details>
<summary>The current #setParent call works similar to that</summary>

https://github.com/discordjs/discord.js/blob/d827544fbd12e827fb4b6ff99d8894ecd79ede02/src/structures/GuildChannel.js#L388-L397

for now #setParent internally calls #edit and passes a setting that's not available to the API call

</details>

⚠ This is **not** how moving channels between categories is supposed to work, this is a work-around and should be replaced once the linked PR reaches stable.

📝 Please leave this issue open, as again, this is a work-around and it should be closed with the proper implementation of category moving.
