### ISSUE TITLE
Guild.voice.speaking is null when the bot is dispatching audio

### ISSUE THREAD

**Issue by Protected** [discordjs/discord.js#4273]
This is a fairly straightforward issue, I think. Guild.voice is a VoiceState, which contains a 'speaking' getter which should be true when the associated user is known to be speaking. But the bot doesn't seem to acknowledge it is, itself, speaking when the SDK should know that it is, beyond a shadow of a doubt.

Looking into it, VoiceState.speaking checks VoiceConnection._speaking, which isn't updated for the bot proper, even if I explicitly use setSpeaking on the connection. 

**Further details:**

- discord.js version: 12.2
- Node.js version: 14.1
- Operating system: Windows 10
- Priority this issue should have: Medium-High. This seems like a couple of lines to fix (make consistent).

- [X] I have also tested the issue on latest master, commit hash: 2583ad5da7db5ab92dfa357909f9c713db0a2981

**Comment by amishshah** [comment]
Hi there,

We're working on a new implementation of Discord's Voice API that has better playback quality and is more reliable than what we currently support in Discord.js v12 - check it out at https://github.com/discordjs/voice!

The new library solves many of the issues that users are facing, and as part of this, we're dropping built-in support for voice in our next major release. We have a PR (https://github.com/discordjs/discord.js/pull/5402) that adds native support for our new voice library - once this PR is merged, this issue will be closed.

You can still use our new voice library before that PR lands - just take a look at [our music bot example](https://github.com/discordjs/voice/tree/main/examples) to see how to get started upgrading your voice code. By using the boilerplate music player in the example, you can make it even easier to upgrade your code.

Note that the PR above only reduces some of the boilerplate code you'd otherwise have to write - you do not have to wait for the PR to be merged to start using the new voice library.

-----

If you have any questions about this, feel free to:

- [Make an issue](https://github.com/discordjs/voice/issues) if you have found a bug in the new voice library
- Use [GitHub Discussions](https://github.com/discordjs/voice/discussions) or join our [Discord server](https://discord.gg/djs) (we have a new channel, `#djs-new-voice`, specifically for this!) to ask general questions about the library, give feedback on the library, and get support with upgrading to it
