### ISSUE TITLE
client.login() doesn't work on my bot

### ISSUE THREAD

**Issue by bf-dev** [discordjs/discord.js#4291]
**Please describe the problem you are having in as much detail as possible:**
The client.login() did not work on my bot and the bot remained offline.
It works when you create another bot and try again, it works.

**Further details:**

- discord.js version: discord.js@12.2.0
- Node.js version: v14.2.0
- Operating system: Ubuntu 19.10(Linux 5.3.0-51-generic)
- Priority this issue should have – please be realistic and elaborate if possible:

- [x] I have also tested the issue on latest master, commit hash:2583ad5da7db5ab92dfa357909f9c713db0a2981

**Comment by Monbrey** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

Please go to the server and provide the relevant information the issue template would have asked you for - the error and a reproducible code sample.
