### ISSUE TITLE
Switching voice channels rapidly and playing the same audio causes issues

### ISSUE THREAD

**Issue by zimmah** [discordjs/discord.js#4293]
**Please describe the problem you are having in as much detail as possible:**
When you play audio in one channel, then listen for a `dispatcher.on('finish')` event to repeat the process in a different channel, one of two things will happen:

1. The connection will fail, it will actually join the channel, but node will throw an error claiming a connection couldn't be established in 15 seconds.

2. The connection is fine, but the audio won't play.

Workaround: adding a ~150ms delay.

**Include a reproducible code sample here, if possible:**
dependencies needed: "discord.js": "^12.2.0",  "@discordjs/opus": "^0.3.2, "ffmpeg-static": "^4.2.1"

```js
client.on('message', msg => {
    if (msg.content === 'honk') {
        const queue = [VoiceChannel1, VoiceChannel2];
        async function play() {
            if (queue.length > 0) {
                const voiceChannel = queue.shift();
                const connection = await voiceChannel.join();
                const dispatcher = connection.play('./sounds/sound.mp3');
                dispatcher.on('finish', () => {
                    dispatcher.destroy();
                    play();
                });
            }
        }
    play();
}
```

**Further details:**

- discord.js version: ^12.2.0
- Node.js version: 14.2.0
- Operating system: windows 10
- Priority this issue should have – please be realistic and elaborate if possible: low, the workaround is to add a small timeout. It's only slightly annoying.

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by amishshah** [comment]
Hi there,

We're working on a new implementation of Discord's Voice API that has better playback quality and is more reliable than what we currently support in Discord.js v12 - check it out at https://github.com/discordjs/voice!

The new library solves many of the issues that users are facing, and as part of this, we're dropping built-in support for voice in our next major release. We have a PR (https://github.com/discordjs/discord.js/pull/5402) that adds native support for our new voice library - once this PR is merged, this issue will be closed.

You can still use our new voice library before that PR lands - just take a look at [our music bot example](https://github.com/discordjs/voice/tree/main/examples) to see how to get started upgrading your voice code. By using the boilerplate music player in the example, you can make it even easier to upgrade your code.

Note that the PR above only reduces some of the boilerplate code you'd otherwise have to write - you do not have to wait for the PR to be merged to start using the new voice library.

-----

If you have any questions about this, feel free to:

- [Make an issue](https://github.com/discordjs/voice/issues) if you have found a bug in the new voice library
- Use [GitHub Discussions](https://github.com/discordjs/voice/discussions) or join our [Discord server](https://discord.gg/djs) (we have a new channel, `#djs-new-voice`, specifically for this!) to ask general questions about the library, give feedback on the library, and get support with upgrading to it
