### ISSUE TITLE
presence.game.streaming not working shows everytime false

### ISSUE THREAD

**Issue by DK-Web** [discordjs/discord.js#4297]
Hi, 

If I use "presenceUpdate" "presence.game.streaming" gets always false even though I am live in Twitch.

That seems to be a bug?

Many Greetings

**Comment by Monbrey** [comment]
`presence.game` no longer exists on v12.
v11 is deprecated and is no longer supported.

**Comment by DK-Web** [comment]
Hi Monbrey,

thank you for your quick response and help. Sorry for not using the template. I will pay attention to this in the future.

What do I have to use instead of presence.game?

many Greetings

**Comment by Monbrey** [comment]
Discord.js v12 provides support for multiple activities - `presence.activities` is an Array of Activity objects.

<https://discord.js.org/#/docs/main/stable/class/Activity>

The issue tracker is only for bug reports and enhancement suggestions. If you have further questions, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

**Comment by DK-Web** [comment]
Thank you so much! Ok, I rarely write on GitHub, so I'm kind of a noobie sorry.

**Comment by iCrawl** [comment]
Closing as it is a stale issue, reopen or check open issues if this is still an issue.
