### ISSUE TITLE
using message split ignores message options

### ISSUE THREAD

**Issue by Markus-Rost** [discordjs/discord.js#4300]
When sending multiple messages using the message split option other options like `allowedMentions` are only added to the very last message send. This might result in uncontrolled role mentions or other issues.

```js
var options = {
    split: { maxLength: 20 },
    allowedMentions: { parse: [] }
}

msg.channel.send( '<@12345>', options )
// '@mention' no notification

msg.channel.send( '<@12345>\n<@12345>\n<@12345>', options )
// '@mention' notification
// '@mention' notification
// '@mention' no notification
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: v12.13.0
- Operating system: Windows 10
- Priority this issue should have: medium, as it might result in uncontrolled role mentions.

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
should be fixed in the referenced PR.
Feel free to test it out and leave comments/reviews in the PR thread.

- `npm i almostSouji/discord.js#ba90212331e8e5f6c9777b6cf6d3d0869f7d68e9` (one commit only)
- `npm i almostSouji/discord.js#split-mentions` (the branch the PR is from, including respective changes over time, if applicable)

reference: https://docs.npmjs.com/files/package.json#git-urls-as-dependencies
