### ISSUE TITLE
Reaction roles

### ISSUE THREAD

**Issue by Makicka2006** [discordjs/discord.js#4309]
**Problem:**
I would like to create reaction role, but the trigger isn't working. I cust putted a console.log("ok"); before if, but nothing happened, when I reacted. What to do?

**Code:**
```js
client.on("messageReactionAdd", (reaction, user) => {
  console.log("ok");
  if (reaction.message.channel.id !== "713066051969220631" && reaction.emoji.name !== '✅') {
    return;
  }
  client.guilds.get(yourguildid).member(user).addRole('713065834771120172')
}
```

**Further details:**

- discord.js version: v11
- Node.js version: v12
- Operating system: Win7
- Priority this issue should have – please be realistic and elaborate if possible: S.O.S (it is! I need it for 01.06.2020.)

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Monbrey** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by Makicka2006** [comment]
1. It is a bug, because the TRIGGER isn't working and by my friend, it WORKED!
2. At Discord server, it is absolutely impossible to get help. There are three chat lines in a channel at the same time.

**Comment by Monbrey** [comment]
This is absolutely not a bug. Discord.js v11 does not have support for listening to reactions on uncached messages, which is most likely the issue here.

The recommend approach is to use v12, and enable partials.
https://discordjs.guide/popular-topics/partials.html?v=12

In future please do not ignore being directed to the server, which is where you'll get proper support for issues like this.

**Comment by iCrawl** [comment]
Closing as it is a stale issue, reopen or check open issues if this is still an issue.
