### ISSUE TITLE
ClientUser#setAcitvity not setting the activity for the shard id(s) passed into the options

### ISSUE THREAD

**Issue by SemperFortis** [discordjs/discord.js#4342]
ClientUser#setActivity won't set the activity on the specified shard unless it is the shard that last spawned. Ex: 5 shards, this will work for the 5th shard but not any shard before the 5th shard. - Error: TypeError: Cannot read property 'send' of undefined. (discord.js/src/ClientPresence.js:24:43)

```js
client.user.setActivity('test', { shardID: [0,1] })
```

- discord.js version: v12.2.0
- Node.js version: v 13.9.0 & 14.x
- Operating system: Windows & Linux
- Priority: Not really a big priority - only an issue for sharded bots which most users do not currently have

- [x] I have also tested the issue on latest master, commit hash: 1c275af

**Comment by Keke27210** [comment]
You're likely not using internal sharding which is why you're getting that error. This option just makes the code get shards you specified in `<Client>.ws.shards` and send them the presence update payload but if you're not using internal sharding you won't have them all here.
You must call `ClientUser#setPresence` on each individual shard process.

The 5th shard thing is maybe just that you run that code on the 5th shard process which explains why it actually works for that only specific case.

**Comment by SemperFortis** [comment]
Ah, that probably explains it as I am using the sharding manager, but as a workaround I'm just broadcasting to all shards.
