### ISSUE TITLE
PresenceStatusData does not align with PresenceStatus

### ISSUE THREAD

**Issue by DefaultSobriquet** [discordjs/discord.js#4371]
**Please describe the problem you are having in as much detail as possible:**

Setting a client user's status to "invisible" (PresenceStatusData) will set the actual PresenceStatus returned by the client user to "invisible," which does not match the Type definition of PresenceStatus.

While this is likely an intentional feature (since the bot can't be offline and checking itself at the same time), it will cause issues when working with TypeScript, as PresenceStatus should never be "invisible" (but it is in the case of the client user). 

```ts
// Make the bot user appear offline.
client.user.setStatus("invisible");

const status = client.user.presence.status;

console.log(status); // "invisible"

//Typescript Error: This condition will always return 'false' since the types 'PresenceStatus' and '"invisible"' have no overlap.
if(status === "invisible"){
    // Do something interesting.
}

```

**Further details:**

- discord.js version: 12.0.1
- Node.js version: 12.16.1
- Operating system: Windows 10
- Priority this issue should have: Low

- [x] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
should be fixed in the referenced PR, I could not find any irregularities after applying it myself.
Feel free to test it out and leave comments/reviews in the PR thread.

- `npm i almostSouji/discord.js#94ba80176b4631b64d811e7d1da69c2875d3b11e` (one commit only)
- `npm i almostSouji/discord.js#typings-presence` (the branch the PR is from, including respective changes over time, if applicable)

reference: https://docs.npmjs.com/files/package.json#git-urls-as-dependencies
