### ISSUE TITLE
guildMemberUpdate Bug

### ISSUE THREAD

**Issue by Bolimha1234** [discordjs/discord.js#4375]
Hello, so I found this bug while I was trying using guildMemberUpdate event, this bug does that when is a bot adding a role to an user, it just creates oldMember function, and not newMember, but when it's an user adding the role it creates oldMember and newMember.

I tried the following code:
```js
client.on('guildMemberUpdate', (oldMember, newMember) => {
    if(oldMember.roles.cache.has('Role id')) return console.log('Old member has the role.')
    if(newMember.roles.cache.has('Role id')) return console.log('New member has the role.')
// When is a bot adding the role to the user, it just logs oldMember, but when is an user it logs the both.
})

**Comment by almostSouji** [comment]
For future issues lease do not delete the issue template but fill it out instead.

Steps i took to reproduce:
1) created a role, copied its id
2) applied the code sample to my bot on discord.js version 12.2.0 and started it
3) manually added the role to myself -> `New member has the role.`
4) manually removed the role from myself -> `Old member has the role.`
5) added the role to myself via bot -> `New member has the role.`
6) removed the role from myself via bot -> `Old member has the role.`

This is the expected behaviour. The event emits with the GuildMember prior to and after the update. Thus on removal the old (prior to update) member will have the role, while on adding the new (after update) member will have it.
If it is a user or a bot applying the member update (adding/removing a role in this case) does not matter.

I can not reproduce the behaviour your describe with the provided code sample
version: 12.2.0 (stable)

**Comment by Bolimha1234** [comment]
Hello, I did see your comment, in my code i'm using BetterAntiSpam bot, but I tested with other bots, and didn't change nothing... The newMember emitts when it's a user adding it, but when it is a bot, i just don't.

**Comment by almostSouji** [comment]
If you can not reproduce the issue on vanilla discord.js please check back with whoever wrote the code you use. We do not provide support for other peoples code base.

**Comment by Bolimha1234** [comment]
Did you tested adding the role with other bot, and not the bot what you are testing the code?

**Comment by almostSouji** [comment]
I somehow missed your reply, sorry!
Initially I did not, however i tested that (adding the role with another bot as the one running the logging) as well and the outcome did not change.

Overall I can in no way reproduce this behavior. If you still can please provide a minimal, executable, reproducible code sample and the exact steps to set this up and test it in an isolated environment (no other code in the bot, just the code necessary to reproduce the issue, so we can run it with our own token and verify the behavior). Else there isn't much I can do right now.
