### ISSUE TITLE
Can't fetch messages before the bot startup.

### ISSUE THREAD

**Issue by pizdo** [discordjs/discord.js#4645]
**Please describe the problem you are having in as much detail as possible:** 
I have a problem, when i try to react to message that has been created before the bot starts, nothing happens. On the new message all it's fully working. It's show on image: "red color" doesn't works "yellow color" works normally.
![image](https://user-images.githubusercontent.com/51962721/87946975-fd376480-caa2-11ea-8fb8-5062929d5c21.png)

**Include a reproducible code sample here, if possible:**

```js
module.exports = async (client, reaction, user) => {
    let role = reaction.message.guild.roles.cache.find(role => role.name === "👤 | Użytkownik");
    let member = reaction.message.guild.members.resolve(user);
    
    //if (reaction.message.id === "734757792371572836") {
        if (reaction.emoji.id === "734702596979163137") {
            console.log("dipa");
            member.roles.add(role);
        };
    //};
};
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 12.18.2 (inpm 6.14.5)
- Operating system:  Microsoft Windows 10 Pro [10.0.19041 N/A Build 19041]
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [x] I have also tested the issue on latest master, commit hash: latest

**Comment by tipakA** [comment]
Technically, it's not fetching.

In order to receive `messageReactionAdd` event, message which reaction was added to must be cached. Messages sent after the bot was started are cached automatically (with limits), but those before are not. To solve that, you would have to either fetch the message on startup, like in `ready` event, or, if you want to not be limited about what messages you can receive the event for - use partials.

Also note that this is not a place to ask for support, but for bugs reports and enhancement suggestions. You should try to ask in the [Discord server](https://discord.gg/bRCvFy9) next time

**Comment by pizdo** [comment]
to close
