### ISSUE TITLE
All embeds giving an error

### ISSUE THREAD

**Issue by Quark03** [discordjs/discord.js#4671]
Error: 
![bot-issue](https://user-images.githubusercontent.com/58290772/88963278-8585e880-d29f-11ea-90b9-dea9e6938641.png)

Code: 
`await message.channel.send({embed: {description: "Hello",color: color.default}})`

This error happens for every single message that my bot has to send. Some actually have fields with text and some doesn't

**Comment by advaith1** [comment]
I can't reproduce the error with the code you provided, can you provide code that the error can be consistently reproduced with?

Also, you deleted the issue template, which has important info that you need to provide.

**Comment by Quark03** [comment]
Node Version: 14.6.0
Discord.js: 12.2.0
OS: Windows 10 Home 1903

**Comment by alhassanv** [comment]
The error mentions embed fields; the snippet provided only uses a description.

**Comment by Quark03** [comment]
Really, I didn't know that
That's why I am here

**Comment by almostSouji** [comment]
Your stack trace quite clearly shows that you are in fact calling `.addField()` with an empty value in `Index-Bot/logSync.js:265`. Without any more information all I can deduce from the file names and stack trace this could be caused by a listener on message updates where you attempt to log the `message.content`. 

Discord delivers embedded content by editing it in with an update action after the message is received, which does emit the `"messageUpdate"` client event. Now if your bot just sends an embed (no matter if the structure has fields or not, as demonstrated in your opening post) it tries to log the edit with an empty content which is rejected at

https://github.com/discordjs/discord.js/blob/fb1dd6b53aee68722b057f9a460eb618c61dd1c6/src/structures/MessageEmbed.js#L424-L425

If that is what's happening in `Index-Bot/logSync.js:265` one solution is to compare the content of the old and the new message in the event callback (before you try to do anything with it) and returning if the content on both is the same. This will of course prevent any embed updates from showing up, but if this is the reason for the error your approach doesn't seem fit to deal with such updates anyways, so you might as well ignore all and any embed updates.

---

For future reference:
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions.

**Comment by Quark03** [comment]
OK, thanks for the help anyone was able to give me. I'll take a look.
And at this point is useless to go to the discord server cause no one usually helps (just as a note)

**Comment by almostSouji** [comment]
Seeing hundreds of questions being answered in discord on a daily basis I have to disagree with that statement (just as a note)
