### ISSUE TITLE
client.setStatus not working.

### ISSUE THREAD

**Issue by isuckatprogram** [discordjs/discord.js#4734]
**Please describe the problem you are having in as much detail as possible:**
So I have a bot that is in 30+ servers and when i try to set my bot's status to dnd with ``client.user.setStatus('dnd')`` it doesn't work. It doesn't show an error and the ``.then`` function runs but the status of the bot doesn't change the dnd and remains online.

**Include a reproducible code sample here, if possible:**
It wasn't really code, it was an eval command so here's the eval command. 

```
ME: ?eval client.user.setStatus('dnd').catch((err)=>{message.channel.send(err)}).then(()=>{message.channel.send('done')})

BOT: [object Promise]

BOT: done

```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: v12.18.0
- Operating system: win32
- Priority this issue should have – please be realistic and elaborate if possible:
Should probably have the lowest priority since it isn't that important

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by advaith1** [comment]
I tested and it seems that setStatus does not have an immediate effect, but the new status is applied when setActivity is run.

**Comment by almostSouji** [comment]
I can not reproduce this on v12.3.1, status is set immediately if given appropriate time in between changes. My guess is that you're changing presence/status/activity (the latter two subsets of presence) much too quickly and the presence updates we send are ignored by discord because you are on cooldown.

**Comment by ArchieMourad** [comment]
@almostSouji what would the cooldown time be?

**Comment by The-Dylanator** [comment]
I was able to reproduce this. I'm trying to do `client.user.setStatus('dnd)` but it does not set the status. Please help.

**Comment by AustrianDev** [comment]
It might take some seconds/minutes to update. If you wait, does it show up ?

**Comment by almostSouji** [comment]
Another common pitfall that sometimes comes up in our support channels is that people run multiple processes and applications on the same token. Due to how presence update distribution is handled this will conflict and can cancel each other out, or simply not apply any at all. This use case is not supported, each application should run on it's own token, as they share rate limits and other information.
