### ISSUE TITLE
Reaction with a reaction array

### ISSUE THREAD

**Issue by Asgarrrr** [discordjs/discord.js#4752]
Please, add this : 

```js
message.react(['🍎', '🍊', '🍇']);
```

**Comment by monbrey** [comment]
The reaction endpoint does not accept multiple reactions. You can achieve this yourself using a simple loop.

**Comment by Asgarrrr** [comment]
Of course, but when a large number of reactions are added, it can be a bit long, but thanks anyway!

**Comment by almostSouji** [comment]
We can simply just implement what the discord API offers and aim to stay true to what the API allows instead of suggesting there are bulk endpoints where there are none. We'd need to make `n` API calls per method call in the background to fulfill this functionality (where n is the number of emoji provided).

We tend to resolve promises if the requested functionality (in this case reacting with multiple emojis) has fully completed.

Due to API ratelimits the returned promise might take almost arbitrary long to resolve, which doesn't make for a very nice user experience. While we could maybe return a `Promise<MessageReaction>[]` that's really starting to get very clunky if you can just as easily get that result with `emojis.map(e => message.react(e))` - which might even become the internal implementation with additional checks of input types.

At that point it's quite questionable if the perceived ease of use (which can lead to confusion as mentioned above) is worth the trouble and arising support requests "why does my react call need so much time?!".
