### ISSUE TITLE
Idea: Improve user avatar handling

### ISSUE THREAD

**Issue by AntoineJT** [discordjs/discord.js#4767]
When I say "removed", I obviously want to say "deprecated at first, then removed". 

**Is your feature request related to a problem? Please describe.**
I just discovered the two methods `User#avatarURL` and `User#displayAvatarURL`. 
I don't think `displayAvatarURL` is a good name.
Moreover, the distinction between both seems not great to me. If we want to know if the user has its default avatar, I don't think most of the time we need to have directly the avatar url with it. And I think it's confusing. 

**Describe the ideal solution**
I think `avatarURL` should act like `displayAvatarURL`, `displayAvatarURL` should be removed, and a method returning a boolean `hasDefaultAvatar` should be created. I think it would lead to cleaner and better understandable code. 

**Describe alternatives you've considered**
At least, `displayAvatarURL` should be removed, and an optional boolean parameter `includeDefault` can be added to `avatarURL`. 

**Additional context**
I don't have specific additional context.

**Comment by tipakA** [comment]
The `User#displayAvatarURL` method returns link to avatar that is "displayed" for everyone looking on the user. Since you do not set default avatar at all (default avatars are determined [basing on the discriminator](https://discord.com/developers/docs/reference#image-formatting-cdn-endpoints), and somewhat hardcoded), you have *no* avatar - `User#avatar` returns `null`, and so does `User#avatarURL()`.  
This is how Discord handles the data.

It works in similiar way as [`GuildMember#displayName`](https://discord.js.org/#/docs/main/stable/class/GuildMember?scrollTo=displayName). It shows the name that would be displayed for anyone looking on the member - nickname if it exists, otherwise username.


​


While writing this i noticed that you already asked about that in the Discord server, and received answer as to why they are there, and if there is a chance to change that

**Comment by Aakodal** [comment]
We're not the same person! xD

**Comment by AntoineJT** [comment]
He is someone I talk with this about it, so that's why he asked a similar question, but we're not the same person.

**Comment by Tenpi** [comment]
I agree with this idea, but I prefer the alternative solution where you keep `avatarURL()` but add the parameter `includeDefault` if you want the default avatar. This way it isn't a breaking change.

**Comment by Aakodal** [comment]
Don't forget that you made `defaultAvatarURL()` deprecated in your PR, as it implies it'd be removed later (so it'll be a breaking change for v13).
