### ISSUE TITLE
typingStart not working in dm on uncached channels with partials

### ISSUE THREAD

**Issue by Snokilo** [discordjs/discord.js#4771]
# The event detecting if a player start typing in a channel doesn't trigger in a dm channel

## typingStart
> Emitted whenever a user starts typing in a channel.

Nothing in the documentation precise it is not suppose to work

```js
const Discord = require('discord.js');
const config = require('./config');
const client = new Discord.Client();

client.on('ready', () => {
  console.log(`Logged in as ${client.user.tag}!`);
});
 
// Not triggered by bot DM Channel
client.on('typingStart', (channel, user) => {
  console.log(channel)
}); 
 
client.login(config.token);
```

**Further details:**

- discord.js version: 12.3.1
- Node.js version: 12.18.3
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: idk, tell me

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by almostSouji** [comment]
<https://github.com/discordjs/discord.js/blob/56e8ef2d38633154540748acb64f4c1305fcc6d3/src/client/websocket/handlers/TYPING_START.js#L11>

The event can only emit on client if the channel is cached, discord.js otherwise drops the event (does not emit it). In this case this means you did not have a DM during the bots session from either side (you -> bot/ bot- > you), else the channel would be created/cached.

We do offer a feature called [partials](https://discordjs.guide/popular-topics/partials.html) to still get these events, however in this case this seems to not fix it, which is the actual issue here (and why this should be kept open).

---

Modification of OP to reproduce the (now true) bug with partials enabled:

```js
// enable partials:
const client = new Discord.Client({
	partials: ["CHANNEL", "USER"]
});

// [...]

// tracking the websocket event TYPING_START to exclude discord not emitting the event as cause 
client.ws.on("TYPING_START", d => {
	console.log("TYPING_START: ", d)
})
```

I will update as I find out more/potential fixes

**Comment by NotSugden** [comment]
the cause would seem to be the channel (and user) isnt added using `*Manager.add`, and instead retrieved using `*Manager.cache.get` @almostSouji

**Comment by almostSouji** [comment]
I'm currently doubting we can do this at all, seeing that we need much more than the ID to properly handle typing events. 

1. We would need the _typing map to properly handle this, which can not be present on a universal CHANNEL partial - could solve that with a TEXTLIKE_CHANNEL - or whatever partial, however
2. we can receive this event for any type of channel as per API specification, including channels where it does not make a lot - or any sense, which leads us to:
3. the payload just includes `channel_id`, so we can't know what type of channel this emits on, we can also not just assume it is a text based channel due to 2.

**Comment by Snokilo** [comment]
I have created a PR fixing it
https://github.com/discordjs/discord.js/pull/4772#issue-477205672

**Comment by almostSouji** [comment]
Not auto-fetching data is a deliberate choice in the libraries design

**Comment by Snokilo** [comment]
So the only fix is against the libraries design? aha

**Comment by iCrawl** [comment]
This issue has been stale for a while, if this problem still exists or you can still easily replicate it on `v13` (current master or `discord.js@dev` on NPM), please reopen it as a new issue.
