### ISSUE TITLE
Discord Application [BOT] will not start up entirely.

### ISSUE THREAD

**Issue by apollyon600** [discordjs/discord.js#4777]
**VIDEO VERSION**:
All tokens were refreshed, don't even think about it..
https://cdn.discordapp.com/attachments/716850798402863144/750781214855659611/2020-09-02_11-02-37.mp4
If it downloads, don't worry its like 6,000 KB. 2:20 minutes long video explaining what is currently happening.

Reproducing this is near to impossible.

Debugging Logs
```js
[ws] [connection] Connecting to wss://gateway.discord.gg/?v=6&encoding=json
[ws] [connection] Connected to gateway wss://gateway.discord.gg/?v=6&encoding=json
[ws] [connection] Identifying as a new session
[ws] [connection] Setting a heartbeat interval for 41250ms
[ws] [connection] Sending a heartbeat
READY 5381785f5eed3ef8ba26ba459db7bc8e // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[ws] [connection] Heartbeat acknowledged, latency of 674ms
[ws] [connection] Sending a heartbeat
[ws] [connection] Heartbeat acknowledged, latency of 103ms
[ws] [connection] Sending a heartbeat
[ws] [connection] Heartbeat acknowledged, latency of 81ms
[ws] [connection] Sending a heartbeat
[ws] [connection] Heartbeat acknowledged, latency of 75ms
[ws] [connection] Sending a heartbeat
[ws] [connection] Heartbeat acknowledged, latency of 181ms
[ws] [connection] Sending a heartbeat
[ws] [connection] Heartbeat acknowledged, latency of 76ms
[ws] [connection] Sending a heartbeat
[ws] [connection] Heartbeat acknowledged, latency of 97ms
[ws] [connection] Sending a heartbeat
[ws] [connection] Heartbeat acknowledged, latency of 78ms
[ws] [connection] Clearing heartbeat interval
Error: Something took too long to do. // !!!!!!!!!!!!!!!!!!!!!!
    at C:\Users\Apollo\Downloads\ProjectAlpha\node_modules\discord.js\src\client\ClientManager.js:40:57
    at Timeout._onTimeout (C:\Users\Apollo\Downloads\ProjectAlpha\node_modules\discord.js\src\client\Client.js:436:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[ws] [connection] Client closed the WebSocket connection: 1000
[ws] [connection] Clearing heartbeat interval
[ws] [connection] Connection gracefully closed
[ws] [connection] Attempted to destroy WebSocket but no connection exists!```
```

Discord support is the best.......
![image](https://user-images.githubusercontent.com/41652412/92023472-aa8fd000-ed11-11ea-89bf-1a071c63426d.png)

I have discussed this with 15 developers and 1 discord staff all failing to help me or figure out the issue.
Not to mention the discord staff saying:
![image](https://user-images.githubusercontent.com/41652412/92023736-06f2ef80-ed12-11ea-8c56-d0b08b7df827.png)
which clearly brought me to shorten it to 2 minutes.

**Further details:**

- discord.js version: v11.6.4 (Will upgrade to v12)
- Node.js version: v12.18.1
- Operating system: Visual Studio Code (Locally) [This also applies to my VPS (GalaxyGate)]
- Priority this issue should have – Not entirely sure, this is a very rare case, especially that if it is locally. Id say 6/10

- [] I have also tested the issue on latest master, commit hash:
Feel free to ask as much questions below, I will try my best to answer them.

**Comment by apollyon600** [comment]
If you are curious about the code, it is in my github.

https;//github.com/apollyon600/projectalpha

**Comment by almostSouji** [comment]
"Something took too long to do" has historically come up when discord banned glitch ips, if your bot happened to be on a banned cluster you would be banned with that.

That you can reproduce this from your local machine however kind of destroys that theory. If I interpret that video right you are connecting from the same machine, from two different tokens, one works and one doesn't?

The error has surfaced again recently on v11, which you seem to be on as well (please do not delete the issue template but fill it out instead, it's there for a reason) and the 2 people reporting that could no longer reproduce it when switching their codebase to be compatible with version 12 of the library.

Version 11 of the library is no longer maintained meaning new features and even bug fixes will only ever arrive on v12. 

While I can not guarantee you that the error will be gone on v12, being able to reproduce it on the recent version (12.3.1 at the point of writing) is the baseline for further investigation. Since you seem to be able to reproduce this issue on a barebones boilerplate bot doing so for v12 shouldn't be a lot of effort.

*Please note that v11 -> v12 is a major version jump (breaking) and will require you to update your codebase in a lot of places. To ease you over we provide a [v11 -> v12 update guide on our guide](https://discordjs.guide/additional-info/changes-in-v12.html)*

*Sidenote: the portion of the token we log in v12 is derived from your user id and save to show, v11 exposes the full token (as you said correctly in the video, you should of course reset this)*

**Comment by apollyon600** [comment]
I have refreshed the token about a total of 15 times, I am deeply sure its not because of that, I will however upgrade to v12 as rumors says v11 will be completely unsupportable at October 7.

I will also update the template issue to fit and answer everyones needs.

**Comment by almostSouji** [comment]
So the two tokens you demonstrate this on are from different apps? but both are owned by the same discord account. They are used on the same machine (according to the demo), so an IP ban is also out of the question.

Those "rumors" are not rumors at all. Discord has introduced a domain name change (and announced more breaking changes) which will not be applied back to v11.

**Comment by apollyon600** [comment]
> So the two tokens you demonstrate this on are from different apps? but both are owned by the same discord account. They are used on the same machine (according to the demo), so an IP ban is also out of the question.
> 
> Those "rumors" are not rumors at all. Discord has introduced a domain name change (and announced more breaking changes) which will not be applied back to v11.

Alright so I will upgrade to v12.
Yes, those 2 tokens are from different applications.
What also brings up another question is that it will not start up at my VPS which is located in New York, and my PC, located in AZ.

**Comment by apollyon600** [comment]
@almostSouji After switching to v12, the bot finally connects, the only problem and I am skeptical about it is that it still takes a few seconds to connect while my other bots does it instantly.

I also think it broke is because of unavailable guilds, but I am not entirely sure about it.

**Comment by almostSouji** [comment]
Glad to hear that worked! I'm not entirely sure what could be causing the delay unless one application is on significantly more servers / needs more shards which could of course take longer. (Or you maybe have fetchAllMembers enabled in Client options which of course will take more time on more guilds - we do not recommend using this option whenever avoidable for a reason)

Guilds being unavailable should not be an issue

As the error is not reproducible on stable i'm considering this resolved, if you can reproduce it at some point feel free to re-open or reference in a new issue to your liking
