### ISSUE TITLE
client.on blocks the user inputs unless previous request is processed

### ISSUE THREAD

**Issue by cegprakash** [discordjs/discord.js#4814]
**I am trying to handle user inputs in parallel for all the users. But the request is blocked unless previous request is processed**

```js
function startDiscord() {
	client = new Discord.Client();

	client.on('ready', () => {
		console.log(`Logged in as ${client.user.tag}!`);
	});

	client.on('message', async(msg) => {
		const run = async () => {
			handleUserInput(msg);
		};
		run();
	});

	client.login(token);
}
```

**Further details:**

- discord.js version: 12.3.1
- Node.js version: 12.18.3
- Operating system: NA
- Priority this issue should have – Moderate

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by monbrey** [comment]
Which request? What does `handleUserInput` do?

I think this would be much better diagnosed in the [Discord server](https://discord.gg/bRCvFy9) as there's no evidence of any bugs in Discord.js here.

**Comment by almostSouji** [comment]
I'll close this as invalid for now, there's a lot of information missing which is indeed better discussed and investigated on our discord. If this turns out to be an actual issue with the library please post here again and re-open the issue.

Resources for node event loops and blocking:
- https://nodejs.org/en/docs/guides/dont-block-the-event-loop/
- https://nodejs.org/api/events.html
- https://nodejs.org/en/docs/guides/blocking-vs-non-blocking/
