### ISSUE TITLE
message.member returning null, was working previously for years

### ISSUE THREAD

**Issue by robinsongz** [discordjs/discord.js#4941]
After a working bot for more than 2 years, message.member is now returning null. Not sure why, here is my code:

` if(!message.member.roles.has(adminRole.id)) {
    return message.reply("You're not an admin, sorry!");
  }`

getting an error of : " cannot find roles of null "

looked online and solutions were that I need to fetch guild member first?

so would the solution be:

guild.members.fetch()
  .then(code here)
?

**Comment by advaith1** [comment]
how are you getting the messgae? I assume this is not in a messageCreate event?

**Comment by Vaporox** [comment]
As of today, Discord requires you to have the GUILD_MEMBERS` and `GUILD_PRESENCES` intents specified to get guild members with the initial payload. Specify that in the developer portal and please update to v12 to get the intent functionality for your client.

(@advaith1 in v11, `Message#member` is taken from the guild member cache instead of the message payload.)

**Comment by advaith1** [comment]
just update to v12, as v11 isn't supported anymore and it should work in v12.
