### ISSUE TITLE
client.users.cache.size and guild.members.cache.size doesn't give the correct number anymore.

### ISSUE THREAD

**Issue by HLenin** [discordjs/discord.js#4948]
**Please describe the problem you are having in as much detail as possible:**
So recently I have been getting this problem where it doesn't get the correct number of members in my guild, no matter how many trests I did. I have tried with my eval command, checked the console, and changed and restarted everything, yet it doesn't give the expected result.

> ![image](https://user-images.githubusercontent.com/66825478/97436518-192d8a80-195d-11eb-9d3d-16221c6e28ab.png)

**Include a reproducible code sample here, if possible:**

```js
let memCount = message.guild.members.cache.size;
let userCount = message.client.users.cache.size;
message.channel.send(`${memCount} members and ${userCount} all users.`);

//expected result for memCount: 8, actual result: 2
//expected result for userCount: 19, actual result: 2
```

**Further details:**

- discord.js version: ^12.3.1
- Node.js version: 14.11.8
- Operating system: Idk, but I use Repl.it
- Priority this issue should have – please be realistic and elaborate if possible: Above medium (This bug can ruin server stats and stuff)

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [/] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
Discord started to turn off restricted intents by default, which caused you to no longer get all initial members as before.
In order to restore the initial behavior see Discord's [Gateway Update FAQ](https://support-dev.discord.com/hc/en-us/articles/360056426994) as well as our [message regarding that in our FAQ Channel](https://discord.com/channels/222078108977594368/769862166131245066/770741051606302750).

If you do not need presences, you probably want to keep that intent turned off though.
