### ISSUE TITLE
Structures doesn't work.

### ISSUE THREAD

**Issue by Volcie** [discordjs/discord.js#4979]
The constructor of `MyUser` class doesn't get executed on every user that's gonna be cached when the bot logs in.

Code:

```js
Structures.extend("User", User => {
        class MyUser extends User {
                constructor(...args) {
                        super(...args)
                        console.log(this);
                }
        }
        return MyUser
})
```
The only thing I get logged when the bot logs in is the `ClientUser` object, Nothing else.

- discord.js version: 12.4.1
- Node.js version: 14.6.0
- Operating system: Windows 10 and Ubuntu 20.04.

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [x] I have also tested the issue on latest master.

**Comment by almostSouji** [comment]
The ClientUser will also extend the new User class (of course it's still the child class and has precedence in what gets displayed in the log). Structures#extend needs to be executed __before__ the client is instantiated (constructor is called).

If you __only__ ever find the ClientUser is in the user cache this might be due to https://github.com/discordjs/discord.js/issues/4961 - the user caches are build from initial presence payloads which require the  GUILD_PRESENCES privilege.

Note: you very likely do not need this and should instead re-design your functionality to not rely on the user cache (or fill it before execution by fetching members - requires `GUILD_MEMBERS` privilege.

Note2: You do not need to specify intents in the constructor in v12, not providing any means discord will send all events it can based on your privileges (granted through verification or flipping switches as shown in the linked pinned issue)

If you require more assistance with adapting your code, please visit our discord server (https://discord.gg/bRCvFy9)! I can't find any reproducible bug with Structures here.

**Comment by Volcie** [comment]
I've asked this around 3 times and they still don't respond to me.

**Comment by Darkkkiler** [comment]
My question is how did you get my email

**Comment by NotSugden** [comment]
@Darkkkiler its an automated email from github because you're subscribed to this thread, it literally says this in the email
