### ISSUE TITLE
awaitReactions not work on ready event

### ISSUE THREAD

**Issue by samuelds** [discordjs/discord.js#4980]
**Please describe the problem you are having in as much detail as possible:**

awaitReactions not work on ready event, the same code works with message event. Not error print on console.

**Include a reproducible code sample here, if possible:**

```js
const config  = require('./configs/global.json');
const client  = new Discord.Client();
client.on('ready', async function() {
        const server        = await client.guilds.fetch("guildsID");
        const channel       = await server.channels.resolve("channelID");

        let message = await channel.send("test");
        await message.react('✅');
        
        message.awaitReactions(function(reaction, user) {
            console.log("ok");
            return true;
        }).catch(function(collected) {
            message.channel.send('Error with reaction detection');
        });
});
client.login("TOKEN");
```

```js
const config  = require('./configs/global.json');
const client  = new Discord.Client();
client.on('message', async function(message) {
       
       if(!message.content == "go") return;

        const server        = await client.guilds.fetch("guildsID");
        const channel       = await server.channels.resolve("channelID");

        let message = await channel.send("test");
        await message.react('✅');
        
        message.awaitReactions(function(reaction, user) {
            console.log("ok");
            return true;
        }).catch(function(collected) {
            message.channel.send('Error with reaction detection');
        });
});
client.login("TOKEN");
```

**Further details:**

- discord.js version: ^12.4.1
- Node.js version: v12.19.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
This probably is due to the user that is adding a reaction not being cached.

After you sent a message to trigger collector your user object was cached and thus the reaction was collected.

You can enable the `USER` and, due to a bug, `GUILD_MEMBER` partial types in order have the message reaction add event work reliably. (Note that you might have partial users and guild members then)

You can find more info about partials here:
- https://discord.js.org/#/docs/main/stable/topics/partials
- https://discordjs.guide/popular-topics/partials.html#partial-structures

---

On another note with #4986 you would no longer need both partial types for message reaction adds within guilds(!).
For message reaction removes you would still need `USER` for it to work reliably.

**Comment by leo-2323** [comment]
> @leo-2323 Your issue sounds much more like [#4980 (comment)](https://github.com/discordjs/discord.js/issues/4980#issuecomment-723519865) - which was not yet the case when this issue was opened.

@almostSouji you are correct. Is this a bug? Or should I look for a workaround?

Also, I am new to this so apologies if I am writing under the wrong threads. Please guide me to the correct discussion.
