### ISSUE TITLE
`voiceStateUpdate` gives *two* parameters, one for state before the event, one for after.

### ISSUE THREAD

**Issue by XNexusPrimeX** [discordjs/discord.js#4996]
so how do I get the data after it's done?

_Originally posted by @tipakA in https://github.com/discordjs/discord.js/issues/4988#issuecomment-723492904_

**Comment by almostSouji** [comment]
see https://github.com/discordjs/discord.js/issues/4993#issuecomment-723626863 for an example, otherwise:
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9

This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
