### ISSUE TITLE
Reacting to a message : Nickname = NULL (even it's not)

### ISSUE THREAD

**Issue by FomaFomitch** [discordjs/discord.js#5038]
When a User react to a message, I want to know NICKNAME and DISPLAYNAME of the user with this :

```js
reaction.message.guild.member(user).nickname
console.log(`Nickname:${reaction.message.guild.member(user).nickname}    Displayname:${reaction.message.guild.member(user).displayName}`);
```

Show result "Nickname=null" even If the user change is nick name before reacting.
Works just fine 2month ago, I don't know when it broke.
When I put my bot online, it seems to "save" nickname and displayname on the same variables. And when I change nickname without restarting my bot, it seems that nothin change, old displayname = old nickname. Is it a cache problem ?

**Further details:**

- discord.js version:12
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
### Template-wise

- `12` is the current major, but not an exact verison (`12.X.X` where X is a number), this is quite relevant to know.
- ` ` is not a node version, please include it.
- ` ` is not an operating system (including its version), please include it.
- Please do not just delete the "relevant client options", if you do not have anything configured there, the default `none` is just fine.

### Other-wise

I am unable to reproduce this behavior, since you did not mention your exact version, I assume you are not on 12.5.0.
Older versions wouldn't cache incoming user and member data on reaction adds. The behavior you are describing can occur there.

On 12.5.0, with #4969, these will now be cached and such a behavior should no longer occur.

---
If you are on an older version, update and it should be working now.

If you are already on 12.5.0 or this still happens after you updated, please expand your code sample, the more the better.
Also include relevant bits of whether something is cached or not before the event.

**Comment by FomaFomitch** [comment]
Thanks.
Fixed by enabling two new settings on developper portal :

PRESENCE INTENT

SERVER MEMBERS INTENT
