### ISSUE TITLE
message.guild.members.cache in 12.5

### ISSUE THREAD

**Issue by Clement868** [discordjs/discord.js#5051]
**Description of the problem:**

As of update 12.5, when I use the ```message.guild.members.cache``` command, I only retrieve the members that the bot came into contact with, whereas before I retrieved them all. The last time I tested this command was on November 13th, so I don't know if the change is from version 12.5.0 or 12.5.1. Also, I don't know if this is a bug or a new feature.

**Reproducible code:**

```js
Client.on("message", message => {
    console.log(message.guild.members.cache);
})
```

**Other details:**

- discord.js version: 12.5.1
- Node.js version: 14.15.1
- Operating system: Windows 10
- Priority: medium

**Comment by monbrey** [comment]
This relates to Intents, refer to #4961 for more information.

**Comment by almostSouji** [comment]
> whereas before I retrieved them all.

That's a misconception on your end. You always accessed the cached (as the name suggests) members. However prior to discords change you received member data for all online members as well as all members on small guilds.

This has now been changed (by discord) to require privileged intents to be granted (there is no need to specify them in 12.x)

read more in https://github.com/discordjs/discord.js/issues/4961

> The last time I tested this command was on November 13th

This is the case since [Oct. 27th](https://support-dev.discord.com/hc/en-us/articles/360056426994), so that too is quite doubtful.
