### ISSUE TITLE
Is there any way to add more lines to a bot?

### ISSUE THREAD

**Issue by MotoSniper** [discordjs/discord.js#5085]
I've seen another feature request about this but I didn't understand the replies. So i've been using this:
message.channel.send('message')
message.channel.send('message')
message.channel.send('message')
message.channel.send('message')
message.channel.send('message')
message.channel.send('message')
but they are in random orders and the last one has like a 20 second delay to it.
So is there anyway I can do something like
message.channel.send('message') ('message in line 2') ('message in line 3')

**Comment by advaith1** [comment]
for help ask in the server: https://discord.gg/bRCvFy9

**Comment by amitojsingh366** [comment]
You can use async/await....

**Comment by almostSouji** [comment]
You should really use newline characters `\n` resulting in a linebreak instead of sending lots of messages back to back.

If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
