### ISSUE TITLE
Streaming property not updated correctly on disconnect in voiceStateUpdate

### ISSUE THREAD

**Issue by ghostyboi2793** [discordjs/discord.js#5092]
So my bot locks a certain channel whenever there is no longer anyone streaming. However, if someone is streaming, then disconnects with out manually shutting the stream, voiceStateUpdate won't properly update the streaming property. 

```js
bot.on('voiceStateUpdate',async(oldState,NewState)=>{
    if(NewState.streaming&&!oldState.streaming){
        sChannel=NewState.guild.channels.cache.find(c=>c.name==='stream-chat')
        sChannel.updateOverwrite(sChannel.guild.roles.cache.find(r=>r.name==='Employee'),{
            SEND_MESSAGES:true
        }).then(sChannel=>{
            console.log(`Perms Updated`);
        })
        const sEmbed=new Discord.MessageEmbed()
        .setTitle('Stream start!')
        .setColor('GREEN')
        .setAuthor(`${NewState.member.user.tag}`,NewState.member.user.avatarURL())
        .setTimestamp(Date())
        NewState.member.roles.add(NewState.guild.roles.cache.find(r=>r.name==='DJ'))
        sChannel.send(sEmbed)
    }
    if(!NewState.streaming&&oldState.streaming){
        const sEmbed=new Discord.MessageEmbed()
        .setTitle('Stream over!')
        .setColor('RED')
        .setAuthor(`${oldState.member.user.tag}`,NewState.member.user.avatarURL())
        .setTimestamp(Date())
        NewState.member.roles.remove(NewState.guild.roles.cache.find(r=>r.name==='DJ'))
        sChannel=NewState.guild.channels.cache.find(c=>c.name==='stream-chat')
        sChannel.updateOverwrite(sChannel.guild.roles.cache.find(r=>r.name==='Employee'), {
            SEND_MESSAGES: false
        })
        NewState.guild.members.fetch().then(member => {
            member.forEach(member=>{
                if(member.voice.streaming&&member.id!=NewState.member.id){
                    sChannel.updateOverwrite(member.guild.roles.cache.find(r=>r.name==='Employee'), {
                        SEND_MESSAGES: true
                    })
                    .then(sChannel => console.log(`Perms updated.`))}
                })
            })
        
        sChannel.send(sEmbed)
    }
})
```

**Further details:**

- discord.js version: 12.4.1
- Node.js version: 15.0.1
- Operating system: Windows 10, 64-bit
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**
- partials: Don't know enough about these.
- gateway intents: Don't know enough about these, but I do know that I have all of them enabled.
- other: Don't know enough about these.

- [x] I have also tested the issue on latest master, commit hash:

**Comment by amishshah** [comment]
Hi there,

We're working on a new implementation of Discord's Voice API that has better playback quality and is more reliable than what we currently support in Discord.js v12 - check it out at https://github.com/discordjs/voice!

The new library solves many of the issues that users are facing, and as part of this, we're dropping built-in support for voice in our next major release. We have a PR (https://github.com/discordjs/discord.js/pull/5402) that adds native support for our new voice library - once this PR is merged, this issue will be closed.

You can still use our new voice library before that PR lands - just take a look at [our music bot example](https://github.com/discordjs/voice/tree/main/examples) to see how to get started upgrading your voice code. By using the boilerplate music player in the example, you can make it even easier to upgrade your code.

Note that the PR above only reduces some of the boilerplate code you'd otherwise have to write - you do not have to wait for the PR to be merged to start using the new voice library.

-----

If you have any questions about this, feel free to:

- [Make an issue](https://github.com/discordjs/voice/issues) if you have found a bug in the new voice library
- Use [GitHub Discussions](https://github.com/discordjs/voice/discussions) or join our [Discord server](https://discord.gg/djs) (we have a new channel, `#djs-new-voice`, specifically for this!) to ask general questions about the library, give feedback on the library, and get support with upgrading to it
