### ISSUE TITLE
12.5.1 Error: Cannot find module './GuildTemplate'

### ISSUE THREAD

**Issue by Beasleydog** [discordjs/discord.js#5111]
**Please describe the problem you are having in as much detail as possible:**
I just updated djs to version 12.5.1. In the past my code ran perfectly, locally and on Heroku. After updating, my code only works locally. When running on Heroku I get this error. I tried commenting out all code except require("discord.js") and the error still occurs. 
![image](https://user-images.githubusercontent.com/67757390/101990916-284f6a00-3c77-11eb-89ed-05e354171634.png)

**Include a reproducible code sample here, if possible:**

```js
const Discord = require("discord.js");
```

**Further details:**

- discord.js version:12.5.1
- Node.js version:14.15.1
- Operating system:Ubuntu
- Priority this issue should have – please be realistic and elaborate if possible:High, not able to use Discord.js at all

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [X] I have also tested the issue on latest master, commit hash:

**Comment by iShibi** [comment]
If your bot is working fine locally but throwing error on Heroku, that means the problem is with Heroku and not with the library itself. Sadly, you will have to fix that problem on your own.

**Comment by almostSouji** [comment]
sounds like a corrupt install. you somehow managed to get a newer version which requires the newly introduced [GuildTemplate ](https://discord.js.org/#/docs/main/stable/class/GuildTemplate) class, but for the `node_modules/discord.js` folder structure to be missing said folder.

please fully un- and reinstall discord.js

```
npm uninstall discord.js
npm install discord.js
```

*If you are using a online IDE please inform yourself how to execute terminal operations or otherwise fully delete and re-instantiate a required library.*
