### ISSUE TITLE
Guild Members not fetching correctly

### ISSUE THREAD

**Issue by ArtanisTheOne** [discordjs/discord.js#5133]
**Please describe the problem you are having in as much detail as possible:**

When using Discord.js v11 (have not updated as of yet) to fetch all guild members using `fetchAllMembers`. First it produces a GUILD_MEMBERS_TIMEOUT error when no one has spoken and then when users send a message it functions but only for those who have sent a message while the bot is online. So it doesnt fetch it for all members, which is completely against what it is supposed to do.

The error is below (when no one speaks) :
```[WS => Manager] Failed to fetch all members before ready! Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time. Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time. | at /root/dismail/node_modules/discord.js/src/managers/GuildMemberManager.js:317:16 | at Timeout._onTimeout (/root/dismail/node_modules/discord.js/src/client/BaseClient.js:83:7) | at listOnTimeout (internal/timers.js:549:17) | at processTimers (internal/timers.js:492:7)```

**Further details:**

- discord.js version: 11
- Node.js version: 12
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Relevant client options:**

- partials: none
- gateway intents: Guild Members
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by ArtanisTheOne** [comment]
This issue is related to [this issue](https://github.com/discordjs/discord.js/issues/5004)

**Comment by advaith1** [comment]
v11 is not supported and is not intended to work

**Comment by ArtanisTheOne** [comment]
This issue seems to persist in version 12 as well

**Comment by advaith1** [comment]
is the Guild Members intent enabled for your bot?

**Comment by ArtanisTheOne** [comment]
Yes

**Comment by monbrey** [comment]
Please provide a reproducible v12 code sample.

**Comment by almostSouji** [comment]
this is commonly caused by the changes outlined in #4961 , note that you don't need to provide the intents to the constructor (yet, you will with v13) but do have to be eligible for receiving the events (toggle in application settings or discord bot verification)

---

If you have tested this on version 12, please edit your initial post to the exact version you used (node version "12" isn't accurate either, run `npm list discord.js` and `node --version` in your projects root directory).

Please also note that "fetchAllMembers" is not a good option to use for bots on many large servers. There is a reason why we document it as "should be avoided whenever possible"

**Comment by iCrawl** [comment]
Going forward we are going to remove `fetchAllMembers`, so there will be no fix to this. Use different ways to get members if you need them that don't rely on this setting.
