### ISSUE TITLE
Client#userUpdate does not emit despite proper partials enabled

### ISSUE THREAD

**Issue by WOZARDLOZARD** [discordjs/discord.js#5139]
**Please describe the problem you are having in as much detail as possible:**

The userUpdate event for the `Client` does not emit when a username is updated, even though I have enabled all partials in case the user is uncached and all intents except `GUILD_PRESENCES`. 

**Include a reproducible code sample here, if possible:**

```js
const { Client } = require('discord.js');

const client = new Client({
    partials: ["MESSAGE", "CHANNEL", "REACTION", "GUILD_MEMBER", "USER"],
    ws: { intents: ["DIRECT_MESSAGES", "DIRECT_MESSAGE_REACTIONS", "GUILDS", "GUILD_BANS", "GUILD_EMOJIS", 
    "GUILD_INVITES", "GUILD_MEMBERS", "GUILD_MESSAGES", "GUILD_MESSAGE_REACTIONS", 
    "GUILD_VOICE_STATES"] },
});

client.on('userUpdate', (oldUser, newUser) => {
    console.log("Received " + newUser.id);
    // Nothing gets logged when I change my username
});
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 14.15.2
- Operating system: MacOS Big Sur 11.1
- Priority this issue should have – please be realistic and elaborate if possible: Medium. While I managed to work around this by using the `guildMemberUpdate` event instead, some people might not have the `GUILD_MEMBERS` privileged intent enabled and thus requires this event to receive the necessary information. 

**Relevant client options:**

- partials: MESSAGE, CHANNEL, REACTION, GUILD_MEMBER, USER
- gateway intents: All intents except GUILD_PRESENCES
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by ckohen** [comment]
The gateway `USER_UPDATE` event only fires for the client user. As indicated by the [docs](https://discord.js.org/?source=post_page---------------------------#/docs/main/master/class/Client?scrollTo=e-userUpdate), discord.js fires the `userUpdate` event when `GUILD_MEMBER_UPDATE` is received as well, however, this only occurs if the user is already cached.

Furthermore, you are getting the data in `guildMemberUpdate` because you have partials enabled for `GUILD_MEMBER`. If you disable this partial, you will instead receive a `guildMemberAvailable` event. If you change something about your user twice while the bot is running, or once if `ClientOptions#fetchAllMembers` is true (highly not recommended), you should receive the `userUpdate` event normally, so long as the `GUILD_MEMBERS` intent is enabled.

Note: IIRC, the event you are receiving as a workaround will always contain the same data in `oldMember#user` and `newMember#user` on the first event trigger.

If this is not the case, please report back!

**Comment by WOZARDLOZARD** [comment]
By my understanding though, the whole purpose of partials is to receive events for uncached instances. As such, I thought that it would make sense for the `USER` partial to allow `userUpdate` to be emitted when an uncached user's details change, regardless of whether or not other partials are enabled or not. 

Another strange thing that I noticed was that the `guildMemberUpdate` event would be emitted for a (likely uncached) member for seemingly no reason (none of their roles/nickname/user information was changed). This occurred in a large server (400+ members), so I was wondering: is this because of the `guildMemberAvailable` event? If so, how can I check if the member was actually updated or not?

**Comment by ckohen** [comment]
> Another strange thing that I noticed was that the `guildMemberUpdate` event would be emitted for a (likely uncached) member for seemingly no reason...

If they have membership screening enabled, this would be why you are receiving those events, after a member finishes the screening, the `pending` property updates, which isn't implemented quite yet in djs.

I will get back to you (or someone else may comment) on the behavior of `userUpdate` with the `USER` partial enabled. Right now it seems that partial is only used for `typingStart` and the reaction based events. This may just be an oversight.

**Comment by WOZARDLOZARD** [comment]
> If they have membership screening enabled, this would be why you are receiving those events

I began to notice this behavior immediately after I updated the library to v12.5.0, well before membership screening was released into the public. This probably has something to do with uncached/partial old members. I'll look into this further and report back if I find anything useful.

**Comment by iCrawl** [comment]
This issue has been stale for a while, if this problem still exists or you can still easily replicate it on `v13` (current master or `discord.js@dev` on NPM), please reopen it as a new issue.
