### ISSUE TITLE
[FEATURE] It would be nice to be able to get messages by time period.

### ISSUE THREAD

**Issue by GingkathFox** [discordjs/discord.js#5153]
**Is your feature request related to a problem? Please describe.**
I had a small issue where i needed to get messages sent by a user in the last 6 hours, but there was no option in the `channel.messages.fetch()` method. I was told by a friend that you can do that.

**Describe the ideal solution**
It would be nice to be able to, say, `channel.messages.fetch({within: '6hr'})`

**Describe alternatives you've considered**
I attempted to make a hacky workaround, didn't work.

**Additional context**
No additional context.

**Comment by anandre** [comment]
Discord does not provide a fetch option to search around a time, only based on message IDs.

**Comment by almostSouji** [comment]
That's just not a feature the API supports. The message API works like this:

You can fetch 100 messages per call and you can specify "before", "after" or "around" parameters that are mutually exclusive. These are resolved by the timestamp portion of the message ID, which is why passing timestamps also works.

To achieve this, you'd need to fetch multiple packs of 100 messages and filter them based on the message author and the timestamp (relative to now). To provide this functionality the library would need to do multiple calls (possibly even arbitrary many), which is in general not a good idea to do, even less in a library where any timespan could be entered.

**Comment by GingkathFox** [comment]
ah, makes sense. thanks!
