### ISSUE TITLE
Are the optional dependencies bufferutil and utf-8-validate used?

### ISSUE THREAD

**Issue by RudiAusBuddeln** [discordjs/discord.js#5156]
**Please describe the problem you are having in as much detail as possible:**

Are the dependencies [`bufferutil`](https://github.com/discordjs/discord.js/search?q=bufferutil) and [`utf-8-validate`](https://github.com/discordjs/discord.js/search?q=utf-8-validate), introduced in #3393, actually used by this library? There is no mention of them except in the readme. They used to be a part of `peerDependencies` in `package.json`, but that entire field no longer exists.

**Further details:**

- discord.js version: v12
- Node.js version: v12
- Operating system: any
- Priority this issue should have – please be realistic and elaborate if possible:

**Comment by vladfrangu** [comment]
d.js itself doesn't use them, however the ws library we use does.

---

**This issue tracker is only for bug reports and suggesting enhancements.**
If you have a question, please ask it in the **[Discord Server](https://discord.gg/bRCvFy9)** instead of opening an issue – you'll be redirected there anyways.
