### ISSUE TITLE
catch() Event Triggered After Successful Promises

### ISSUE THREAD

**Issue by Max-Rodriguez** [discordjs/discord.js#5160]
**The Issue In Summary:** When using the `.catch()` method after a function is called from discord.js like `msg.delete()`, it triggers my `catch()` event every time, though it is successful every time. This has happened with other functions from discord.js as well, and I believe the promises could be falsely throwing an error back, even when it is successful.

**Reproducible Code Example:** 

```js
    msg.delete().catch( console.log( "Threw An Error!" ); );
```

**Further details:**

- discord.js version: **12.5.1**
- Node.js version: **v14.15.3**
- Operating system: **Windows 10 Home**
- Priority this issue should have: **Low**

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by kyranet** [comment]
[`Promise#catch`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch) expects a callback, you gave it `undefined`.

---

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
