### ISSUE TITLE
DiscordAPIError: Unknown Emoji

### ISSUE THREAD

**Issue by muhimur9049** [discordjs/discord.js#5168]
Sometimes this error happens, and sometimes it doesn't for this one command I have. It basically reacts with a custom emoji to a message. Perhaps does it do this if the bot cannot react with custom emojis for whatever reason in that particular guild?

**Comment by vBread** [comment]
The issue template exists for a reason; please use it

**Comment by kyranet** [comment]
Your bot is probably using an emoji that is either deleted, or from a guild your bot is not in.

---

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by muhimur9049** [comment]
Looks like it doesn't work across shards. Is that intentional?

**Comment by kyranet** [comment]
> The emoji exists in the main server the bot is in. But it looks like it doesn't work across shards. Is that intentional?

You're probably using it wrong or passing the wrong data to discord.js - it doesn't matter the shards your bot has, the error comes from Discord not identifying the emoji you used as a valid one.
