### ISSUE TITLE
<GuildMember>.voice.speaking always null

### ISSUE THREAD

**Issue by Atlas7005** [discordjs/discord.js#5182]
`<GuildMember>.voice.speaking` seems to always return null.
Made an API to get users in a specific channel, and I want to get the speaking thing, but seems to always be null.

```js
app.get("/api/getUsers", (req, res) => {
    var channel = client.guilds.cache.get("795825232161669140").channels.cache.get("795825233122689043");
    var obj = {
        channel: {
	    name: channel.name,
	    id: channel.id,
	    userCount: channel.members.size
	},
	users: channel.members.map(member => { if(!member.user.bot) return { tag: member.user.tag, speaking: member.voice.speaking, id: member.id }  }).filter(el => el != null)
    };
    res.json(obj);
});
```

**Further details:**

- discord.js version: stable (v12.5.1)
- Node.js version: v12.10
- Operating system: Windows 10 1909

**EDIT:**
I wanna add, I just found out the `<VoiceConnection>.on("speaking")` event isn't getting called either, this is according to an event listener `.on` function as well as the debug event.
**EDIT 2:**
The above edit is half-false. It only doesn't work if the bot was already in a voice channel on startup.

**Comment by almostSouji** [comment]
Your bot has to be in a voice channel with members in order to know if they are speaking

**Comment by Atlas7005** [comment]
> Your bot has to be in a voice channel with members in order to know if they are speaking

It is.

**Comment by Atlas7005** [comment]
After a long time trying to debug this, it seems that Discord.js is just fundamentally broken when it comes to the speaking variable as well as the various speaking events.

**Comment by Atlas7005** [comment]
Fixed by playing 1.5 seconds of silence when joining... Apparently, it's not possible to receive audio before you send audio.

**Comment by advaith1** [comment]
I thought d.js automatically played silence for that?

**Comment by adrifcastr** [comment]
> I thought d.js automatically played silence for that?

It does but it is broken regardless, you have to play a silence frame manually aswell to get it to work at all.

**Comment by KalebMills** [comment]
I have been having problems with `voice` in general. Seems to be quite a buggy feature

**Comment by adrifcastr** [comment]
The playing audio part of djs-voice is just fine, from my experience only the voice receive is broken, which makes sense due to it not being officially supported by Discord itself.

**Comment by KalebMills** [comment]
@adrifcastr - Sounds like you may be able to assist with my issue? #5209

**Comment by amishshah** [comment]
Hi there,

We're working on a new implementation of Discord's Voice API that has better playback quality and is more reliable than what we currently support in Discord.js v12 - check it out at https://github.com/discordjs/voice!

The new library solves many of the issues that users are facing, and as part of this, we're dropping built-in support for voice in our next major release. We have a PR (https://github.com/discordjs/discord.js/pull/5402) that adds native support for our new voice library - once this PR is merged, this issue will be closed.

You can still use our new voice library before that PR lands - just take a look at [our music bot example](https://github.com/discordjs/voice/tree/main/examples) to see how to get started upgrading your voice code. By using the boilerplate music player in the example, you can make it even easier to upgrade your code.

Note that the PR above only reduces some of the boilerplate code you'd otherwise have to write - you do not have to wait for the PR to be merged to start using the new voice library.

-----

If you have any questions about this, feel free to:

- [Make an issue](https://github.com/discordjs/voice/issues) if you have found a bug in the new voice library
- Use [GitHub Discussions](https://github.com/discordjs/voice/discussions) or join our [Discord server](https://discord.gg/djs) (we have a new channel, `#djs-new-voice`, specifically for this!) to ask general questions about the library, give feedback on the library, and get support with upgrading to it

-----

**Specific to this issue:**

This event relies on the voice receive feature, which is undocumented by Discord and prone to breaking quite a lot. As it's an undocumented feature, we cannot guarantee support for it. The new voice library will still have support for voice receive, but even then it will not be a stable feature.
