### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by alima566** [discordjs/discord.js#5183]
**Please describe the problem you are having in as much detail as possible:**
I have a channel that updates a leaderboard every 60 seconds. However, every so often, I will get an Internal Server Error, as indicted

```js
Response: Internal Server Error
    at RequestHandler.execute (/root/bot/node_modules/discord.js/src/rest/RequestHandler.js:161:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/root/bot/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
  code: 500,
  method: 'patch',
  path: '/channels/771015880883699732/messages/788933924294361128'
}
Response: Internal Server Error
    at RequestHandler.execute (/root/bot/node_modules/discord.js/src/rest/RequestHandler.js:161:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/root/bot/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async MessageManager._fetchMany (/root/bot/node_modules/discord.js/src/managers/MessageManager.js:140:18)
    at async updateCounter (/root/bot/features/features/gamblingLeaderboard.js:59:26) {
  code: 500,
  method: 'get',
  path: '/channels/771015880883699732/messages'
}
```

**Include a reproducible code sample here, if possible:**

```js
const updateCounter = async (client) => {
  let guildIDs = [];
  const results = await gamblingLeaderboardSchema.find({});
  for (const result of results) {
    const { channelID, _id: guildID } = result;
    guildIDs.push(guildID);
    const guild = client.guilds.cache.get(guildID);
    if (guild) {
      const channel = client.channels.cache.get(channelID);
      if (channel) {
        const messages = await channel.messages.fetch();
        const firstMessage = messages.first();
        if (firstMessage) {
          firstMessage.edit({ embed: getText() });
        } else {
          await channel.send({ embed: getText() });
        }
      }
    }
  }
  counter -= seconds;
  if (counter <= 0) {
    counter = startingCounter;
    for (const guildID of guildIDs) {
      await fetchData(guildID);
    }
  }
  setTimeout(() => {
    updateCounter(client);
  }, 1000 * seconds);
};
```

**Further details:**

- discord.js version: 12.5.0
- Node.js version: 12
- Operating system: centOS 8.2
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by KinectTheUnknown** [comment]
"Internal Server Error" is referring to Discord API server, meaning something happened on their end. The only way Discord.JS was able to produce such error was by passing a string into `GuildMember#ban`. In your case, you are able to make the request, but sometimes it errors. So, we can eliminate the possibility of a malformed request. Even if it was an issue on our end, we’d be blindly shooting darts as we don’t know what we’re looking for or why it’s erroring in the first place.
It’s also worth noting that the code you provided is considered api spam since ur always fetching the message and updating the embed every minute. I don’t recommend updating live data in messages for such reason.
