### ISSUE TITLE
User Interface interoperability

### ISSUE THREAD

**Issue by hdev-sec** [discordjs/discord.js#5188]
Good Morning to all,
  hope you are doing good on those hard times.
Due to the fact that I am a lazy developer and I'm enjoying a lot you product, I would like to point you out that I hate Discord sometimes. 
TLDR; 
 Someone puts link to invitation to a server on a website, I open it into the browser (I have package installed), your /invite/wowWhatAGreatDeveloper doesn't point out a `xdg-open` to open the server in app. BUT I have QRCode for my phone (Well great idea, but thank you. I do not use chats on mobile, unless you want phone ringing all day) and a login form. AMAZING: but what if I use a VPN plugin on my browser? You detect inner location and I should log into my mail for allowing myself into? I repeat: this is not a browser issue, this is a Discord *missing feature*. Apps on host are not tunneled through VPN so everything now it's up to you.

If you think this is not an issue, i could switch back to Slack(even more madness on auth) or straight to IRC (dealwithit).
 
Goodbye and Thank you.

**Comment by kyranet** [comment]
The browser part of discord.js is not only (informally) deprecated, but it's also most likely broken due to Discord's changes on CORS which forbid browser's REST from working.

Also QRs and similar are completely unrelated to discord.js, you're meant to open a suggestion in https://support.discord.com.
