### ISSUE TITLE
There should be a notice about Privileged Gateway Intents in docs

### ISSUE THREAD

**Issue by Thymue** [discordjs/discord.js#5191]
**Please describe the problem you are having in as much detail as possible:**
There should be a notice about Privileged Gateway Intents in docs for events(/other things) that need them to be enabled
![image](https://user-images.githubusercontent.com/26690825/104084447-5492e200-5247-11eb-8f79-ff6d75199d2d.png)

**Comment by anandre** [comment]
We generally don't list things like that (see any API method and the required Permissions needed, max messages when fetching) because Discord can change them at any time without warning. This could force an unnecessary update to the library or cause confusion if the library is listing incorrect information.

Further, the programmer using the API (you) should also be making use of the API docs when necessary, such as in this case.

**Comment by almostSouji** [comment]
There are a few notices about intents on the various properties of the bit field wrapper <https://discord.js.org/#/docs/main/stable/class/Intents> and I'd be in favor of keeping it concentrated there. In case discord every adds intents and corresponding events to the list of privileged intents this prevents the need of scouring through the documentation looking for references.
