### ISSUE TITLE
Message sent twice or more

### ISSUE THREAD

**Issue by Ivan7851** [discordjs/discord.js#5211]
Hi, I tried to make a simple welcomer bot, but I ran into an issue, sometimes the bot send a welcome message twice or more times, and I can't figure out why it's happening. Here's my code and a picture of the bug.

Code: https://pastebin.com/Kph0uKxf
Picture: https://imgur.com/a/MgIt6oD

**Comment by almostSouji** [comment]
The issue template is provided for a reason, please fill it out instead of deleting it.

```
<!--
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions.
You won't receive any basic help here.
-->

**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

<code>

**Further details:**

- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

<!--
If this applies to you, please check the respective checkbox: [ ] becomes [x].
You don't have to modify the text to suit your particular situation – if you want to
elaborate, please do so in the description.
While it's not a requirement to test your issue on the master branch, it would make fixing
the problem a lot easier for us, so please do so if possible.
-->

- [ ] I have also tested the issue on latest master, commit hash:

```

Please provide a minimal reproducible code sample so we can attempt to reproduce and verify your issue. This means isolating the erroneous behavior to a fresh bot, or stripping away functionality until you can be sure the code is minimal. Also include a manual with the steps you take interacting with the code in question which results in the behavior you outlined.

Please try to reproduce the issue yourself on a fresh bot. If you can't reproduce it, it's very likely that we can't either and the code sample in question is not enough.

Boilerplate: https://discord.js.org/#/docs/main/stable/examples/ping
Minimal Reproducible sample: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by almostSouji** [comment]
Make sure you don't nest your listeners in one another and only have one process running at a time.
