### ISSUE TITLE
Hti

### ISSUE THREAD

**Issue by ccsdscs** [discordjs/discord.js#5263]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]

**Describe the ideal solution**

**Describe alternatives you've considered**

**Additional context**

**Comment by kyranet** [comment]
If you have a bug report, please fill in the template, don't just post an issue without any information.

---

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
