### ISSUE TITLE
GuildMemberRoleManager loses all but last of add/remove(Array) operations if these are not used synchronously

### ISSUE THREAD

**Issue by Protected** [discordjs/discord.js#5279]
**Please describe the problem you are having in as much detail as possible:**

When attempting to add and remove lists of roles to the same member, the intent of one or more operations can be lost by discord.js . This happens because these methods take the set of all currently known roles for a guild member, operate synchronously on it (either add or remove) and then send the result asynchronously to the API. If multiple operations are scheduled, all will operate on the set of known roles at the time of the beginning of execution, ignoring all other scheduled operations. 

I understand the API itself takes a new list of roles when patching the member, so this makes some sense. But the behavior is unintuitive to users, undocumented, and requires implementing repetitive application-side code to deal with independent role update operations for all applications that contain independent code operating on member roles. I feel like the GuildMemberRoleManager could easily keep an "outbound" set of roles, apply all requested operations to it and then send the final result to the API.

**Include a reproducible code sample here, if possible:**

```js
//member has roles a, b, c

Promise.all([
    member.roles.add([d, e]),
    member.roles.remove([b, c])
]);

//member does not receive [d, e], because the remove operation is called without [d, e] in the set, so they are added and immediately removed (as correctly detailed in the audit log).
```

**Further details:**

- discord.js version: 12.5.1 (but checked source code in master)
- Node.js version: 14.15.4
- Operating system: Windows 10, Debian Buster (tested in both)
- Priority this issue should have – please be realistic and elaborate if possible: Documentation should be updated quickly to make this particularity of the GuildMemberRoleManager clear. If this behavior is to be changed, the priority for the change is medium provided the behavior is clearly documented.

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

Edits: The test I was performing for the single role arguments was wrong and led me to believe this problem also affected those cases. It doesn't. This is a problem with the array argument cases.

**Comment by Wittiest** [comment]
I've verified the issue as discussed above and added some additional code / screenshots to elucidate the issue

### Modify roles with array (possibly unexpected result)

Code Samples:

Parallel
```javascript
// Parallel
const getRole = (guild, roleName) => guild.roles.cache.find(r => r.name === roleName);

Promise.all([
  member.roles.remove([getRole(guild, 'Role B')]),
  member.roles.remove([getRole(guild, 'Role C')]),
]);

//Synchronous

member.roles.remove([getRole(guild, 'Role B')]).then(() => {
  member.roles.remove([getRole(guild, 'Role C')]);
});
```

In both of these examples, because we are using a member object with starts with some set of roles, when we invoke `add` or `remove` with an array, the implementation at [GuildMemberRoleManager.js#L138](https://github.com/discordjs/discord.js/blob/master/src/managers/GuildMemberRoleManager.js#L138) will use `PATCH/guilds/{guild.id}/members/{user.id}` which overwrites the first command.

Both of these have the same result (see audit log screenshot)

Audit log screenshot:

<img width="671" alt="Screen Shot 2021-02-03 at 10 58 55 AM" src="https://user-images.githubusercontent.com/30442914/106795403-e277a800-660e-11eb-8cc7-88b55e09dd1e.png">

### Modify roles without array (expected result)

```javascript
const getRole = (guild, roleName) => guild.roles.cache.find(r => r.name === roleName);

Promise.all([
    member.roles.remove(getRole(guild, 'Role B')),
    member.roles.remove(getRole(guild, 'Role C')),
]);
```

Audit log screenshot:
<img width="670" alt="Screen Shot 2021-02-03 at 11 00 28 AM" src="https://user-images.githubusercontent.com/30442914/106795560-1357dd00-660f-11eb-9d54-ecaac00c9370.png">

### Possible Solutions

1. As @Protected mentioned, if the functionality isn't being changed the documentation could be edited to call out this potential issue and the implementation. The documentation could include the suggestion to just use `.set` when attempting to add/remove roles simultaneously or (less preferred) to do something like this:
```javascript
member.roles.add([role1, role2]).then((updatedMember) => {
    updatedMember.roles.remove([role3]);
  });
```

2. As @Protected mentioned, having some set of "outbound" roles could be used because we don't want to wait for the full request-response cycle of the first asynchronous request to finish. If this was implemented, I think we could benefit from some sort of generic class for this use case if this sort of thing is happening in other places with the API

**Comment by almostSouji** [comment]
This isn't really a bug with the library but has to do with the eventual consistency discord applies when rapid role changes occur. 

The behavior can't just be observed within a single bot but also if you have multiple bots updating roles at the same time or very shortly after another (for example when a member joins, one persists role state, another one adds a "member" role) and should be avoided.

If you want to modify multiple roles in one go including removals and additions please use [`GuildMemberRoleManager#set`](https://discord.js.org/#/docs/main/stable/class/GuildMemberRoleManager?scrollTo=set) instead.

**Comment by Wittiest** [comment]
> This isn't really a bug with the library but has to do with the eventual consistency discord applies when rapid role changes occur.

I don't think this relates to eventual consistency on the server side as much as the API limitations that discord.js is operating within.

Discord doesn't offer bulk endpoints for add/remove of roles but does have them for single role changes (ex: [Add Guild Member Role](https://discord.com/developers/docs/resources/guild#add-guild-member-role)) which is why this SDK is using the single role endpoints when we don't pass in an array.

I agree that there is definitely no solution to the problem of overwriting when using [GuildMemberRoleManager#set](https://discord.js.org/#/docs/main/stable/class/GuildMemberRoleManager?scrollTo=set) when it comes to eventual consistency, but calling out in the documentation that [GuildMemberRoleManager#add](https://discord.js.org/#/docs/main/stable/class/GuildMemberRoleManager?scrollTo=add) and remove are using set in the implementation when using an array would inform users to avoid mistakes

**Comment by almostSouji** [comment]
Well, the "bulk update" endpoint exists in form of patching the guild member. I'm not sure yet where you'd want to stop with that suggestion? Technically #set itself calls [GuildMember#edit under the hood](https://github.com/discordjs/discord.js/blob/stable/src/managers/GuildMemberRoleManager.js#L150), (for just that reason).

Rapid patches being swallowed isn't exclusive to these endpoints either, does that mean it should be noted on absolutely any endpoint that makes a patch call (maybe in a "disguised" form as here, internally, maybe even just under certain conditions)? I'm really unsure if that solves any issues rather than just adding more confusion to the mix.

If any and all peculiarities of the discord API are noted in our documentation at which point does it become a convoluted mess?

**Comment by Wittiest** [comment]
Do you think adding in an optional `atomic` param like [discord.py](https://discordpy.readthedocs.io/en/latest/api.html?highlight=role#discord.Member.add_roles) would be a good idea?

With this addition, users could safely use [GuildMemberRoleManager#add](https://discord.js.org/#/docs/main/stable/class/GuildMemberRoleManager?scrollTo=add) with multiple params guaranteed to update the role if they desire, and if they stick with the default the existence of the `atomic` param would implicitly document the existing functionality

**Comment by Protected** [comment]
@almostSouji discord.js is wrapped around the API, obscuring the way it works. It exposes this functionality in such a way that makes it unclear that this behavior exists in the first place. From the text of your arguments it's clear that understanding the issue requires understanding the API behind discord.js; it's easy for you, who are comfortable with the API, to have that position, but the vast majority of users... won't. So when they encounter this issue they'll have to test and/or examine the discord.js code until they understand what's wrong--a waste of everyone's time. 

And I honestly don't see why the fact that quick subsequent patches by different bots can be in conflict prevents and improvement that at least solves the problem for code being executed within the same node instance... It doesn't have to be an all or nothing thing. discord.js has a ton of other features that provide quality of life improvements over raw API use.

**Comment by anandre** [comment]
This is not a problem if you properly resolve the promises from each call.  We see this all the time in support on the discord server.  The correct way to handle it would be along the lines of
```ts
    await message.member?.roles.add('570981724444688394');
    const member = await message.member?.roles.remove('570981648720592908');
    console.log(member?.roles.cache.has('570981648720592908')); // false
    console.log(member?.roles.cache.has('570981724444688394')); // true```

which produces the expected results, or use the set method as Souji suggested earlier.

**Comment by almostSouji** [comment]
@Protected You seem to be misjudging my intent.  I'm not trying to prevent any improvements, I'm trying to convey that this (being labeled as bug) is nothing we can fix on the library level (if it can be considered a bug at all, rather than not immediately obvious API behavior). I'm also unsure in which capacity (if at all) this should be documented.

For the same reason, I'd appreciate suggestions on what it exactly is you'd want to be improved and how that could be achieved rather than paragraphs about why I'm trying to dismiss something I'm not even actually dismissing.

**Comment by almostSouji** [comment]
> Do you think adding in an optional `atomic` param like [discord.py](https://discordpy.readthedocs.io/en/latest/api.html?highlight=role#discord.Member.add_roles) would be a good idea?
> 
> With this addition, users could safely use [GuildMemberRoleManager#add](https://discord.js.org/#/docs/main/stable/class/GuildMemberRoleManager?scrollTo=add) with multiple params guaranteed to update the role if they desire, and if they stick with the default the existence of the `atomic` param would implicitly document the existing functionality

Discord.py using this was indeed news to me. I'm personally unsure yet if I like this approach (making multiple API calls for the user where one might do, having the potential to quickly drain rate limits without the user even realizing they are doing multiple requests here), but could be considered, of course.

**Comment by Wittiest** [comment]
> Discord.py using this was indeed news to me. I'm personally unsure yet if I like this approach (making multiple API calls for the user where one might do, having the potential to quickly drain rate limits without the user even realizing they are doing multiple requests here), but could be considered, of course.

Yeah that's a hard one. I think this sort of thing only makes sense when the default is set to atomic=false so that (hopefully) a user would only opt in after reading and fully comprehending the documentation.

The main benefit here would be that Discord.js would be adding a strongly-consistent bulk add / remove which would be useful for the case you pointed out earlier about multiple bots or the case of a user simultaneously modifying a role. The side benefit would be implicitly documenting the API with that param in a way that could resolve what this initial issue was made for.

Do you think it's worth me opening a Discussion topic about this for input? I'd rather not keep posting on this issue.

**Comment by Protected** [comment]
Feel free to relabel. The new issue pages told me unexpected behavior should be reported as a bug, but maybe it's more of a feature request, really?

**Comment by almostSouji** [comment]
closing in favor of #5293, as this is not really a bug, and conversations about possible approaches are better placed under discussions.
