### ISSUE TITLE
Discord.js is badly created (you can change its fonctionnality pls)

### ISSUE THREAD

**Issue by xevaltans-games** [discordjs/discord.js#5299]
Hello dear Developpers,
I don't know how you made discord.js.
But it's very messy !
There function which leads to the same funcions and there is missing functions.
Why i can't send message by using client (client.guilds.cache.get(id).channels.cache.get(id).send ==> i can't use that !)
And i would like we can use all functions with it ^
There are missing so much things !!
Please fix that i want to use this easly.

I hope you understanding me. Some people have same things ?

Thanks you for your help!!!

**Comment by iShibi** [comment]
Can you show the code where you got this error?

**Comment by almostSouji** [comment]
If you have issues with using discord.js please use the discord server.

If you think you actually found a bug please make your issue about the bug, instead of vaguely stating that our library is bad and needs to be changed. Thank you.

--- 

If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
