### ISSUE TITLE
meme commands

### ISSUE THREAD

**Issue by YodaForce157** [discordjs/discord.js#5343]
Randomly this code sends either infinite buffering or no images with random-puppy v 1.1.0

```js
const Discord = require('discord.js');
const vars = require('../varibles');
const randomPuppy = require('random-puppy');
module.exports = {
    name: "meme",
    description: "Gives you a meme",
    async execute(message, args) { 
        const subReddits = ["dankmemes", "meme", "memes"]
        const subredit = subReddits[Math.floor(Math.random() * subReddits.length)]
  
        const meme = await randomPuppy(subredit);
  
        const memeEmbed = new Discord.MessageEmbed()
        .setColor(vars.colour)
        .setImage(meme)
        .setTitle(`From r/${subredit}`)
        .setURL(`https://reddit.com/r/${subredit}`)
        .setThumbnail(meme);
  
        message.channel.send(memeEmbed);
        message.channel.send(meme);
    }
}
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 7.5.4
- Operating system: windows 10 pro
- Priority - not too important but annoying for meme commands

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none
![image](https://user-images.githubusercontent.com/69751882/108638339-b8373e80-7486-11eb-8bfd-6c264f36e19f.png)

**Comment by tipakA** [comment]
You are aware that you cannot really place a video in an embed, right?

The only reason you are getting those infinitely loading "placeholders", is because you use links to `imgur.com/name.mp4` and not to `i.imgur.com/name.mp4`. If you would use `i.imgur`, you're not gonna get anything at all.

`imgur.com/name` displays entire website, `imgur.com/name.mp4` *redirects* to `i.imgur.com/name.mp4` in the browser, but doesn't really allow to resolve the video directly without the redirect - that's why it looks like it's loading infinitely.

**Comment by almostSouji** [comment]
Outgoing embeds do not support videos.

**Comment by YodaForce157** [comment]
I know but it still happens with png jpeg ect

**Comment by tipakA** [comment]
Then does so for the reson i outlined.
