### ISSUE TITLE
Why guild isnt cached?

### ISSUE THREAD

**Issue by Skiuel** [discordjs/discord.js#5348]
`module.exports = {
    name: "t",
    run: (msg,args) => {
        const Discord = require("discord.js")
        const client = new Discord.Client()
        console.log(client.guilds)
    } 
}`
this code give
`GuildManager {
  cacheType: [class Collection extends Collection],
  cache: Collection(0) [Map] {}
}`
Why

**Comment by zaida04** [comment]
Because you are instantiating a whole new discord client that's not even logged in. You should be accessing your already created client instance from `msg.client`.

The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
