### ISSUE TITLE
fetch user by tag (user#discriminator)

### ISSUE THREAD

**Issue by seiyria** [discordjs/discord.js#5359]
**Is your feature request related to a problem? Please describe.**

Discord.js seems to have removed the ability to search users by tag, without loading every user up front. Previously (my last app was on 12.0.2) I could do this.

**Describe the ideal solution**

`GuildMemberManager#fetch` options would ideally support a `tag` query option (or a `user` and `discriminator` option, whatever makes the most sense).

**Describe alternatives you've considered**

Downgrading to 12.0.2, or asking users to put in their Discord ID (the string of numbers) instead of their tag. The latter is far less user friendly.

I've also considered fetching all server members (which [seems limited to 1000?](https://github.com/discordjs/discord.js/blob/4b555fdf4c3b35fa0ea284f9cd56765ecb608b89/src/managers/GuildMemberManager.js#L303)) any time a request is made, but this seems wasteful and is really not ideal. It would also be happening quite frequently, as these queries are made when the user logs in each time, as well as changes their account options. Being able to fetch for an individual user would make this at least only fetch for their user, instead of reloading all other users.

**Additional context**

My application allows users to externally put in their Discord tag, which Discord.js then syncs up their earned roles any time they log in or change some account statuses that affect those roles. Getting the users ID in any way isn't really applicable as they may not have interacted with the bot before this. 

Previously in Discord.js 12.0.2, I had code like this that would work:

```ts
  public getDiscordUserByTag(tag: string): Discord.GuildMember | undefined {
    return this.discordGuild?.members.cache.find(u => u.user.tag === tag);
  }
```

I recognize this is because previously all users were cached, which made this work (and it would still work if all users were cached).

**Comment by vaporox** [comment]
We cannot add something that Discord doesn't support. There's the `query` option for usernames though.

**Comment by seiyria** [comment]
I've thought of doing it by username only, but those can change and people can impersonate others so that didn't seem to be a good idea. Is there a good way to request something like this for discords official api?

**Comment by vBread** [comment]
> Is there a good way to request something like this for discords official API?

https://discord.gg/discord-api

**Comment by almostSouji** [comment]
> Previously (my last app was on 12.0.2) I could do this.

Nothing about this functionality has changed. The code you provide searches the cache until it finds a member where the tag is as specified. To be found this of course requires the member to be cached in the first place. 

The only thing that has changed is that without granting/enabling the required privileged intent switch you will receive substantially less to no member data, which you can read more about here: https://github.com/discordjs/discord.js/issues

> I've also considered fetching all server members (which seems limited to 1000?) 

No, the referenced code just orchestrates member chunking, fetching the full member list via `<Guild>.members.fetch()` without parameters is still a valid thing to do (provided you have the `GUILD_MEMBERS` intent enabled

The only feasible option is to direct your members to how to find their discord ID. Not only due to the tag being a variable that can change at any time (username change, nitro expiration, nitro discriminator grant) but also due to it being considered end-user data, which you should not save if not necessary for your operation (the ID is a much better choice for this use case).

**Comment by advaith1** [comment]
API feature request: https://github.com/discord/discord-api-docs/issues/1574
