### ISSUE TITLE
GuildMemberManager#fetch Not fetching all members matching a query

### ISSUE THREAD

**Issue by GeorgeH005** [discordjs/discord.js#5366]
**Please describe the problem you are having in as much detail as possible:**
When fetching guild members while providing a query, only the first member matching the query is returned, not the whole list of members matching the query. Manually setting a limit higher than 1 fixes that but shouldn't it be unlimited by default?

**Include a reproducible code sample here, if possible:**

```js
<guild>.members.fetch({ query: username, cache: false });
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 14.15.5
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Not that high admitedly. There are ways to get around this but i believe they are sub-optimal.

**Relevant client options:**

- partials: none
- gateway intents: ['GUILD_MEMBERS', 'GUILDS', 'GUILD_WEBHOOKS', 'GUILD_MESSAGES', 'GUILD_VOICE_STATES', 'GUILD_MESSAGE_REACTIONS', 'GUILD_EMOJIS']
- other: none

**Comment by monbrey** [comment]
Not sure why you closed #5361 where you actually pointing out what causes this

**Comment by GeorgeH005** [comment]
Because it wasn't getting labeled. Then i noticed there was a template for errors so i used it. I will try to remention that piece of code.

**Comment by GeorgeH005** [comment]
https://github.com/discordjs/discord.js/blob/d744e51c1bdb4c7a26c0faeea1f2f45baaf5fd3c/src/managers/GuildMemberManager.js#L134

There is that piece of code.

**Comment by vaporox** [comment]
The line you linked above is unrelated to the problem you're mentioning, it only gets there if `options.user` is present, which is probably not the case when you're fetching with a query.

When requesting a query, it is required that you pass a limit ([Reference](https://discord.com/developers/docs/topics/gateway#request-guild-members-guild-request-members-structure)). The library defaults that limit to 0 because that's needed to fetch all members without a query, however if you do pass a query, that's probably what sets it to only return one. Thus, making sure that all members get fetched in this case cannot be guaranteed because you cannot leave the limit empty, and just passing a very high integer as a workaround is also not really optimal.

**Comment by GeorgeH005** [comment]
Ok Thanks. As it cannot be considered a bug in discord.js i am closing the issue.
