### ISSUE TITLE
guild.members.cache.get returns always 'undefined'

### ISSUE THREAD

**Issue by BlckqFlorian** [discordjs/discord.js#5380]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
let guild = bot.guilds.cache.get("602251489653686300");
															if (guild) {
																let member = guild.members.cache.get(rows[ i ][ "discordId" ]);
```

**Further details:**

- discord.js version: latest
- Node.js version: latest
- Operating system: Debian 10
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by almostSouji** [comment]
Client caches are empty before the client is logged in and ready. Since you specify no intents and assuming "latest" means 12.5.1 (latest stable as of writing this) I'm guessing you are trying to access caches before the bot is fully connected.

For future reference: "latest" is not a valid version and a reproducible code sample should be "plug and play" as in "we can plug in a token, run a bot and see the behavior you outline".
