### ISSUE TITLE
Volume controlled opus streams do not get properly destroyed

### ISSUE THREAD

**Issue by keybraker** [discordjs/discord.js#5429]
When creating a stream with `opus` that is volume controled **volume: true** it does NOT destroy the stream upon `.end()` or `.destroy()` function calls. In contrary, when source stream ends, it gets destroyed from source.

On [playOpusStream](https://github.com/discordjs/discord.js/blob/8a7abc9f06d44bf693e35a615bb6ba2c3eb1d6e7/src/client/voice/player/BasePlayer.js#L68-L83) in line [71](https://github.com/discordjs/discord.js/blob/8a7abc9f06d44bf693e35a615bb6ba2c3eb1d6e7/src/client/voice/player/BasePlayer.js#L71) you can see that a pipe is used to enable for volume adjustments.

```js
streams.opus = stream
        .pipe(decoder)
        .pipe(streams.volume)
        .pipe(new prism.opus.Encoder({ channels: 2, rate: 48000, frameSize: 960 }));
```

Piping the source stream to current dispatcher creates an intermediate which prevents [`_destroy()`](https://github.com/discordjs/discord.js/blob/8a7abc9f06d44bf693e35a615bb6ba2c3eb1d6e7/src/client/voice/dispatcher/StreamDispatcher.js#L120) from destroying the source opus stream.

```js
 _destroy(err, cb) {
    this._cleanup();
    super._destroy(err, cb);
  }

  _cleanup() {
    if (this.player.dispatcher === this) this.player.dispatcher = null;
    const { streams } = this;
    if (streams.broadcast) streams.broadcast.delete(this);
    if (streams.opus) streams.opus.destroy();
    if (streams.ffmpeg) streams.ffmpeg.destroy();
  }
```
### Reproduce

With the following code, you execute the destroy function `dispatcher.destroy();` and the stream will still run, in the background idle (can be seen using `top` in terminal)
```ts
function create_dispatcher(
	video_options: yts.VideoSearchResult, voice_connection: VoiceConnection
): StreamDispatcher {
	const stream = ytdl(video_options.url, {
		filter: 'audioonly',
		opusEncoded: true,
		encoderArgs: ['-af', 'bass=g=10, dynaudnorm=f=200']
	});

	const stream_options = <StreamOptions>{
		type: 'opus'
	}

	return voice_connection.play(stream, stream_options);
}
```
In order to destroy the source stream you must add `volume: false` option in StreamOptions
```ts
const stream_options = <StreamOptions>{
	type: 'opus',
        volume: false
}
```

> Note that setting a custom `bitrate` will also trigger a pipe and thus not destroy upon destroy()

This probably is not the intended behaviour, and should probably be handled seperately.

**Related errors:**

https://github.com/discordjs/discord.js/commit/4009986bc8bd1ccf0bdbd0b5135c1bde78839ed2
https://github.com/nodejs/node/pull/32968

**Further details:**

- discord.js version: 12.5.1 (stable)
- Node.js version: 14.16.0
- Operating system: (Ubuntu 20.04.2 LTS focal)
- Priority this issue should have: medium
  _not essential but causes bots to crash and run artificially slow_

**Comment by amishshah** [comment]
Hi there,

We're working on a new implementation of Discord's Voice API that has better playback quality and is more reliable than what we currently support in Discord.js v12 - check it out at https://github.com/discordjs/voice!

The new library solves many of the issues that users are facing, and as part of this, we're dropping built-in support for voice in our next major release. We have a PR (https://github.com/discordjs/discord.js/pull/5402) that adds native support for our new voice library - once this PR is merged, this issue will be closed.

You can still use our new voice library before that PR lands - just take a look at [our music bot example](https://github.com/discordjs/voice/tree/main/examples) to see how to get started upgrading your voice code. By using the boilerplate music player in the example, you can make it even easier to upgrade your code.

Note that the PR above only reduces some of the boilerplate code you'd otherwise have to write - you do not have to wait for the PR to be merged to start using the new voice library.

-----

If you have any questions about this, feel free to:

- [Make an issue](https://github.com/discordjs/voice/issues) if you have found a bug in the new voice library
- Use [GitHub Discussions](https://github.com/discordjs/voice/discussions) or join our [Discord server](https://discord.gg/djs) (we have a new channel, `#djs-new-voice`, specifically for this!) to ask general questions about the library, give feedback on the library, and get support with upgrading to it
