### ISSUE TITLE
ReactionCollector.stop is not a function

### ISSUE THREAD

**Issue by tandpfun** [discordjs/discord.js#5437]
**Please describe the problem you are having in as much detail as possible:**
It is impossible to stop a reaction collector with `collector.stop()` as it is not defined in discord.js but says it exists in the docs.

**Include a reproducible code sample here, if possible:**
```js
let filter = (reaction, user) => user.id === message.author.id;
let collector = m.createReactionCollector(filter, { time: 60000 });
collector.on('collect', async (reaction, collector) => {
    collector.stop()
})
```

**Further details:**

- discord.js version: 12.5.0
- Node.js version: v14.15.1
- Operating system: Ubuntu 18.04
- Priority this issue should have – please be realistic and elaborate if possible: high-ish (missing from v11 -> v12)

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by monbrey** [comment]
The second param emitted by ReactionCollector#collect is `user`, not `collector`.

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
