### ISSUE TITLE
Cache members received from `guild.voice_states` in guild payloads

### ISSUE THREAD

**Issue by almostSouji** [discordjs/discord.js#5474]
**Is your feature request related to a problem? Please describe.**
members in voice channels are not cached on ready, requiring a broad `<Guild>.members.fetch()` request to make sure voice states are available for any member (invisible members are not gound in the general guild member data arriving via WS but `<guilddata>.voice_states` )

**Describe the ideal solution**
cache member data we receive on initial guild payloads

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by SpaceEEC** [comment]
I tested this using a bot using the `GUILDS` and `GUILD_VOICE_STATES` intents.
Members that are currently connected seem to be under `members` in the guild create payload, `voice_states` does not contain them.
When not connected to voice, the member wasn't in the `members` array anymore.

I'm going to assume this behavior changed and since it's working as expected now I'm going to close this issue.
