### ISSUE TITLE
Invalid Error Message

### ISSUE THREAD

**Issue by eliteSchwein** [discordjs/discord.js#5499]
**Please describe the problem you are having in as much detail as possible:**
The bot should dm me with a message, which it does, but here is a invalid error message
**Include a reproducible code sample here, if possible:**

```js
  for (const notifyindex in notifylist) {
    const clientid = notifylist[notifyindex]
    client.users.fetch(clientid)
      .then(async (user) => {
        console.log(await user.send(message))
      })
      .catch((err) => { console.log((err).error) })
  }
```

**Further details:**

- discord.js version: 12.5.3
- Node.js version: 11.15.0
- Operating system: Raspbian
- Priority this issue should have – please be realistic and elaborate if possible: Mid

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

https://pastebin.com/6jzCFQbs message object
https://pastebin.com/4HmgxAhL error message
![image](https://user-images.githubusercontent.com/39838619/114036294-3ce7eb80-9880-11eb-924b-8cb735e591cd.png)

**Comment by almostSouji** [comment]
The error clearly states that you are trying to DM a user which the bot can not DM. Possible reasons are:

- bot does not share a guild with the recipient
- recipient is the bot itself or another bot
- recipient has bot blocked
- recipient has no shared guild where they have DMs enabled
- recipient categorically denied DMs

Bots can not circumvent these restrictions, this is not an error with the library.

The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
