### ISSUE TITLE
Some server emojis unable to be used when shards are used

### ISSUE THREAD

**Issue by AustrianDev** [discordjs/discord.js#5551]
Hi there,

When you want to react to a message using a custom emoji, you can use its id to react. Like :
```js
message.react("123456789123456789") // Let's say that it's the ID of the emoji
```
But if you're using shards and that the guild that hosts the custom emoji is NOT on the current shard, the reaction won't be created.

> For example, let's say this emoji (id is 123456789123456789) is in a guild A on shard 0. And you want to react to a message on shard 1 using that emoji. That won't work because the two guilds are not on the same shard.

**Node server details:**

- discord.js version: `12.5.3` (last stable)
- Node.js version: 12.22.1
- Operating system: Debian 10 (VPS)
- Priority this issue should have : medium

**Client options:**

- partials: none
- gateway intents: SERVER_MEMBERS
- **shards enabled**

**Explanation**

When `Message#react` is called, the bot is resolving the custom emoji by searching into the guilds cache :

```js
get emojis() {
    const emojis = new BaseGuildEmojiManager(this);
    // For each CACHED guild (so in the current shard)
    for (const guild of this.guilds.cache.values()) {
      if (guild.available) for (const emoji of guild.emojis.cache.values()) emojis.cache.set(emoji.id, emoji);
    }
    return emojis;
  }
```
> [See source code](https://github.com/discordjs/discord.js/blob/0d68ca8eb9abdb517acee562fe01374416d225ed/src/client/Client.js#L176)

But guilds cache is not shared between shards. It's the reason why custom emojis are not correctly resolved when the method is called.

We could fix this issue by listing all emojis using `ShardManager#broadcastEval` across shards but that could possibly increase latences when reacting to a message. If you want me to do a PR, let me know 😉

**Comment by tipakA** [comment]
From what i noticed accross the code, this is mainly because API requires `name:id` format for reacting with custom emojis. Since your id doesn't have name and is located on another shard, it can't really resolve to that.

`broadcastEval` on every single `react` call is definitely not an option that library would do on its own; best you can do to avoid it in your case right now, is to use `name:id` or full `<:name:id>` format (or use solution described below).

There is however a way to fix that. API does not validate passed name, so pretty much any non-empty name in the `name:id` format will make it react properly.

**Comment by AustrianDev** [comment]
Ok I'll try it out tomorrow. I'll let you know
