### ISSUE TITLE
GuildChannel#clone exceeds maximum call stack when providing a CategoryChannel to the parent option

### ISSUE THREAD

**Issue by monbrey** [discordjs/discord.js#5553]
`GuildChannel#clone()` internally uses `Util#mergeDefault` to merge the provided options with that of the channel being cloned.
If a CategoryChannel is provided as the `parent` option, `Util.mergeDefault` detects this as an object and infinitely recurses into it. 

**Include a reproducible code sample here, if possible:**

```js
const category = message.guild.channels.cache.get("category_id");
message.channel.clone({ parent: category });
```

**Workaround**
Pass the Snowflake directly / `category.id`

**Further details:**

- discord.js version: 12.5.3
- Node.js version: N/A
- Operating system: N/A
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Relevant client options:**

- partials: N/A
- gateway intents: N/A
- other: N/A

**Comment by BannerBomb** [comment]
Just to mention in case it's of any significance. The issue is with this line https://github.com/discordjs/discord.js/blob/0d68ca8eb9abdb517acee562fe01374416d225ed/src/util/Util.js#L292-L294. It is getting stuck when it reaches the `cacheType` key in a manager class, because on the Collection class there's a static key called `default` that is referencing back to itself. ![image](https://user-images.githubusercontent.com/11788894/115685884-a529d900-a326-11eb-86e9-2ff40b571f51.png)
