### ISSUE TITLE
GuildMemberRoleManager.remove with multiple roles doesn't work properly

### ISSUE THREAD

**Issue by Koyamie** [discordjs/discord.js#5555]
**Please describe the problem you are having in as much detail as possible:**
Using GuildMemberRoleManager.remove(Array of roles) doesn't seems to work properly, no roles are removed and no error is thrown.
Using a single role works fine.

**Include a reproducible code sample here, if possible:**

```js
var list_of_roles = ["833828666008928357","834785390447427644","834785406770741249"];

guildMember.roles.remove(list_of_roles).catch(console.error); // No roles removed, no errors

guildMember.roles.remove(list_of_roles[0]).catch(console.error); // Works fine
```

**Further details:**

- discord.js version: latest master
- Node.js version: 14.16.1
- Operating system: debian 10
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: ['REACTION','MESSAGE', 'CHANNEL', 'USER']
- gateway intents: 13999
- other: none

**Comment by iShibi** [comment]
This is my fault. The method compares the provided roles with already existing roles, to decide what should be passed to `GuildMemberRoleManager#set` (which would be the roles we want to keep).  After the changes made in #5495 the comparison should have been done using the `id` instead of the whole role object, which I forgot to change and hence the issue. This has been fixed in the above linked PR, I'm sorry for the mess tho.

**Comment by almostSouji** [comment]
if you are using the master branch please provide the commit you are on instead of "latest", as the branch moves on quite quickly. you can find the commit hash from `npm list discord.js` - note that due to a mess up in history `12.5.0`  is still displayed for master releases.

For current "latest" as of writing this 0d68ca8 would be sufficient.

**Comment by Koyamie** [comment]
> if you are using the master branch please provide the commit you are on instead of "latest", as the branch moves on quite quickly. you can find the commit hash from `npm list discord.js` - note that due to a mess up in history `12.5.0` is still displayed for master releases.
> 
> For current "latest" as of writing this [0d68ca8](https://github.com/discordjs/discord.js/commit/0d68ca8eb9abdb517acee562fe01374416d225ed) would be sufficient.

Yeah by latest I was meaning latest pull request at the time of my issue reports but will provide the hash next time.
