### ISSUE TITLE
Add Message#emojis to message class

### ISSUE THREAD

**Issue by SirTenzin** [discordjs/discord.js#5591]
**Is your feature request related to a problem? Please describe.**
No, this is just a personal idea i had im sure many other users wished we had! Its an emoji parser for messages
**Describe the ideal solution**
```js
message.emojis
// Collection<Snowflake, Emoji>
```
**Describe alternatives you've considered**
Many stackoverflow threads say to use a regex which works fine but its clunky and not in discord.js its self
**Additional context**
This should work like Message#reactions and Message#mentions!

**Comment by Keke27210** [comment]
The reason why `Message#reactions` and `Message#mentions` exists is because Discord sends them with the message itself (a bit more complicated for reactions, but that's the general thing). There is no parsing done by the library to extract mentions from messages.
Unlike them, emojis are not sent separately and **have** to be parsed from the message content.

Now, even if that could make things easier for beginners, how do we know where was that emoji in the message content, should we count emojis from embeds (from bot messages) ? There are plenty of things that may not be decidable by the library itself... and that's why it's probably easier to let the end user parse them by themselves. To pre-answer for mentions, we just provide what Discord sends so we don't have to wonder about these things directly as this is just direct API support.

Also another problem, unlike mentions where if a mention is valid on the user-side, it'll be on the bot-side (channels, roles and members are necessary in common), emojis can be used in a message while bot would not be able to use it, have it in cache (via Nitro) and what would we do in that case? Should we silently ignore it and not fill emojis, making it unreliable, or making Emoji partializable (?). And I don't know what would be the memory footprint of all the possible new emojis added that would be linked to cached messages.

+ with v12 and Structures you can easily extend the Message class to add that collection you'd fill automatically for every messages if you really want that feature, that would be an opportunity for you to bring a first "draft" of what could it look like in code.

**Comment by SirTenzin** [comment]
Thank you, and maybe i will make a draft about this!

**Comment by SirTenzin** [comment]
Hey I started working on it, struggling with instantiating an emoji class, do i have to make the "emoji" object param my self or can i query the api?

**Comment by DTrombett** [comment]
That's a really interesting feature. I think this can be done with a getter or a function that checks with regex(s) unicode and custom emojis in the message content filtering not cached emojis (or actually with partial emojis) but as said above it wasn't added because the API doesn't and doing it on our side could lead to problems...

**Comment by monbrey** [comment]
This won't be added to the library for a few reasons:

- The data isn't in the message payload.
- Maintaining a regex that matches all unicode emojis isn't desirable, even if from an external dependency.
- Performing a highly complex regex on every message payload is absolutely horrible for performance.
