### ISSUE TITLE
Property send does not exist on type 'Channel'

### ISSUE THREAD

**Issue by gelilaa** [discordjs/discord.js#5623]
**Please describe the problem you are having in as much detail as possible:**
 `Discord.Channel `does not provide `send()` method in type definition file.
**Include a reproducible code sample here, if possible:**
![image](https://user-images.githubusercontent.com/62214717/118120735-a368a800-b3f0-11eb-9f5c-75aaa297367c.png)

**Further details:**

- discord.js version:12.5.3
- Node.js version: 14

**Comment by almostSouji** [comment]
Not all channels can be sent to (voice channels being one example).
If you are using typescript you need to assert or type guard these calls (if you retrieve by ID an assertion is safe, as you definitely know the type of this channel) to a more specific channel type.

The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

**Comment by PawFV** [comment]
This is not a question, is a type error, and it can be fixed, please reopen the Issue.

**Comment by almostSouji** [comment]
As I said, the `Channel` class is a parent from which all the different channel types are derived. This is not a bug with the library.

**Comment by PawFV** [comment]
> As I said, the `Channel` class is a parent from which all the different channel types are derived, some of which can not be sent to. This is not a bug with the library.

Again **it is a bug**, you are not providing the types in this case the error is self exaplanatory enough. 

If you don't know how to infer these types that's another topic but I'd let this issue open since it's not something needs to figure out and/or go ask Discord.js a question to be able to solve it.

**Comment by almostSouji** [comment]
No, this is not a bug with the library, as much as you seemingly want it to be one.
Channels are structured in an approach similar for all channel types:
`TextChannel extends GuildChannel extends Channel extends Base`

- Base: has a client accessor
- Channel: represents __any__ channel on discord
- GuildChannel: channel inside a guild (can still be voice, text, news, etc.)
- TextChannel: a text channel

Declaring send to exist on the `Channel` class is wrong.
We do provide the correct types, however they are not used correctly by the user (and you, if you deem module augmentation necessary for this)

The `Client#channels` cache can hold __any__ type of channel, hence the most strict type we can provide here being `Channel`. This could be DM Channels, voice channels (__no__ send here!), etc.

The approach to take is to cast or guard the types.

## Casting

If you know the type of the channel better (since you know what channel's id you grabbed of) you type-cast/assert `const channel = client.channels.resolve("id") as TextChannel`

## Guarding

Handling each case appropriately

```js
const channel = client.channels.resolve("id");
if (channel.isText()) {
  channel.send("foo")
} else {
  console.log(`${channel.name} is not a text based channel`)
}
```

<https://discord.js.org/#/docs/main/stable/class/Channel?scrollTo=isText>

--- 

> Also for the average user that comes from google here and doesn't find an answer [...]
definitely ignore that screenshot.

**Comment by PawFV** [comment]
1 - You redirect the issue to another place instead of leaving a solution so others can just grab just grab that.
2 - Now that you get triggered, you post a bunch of articles and a biblic explanation of how your library works which is redundant.
3 - It is an issue and it can be solved, but you just don't know how, yet insist that it's a help question. 

I'm not going to waste more time solving your issue, with the attitude you are taking towards it. Less the less discussing on how to solve it, you know this project better than me, so have fun :).
