### ISSUE TITLE
discord.js UnhandledPromiseRejectionWarning: TypeError: fn.bind is not a function What is wrong?

### ISSUE THREAD

**Issue by officialperix** [discordjs/discord.js#5657]
find(fn, thisArg) {
        if (typeof thisArg !== 'undefined')
            fn = fn.bind(thisArg);
        for (const [key, val] of this) {
            if (fn(val, key, this))
                return val;
        }
        return undefined;

**Comment by SpaceEEC** [comment]
You seem to be passing invalid parameter(s) to [`Collection#find`](https://discord.js.org/#/docs/collection/master/class/Collection?scrollTo=find), you might want to double check with the documentation.

---

The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
