### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by Vir4k** [discordjs/discord.js#5669]
Hello Discord.js Devs,
Can you make the import package from const to import from 'discord.js'; ?

I would appreciated if it's come in v13

**Comment by kyranet** [comment]
Thank you for submitting your bug report, however, you have deleted all the metadata information that came with the template, and as such, it is not easy for us to determine your version of Node.js, OS, and discord.js.

Please edit your issue to include this missing information.

Furthermore, examples may be required for us to properly understand your issue here.

**Comment by adrifcastr** [comment]
I think they want to import 'Discord.js' when destructuring other structures from the import simultaneously

**Comment by kyranet** [comment]
That [already exists](https://github.com/discordjs/discord.js/blob/master/esm/discord.mjs), just tested it and it worked fine.
