### ISSUE TITLE
Bitrate Editable returning different value

### ISSUE THREAD

**Issue by killer069** [discordjs/discord.js#5691]
I am playing a stream with ytdl and wanted to know whether bitrate is editable or not. In documentation, it is written that it will give us a boolean value, but it is returning something else

**Include a reproducible code sample here, if possible:**

```js
await message.guild.me.voice.connection.play(await ytdl(args[0],  { filter: 'audioonly'})) //PLAYING Command

message.channel.send(`Bitrate Editable : ${message.guild.me.voice.connection.dispatcher.bitrateEditable}`) //Result command
```

**Reprduction Steps :**
1. Start the bot and make it connect to same vc as that of author.
2. Play the song using the given code
3. Now test the result of Bitrate Editable

**RESULT :**
 
```
Bitrate Editable : setBitrate(bitrate) {
    (this.encoder.applyEncoderCTL || this.encoder.encoderCTL)
      .apply(this.encoder, [CTL.BITRATE, Math.min(128e3, Math.max(16e3, bitrate))]);
  }
```
**Further details:**

- discord.js version: 12.5.3
- Node.js version: v14.17.0
- Operating system: Windows
- Priority this issue should have – I don't know whether This error is from my side or from discord js side

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by killer069** [comment]
@kyranet Anyone will see this issue or not ???

**Comment by killer069** [comment]
12 days and not even any response from developers. WoW 👏

**Comment by kyranet** [comment]
We were planning to announce this later, but since you insist... #5402 removes all voice code (including what you're using) and adds support for our newer `@discordjs/voice`, which has been so far a lot more stable and reliable.

You'll also see a large increase in audio quality and performance with the switch too.

Once the PR is merged, we'll close all the voice issues, and future ones will have to be created in the respective [discordjs/voice](https://github.com/discordjs/voice) repository.

**Comment by killer069** [comment]
Ok thanks for the info.
