### ISSUE TITLE
gif in .setThumbnail not loading

### ISSUE THREAD

**Issue by MarzonDark** [discordjs/discord.js#5697]
The .gif images in .set Thumbnail do not load (I don't know if in .setImage this is the same problem too). 

 I am using discord.js v13.0.0-dev

**Comment by killer069** [comment]
You have deleted all the metadata information that came with the template, and as such, it is not easy for us to determine your version of Node.js, OS, discord.js.

Please edit your issue to include this missing information.

Furthermore, examples may be required for us to properly understand your issue here.

And at last, I have tested this myself and set thumbnail is working fine. It maybe your url that causes the issue.

**Comment by MarzonDark** [comment]
@killer069 it's strange. Just that I read your comment it has been fixed but suddenly now the emojis do not load ... I do not know if it is because of my discord or because of D.js 13 ...

By the way I am using Discord PTB

(As you can see the gifs, I will suppose it was my discord or something from my pc)
