### ISSUE TITLE
Improve Structures - "binding"

### ISSUE THREAD

**Issue by ghostdevv** [discordjs/discord.js#5733]
**Is your feature request related to a problem? Please describe.**
Structures are great but there can be issues, and I have found a few. I have made packages that extend or add to the functionality of discord.js before, and over and over again have had people reporting to me that the packages aren't working, and the reason is that the structures aren't applying. The common reasons for this are

- Custom client (Since the `require` deal isn't being done in the custom clients file, structures aren't being picked up)
- Destructing imports (For example `const { Client } = require('discord.js');` can cause structures not to apply)

**Describe the ideal solution**
Hopefully away to "bind" structures to the client, this would also allow for structures to only affect one client which would be great!

Here are some examples of what I mean by bind
```js
const client = new Discord.Client();
const structure = new Discord.Structure('guild', () => ...);

client.structures.add(structure);
```
```js
const client = new Discord.Client();
const structure = new Discord.Structure('guild', () => ...);

structure.bind(client);
```
Of course there would be many ways to achieve this, these are just a few examples. It would be a great addition to djs and I am sure it would promote a "plugin" ecosystem if that was allowed

**Describe alternatives you've considered**
Unfortunately I haven't found another nice way to reliably achieve this concept, without extending discord.js or doing some fuckery that I wouldn't be able to ship outside my testing

**Comment by kyranet** [comment]
Structures aren't tied to the client, they're standalone.

What is happening here is that you have discord.js installed multiple times, this could be because one package installs its own version of discord.js instead of having it as a [legacy] peer module users must install on their own.

**Comment by ghostdevv** [comment]
I don't believe that it's becuase of that, though I can do some testing.

The idea still stands, binding structures to the client would be great. Even if its in client options for example.

**Comment by kyranet** [comment]
You're welcome to come up with a solution for that, my previous team wasn't able to come with any after 3 years, the only way was to not include the library in question as a dep, or exposing register hooks so they're applied to the right module.

**Comment by ghostdevv** [comment]
If you had a client option like
````js
new Client({
    structures: [
        new Structure('guild', () => ...)
    ]
});
```

That could work surely? It would be applied to the client as it started so you could easily use the extended classes, you could even keep the existing functionality of structures.

**Comment by kyranet** [comment]
How do you register extension packages with this? What about registering an extension for an extension (MyBotMessage extends MyFrameworkMessage extends Message), or unrelated/parallel (MyBotGuild, MyMusicGuild) ones?

Structures.extend work by storing the class, and then replacing it with an user-defined extension, so if something.

**Comment by ghostdevv** [comment]
Well it would be the same concept of swapping around extended classes, but done per client instead of that instance of node runtime etc.

You could still achieve that class magic.

**Comment by kyranet** [comment]
Yes, but the client instance does not exist until the user creates it.

And even if we bring one of our -next's ideas to put the client instance in a globally-accessible container, there'd still be different instances of said container (due to multiple discord.js installations), which leads to the same issue.

Something I can think of, is to export a register callback in your plug-in/extension modules and use it to register the structures using the right ones from the user's `Structures`.

While more manual, it should in theory, solve your register issue.

**Comment by ghostdevv** [comment]
Sorry for the late response! Could you give me an example of what you mean?

**Comment by kyranet** [comment]
```typescript
// module1
exports.register = (structures) => {
	structures.extend('User', (User) => class extends User {});
};
```

And then in your code:

```typescript
const { Structures } = require('discord.js');
require('module1').register(Structures);
require('module2').register(Structures);
```

Since it'll call Structures.extend to the same Structures instance (the one your application uses), it'll just work.

---

However, my suggestion to **not** include discord.js as a dependency in your plugins/extensions still remain as the cleanest and least bothersome solution, as they do not require anything further.

By ensuring they don't have discord.js as a direct dependency, your package manager won't install multiple versions of it, which leads to having the same `Structures` everywhere, and thus, solving the same issue.

Normally, you'd add discord.js as a `peerDependency`, but npm@7 made peer dependencies mandatory, and thus, defeating this solution, that's why you must have it as a development dependency at most.

Skipping the dependencies also allows your users to install whatever version of discord.js as they please: v12, v13... as long as they have `Structures` and the structures they're extending exist in the user's version.

**Comment by ghostdevv** [comment]
The method you gave could be a useful hack but I don't think it would be a good solution.
I do still think that somehow binding structures would be a great feature but I do understand why you don't.

I just think that being able to bind a structure to a client, or register a plugin - whatever it would be cause less issues.
I do think I have experienced issues with structures not applying on packages that aren't shipping discord.js as a dep but I will need to check

> Normally, you'd add discord.js as a peerDependency, but npm@7 made peer dependencies mandatory, and thus, defeating this solution, that's why you must have it as a development dependency at most.

I didn't know this, does npm@7.x now install peerDeps as deps or did I misunderstand--?

**Comment by kyranet** [comment]
> The method you gave could be a useful hack but I don't think it would be a good solution.

Please come up with a nice [PoC](https://en.wikipedia.org/wiki/Proof_of_concept) that is easy to use, maintainable, and fixes your issue, I'm sorry but I can't think of a better way that also works.

> I didn't know this, does npm@7.x now install peerDeps as deps or did I misunderstand--?

Yes, it does.
