### ISSUE TITLE
Type CommandInteraction.client to subclass

### ISSUE THREAD

**Issue by Bluenix2** [discordjs/discord.js#5788]
**Please describe the problem you are having in as much detail as possible:**

I am working in TypeScript on master with the new interactions and have started to run into my first problems. I use a subclassed `Client` but `Interaction` (and its subclass `CommandInteraction`) have the `client` property typed to `Client` (not my subclass).

**Include a reproducible code sample here, if possible:**

I think the issue is pretty straight forward otherwise I could provide a quick example.

**Further details:**

- discord.js commit: Could be reproduced on 7b2e12b102984abf61132e1057558ef7f04e6d83 (latest)
- TypeScript version: 4.2.4
- Priority this issue should have: Extremely low

**Potential Solutions**

I could perhaps subclass `CommandInteraction` as well, and override that typing this requires only change on my end. Another solution would be using generics.

This could perhaps be something that could be added in the guide/docs on using interactions with TypeScript.

**Comment by Keke27210** [comment]
Unfortunately... there is not much we or you can do about it
Either cast `Interaction#client` to your custom structure whenever you use it, which is pretty annoying to do I agree
Or keep your custom client somewhere else and use this instead of `Interaction#client`

The same would apply for every extended structures that can be accessed from some "official" structure
