### ISSUE TITLE
member.guild.fetchAuditLogs not fetching member from guildMemberRemove

### ISSUE THREAD

**Issue by AKASGaming** [discordjs/discord.js#5851]
**Please describe the problem you are having in as much detail as possible:**
When running member.guild.fetchAuditLogs({ limit: 1, user: member.user }) in the guildMemberRemove event, the Collection is empty

**Include a reproducible code sample here, if possible:**

```js
exports.run = async(client, member) => {
		if(member.guild.me.hasPermission("VIEW_AUDIT_LOG") || member.guild.me.hasPermission("ADMINISTRATOR")){
			const fetchedLogs = await member.guild.fetchAuditLogs({ limit: 1, user: member.user })			
			const deletionLog = fetchedLogs.entries.first();
			console.log(fetchedLogs)
			const { action, reason } = deletionLog;
		}
}
```

**Further details:**
I seem to have gotten no further help with this in other servers.
I have also tried `member`, `member.user`, and `member.id`
No error, but empty Collection like below:

```js
GuildAuditLogs {
  webhooks: Collection(0) [Map] {},
  integrations: Collection(0) [Map] {},
  entries: Collection(0) [Map] {}
}
```

- discord.js version: v12.5.3
- Node.js version: v15.10.0
- Operating system: Windows 10 x64 Bit
- Priority this issue should have – please be realistic and elaborate if possible: Low?

**Relevant client options:**

- partials: none
- gateway intents: PRESENCE & SERVER MEMBERS
- other: `Discord.Client({ shards: 'auto', fetchAllMembers: true, intents: ['GUILDS', 'GUILD_MESSAGES', 'GUILD_MESSAGE_REACTIONS', 'DIRECT_MESSAGES', 'GUILD_PRESENCES', 'GUILD_VOICE_STATES', 'GUILD_INVITES', 'GUILD_INTEGRATIONS', 'GUILD_EMOJIS', 'GUILD_BANS', 'GUILD_MEMBERS', 'DIRECT_MESSAGES'] })`

**Comment by almostSouji** [comment]
A few things:
- The `user` parameter from #fetchAuditLogs works the same as it does for the GUI (your discord client) in that it filters for the person applying the action (the moderator kicking, banning, etc.)
- Audit logs are generally not guaranteed to have arrived when the corresponding websocket event emits (if you get a `guildBanAdd` event, for example)
- `guildMemberRemove` generally also emits when people leave the server out of their own will, which will not result in an audit log

--- 

The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
