### ISSUE TITLE
Permissions.remove(); dosen't work and don't show any error!

### ISSUE THREAD

**Issue by Amir-78** [discordjs/discord.js#6097]
- Hello, when i'm trying to make Role protection `when someone enable ADMINISTRATOR Permissions in a role the bot automotaclly remove it` but the bot don't show any error and didn't change anything! and i tried the code below and i got the same results `(No error and didn't change the permissions)`

**TestCode:**

```js
client.on("message", message =>{

if(message.content.startsWith("$test")){

let adminRole = message.mentions.roles.first(); //Mention ADMINISTRATOR role!

adminRole.permissions.remove('ADMINISTRATOR');

}

});
```

**Further details:**

- discord.js version: `v12.5.1`
- Node.js version: `v16.4.0`
- Operating system: `Windows 8.1 Pro`
- Priority this issue should have – please be realistic and elaborate if possible: **It seems that this problem must be solved as soon as possible because such a command is used in many protection bots in `roleUpdate` event, and will put many servers at risk.**

**Relevant client options:**

- partials: none
- gateway intents: `Both of them`
- other: none

**Comment by almostSouji** [comment]
If you want to modify the role's permissions (which this looks like) you need to call [`Role#setPermissions`](https://discord.js.org/#/docs/main/v12/class/Role?scrollTo=setPermissions), 

[`Permissions#remove`](https://discord.js.org/#/docs/main/v12/class/Permissions)  modifies the underlying bitfield but does not push any changes to the Discord API. It's a method on the Bitfield wrapper, rather than the role.

---

The issue tracker is only for bug reports and enhancement suggestions. If you have further questions, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue.
