### ISSUE TITLE
Client user activity not appearing on Discord

### ISSUE THREAD

**Issue by Ascendus** [discordjs/discord.js#6120]
**Problem:** Whenever I set the activity for the client user in the ready event, it doesn't appear on Discord and I get no errors thrown.

```js
const statuses = {
    "online": "Online",
    "idle": "Idle",
    "dnd": "Do Not Disturb",
    "invisible": "Offline"
};

await client.user.setPresence({
    status: "online",
    activity: {
        name: `${client.guilds.cache.size} servers | ${client.commandHandler.prefix}help`,
        type: "WATCHING"
    }
})
.then(async presence => {
    return console.log(`${await client.util.time()} | [ MatrixClient ] ${client.user.tag} is ready and online | Status: ${statuses[presence.status]} | Websocket Ping: ${client.ws.ping.toFixed(2)}ms`);
})
.catch(
    /**
     * @param {Error} err
     */
    async err => {
        return console.log(`${await client.util.time()} | [ MatrixClient ] ${err.stack}`);
    }
);
```

**Further details:**
- discord.js version: 12.5.3
- Node.js version: 16.5.0
- Operating system: Microsoft Windows 10 Home
- Priority this issue should have – please be realistic and elaborate if possible: Well I guess this is a big issue if others are having the same problem because a lot of people would want to set their status for their bots I guess

**Relevant client options:**
- Partials: CHANNEL, GUILD_MEMBER, MESSAGE, REACTION, USER
- Gateway Intents: GUILDS, GUILD_MEMBERS, GUILD_BANS, GUILD_EMOJIS, GUILD_INTEGRATIONS, GUILD_WEBHOOKS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS, DIRECT_MESSAGE_TYPING
- Other: none

- I have also tested the issue on latest master, commit hash: `4206e35.1626393827`. I did the exact same thing but how it's supposed to be done on v13, and it worked. Here's how I did it just in case:
```js
client.user.setPresence({
    status: "online",
    activities: [{
        name: `${client.guilds.cache.size} servers`,
        type: "WATCHING"
    }]
});`
```

**Comment by thehairy** [comment]
I think we already resolved that on the discord.
The dev branch uses **activities** and takes an array.

**Comment by Ascendus** [comment]
Yeah sorry, I just tried using the array method on v12 and it worked.

**Comment by Ascendus** [comment]
Never mind, I had the code for v13 running on the same bot as v12, so I'll need to reopen the issue, apologies

**Comment by Ascendus** [comment]
Well everyone's telling me to close it and ask in the support channels even I already have done so plenty of times so due to the pressure I will close this issue.

**Comment by almostSouji** [comment]
Can not reproduce on `13.0.0-dev.4206e35.1626393827` after using an activities array, as [documented](https://discord.js.org/#/docs/main/master/class/ClientUser?scrollTo=setPresence).

Running two bots on the same token will additionally mess with presence data and is not a supported use case. If tested on the above version with a single process running on the token the adapted code (again, `v13/@dev` requires an activities array to be passed) works as expected.

The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
