### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by PatriotZest** [discordjs/discord.js#6149]
```
let templink = args[0]
let errho = new Discord.GuildTemplate(client, templink)
      errho.createGuild('name', 'https://upload.wikimedia.org/wikipedia/commons/d/dc/YES-Snowboards-logo.jpg')
```

Running this code gives me an error of cannot read property 'id' of undefined

- discord.js version: latest
- Node.js version: latest
- Operating system: Windows

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by BannerBomb** [comment]
The second parameter of the GuildTemplate class takes an object, not a string. You shouldn't need to initialize a new GuildTemplate class instead you can use [Guild#fetchTemplates](https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=fetchTemplates) or [Client#fetchGuildTemplate](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=fetchGuildTemplate) to fetch an existing template.

**Comment by PatriotZest** [comment]
> The second parameter of the GuildTemplate class takes an object, not a string. You shouldn't need to initialize a new GuildTemplate class instead you can use [Guild#fetchTemplates](https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=fetchTemplates) or [Client#fetchGuildTemplate](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=fetchGuildTemplate) to fetch an existing template.

how do i send an object

**Comment by advaith1** [comment]
as BannerBomb said, you should not be constructing a GuildTemplate object, you should use a d.js method to fetch the template. for more help, ask in [the server](https://discord.gg/djs).

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/djs) instead of opening an issue – you will get redirected there anyway.**
