### ISSUE TITLE
Use new JS private fields on private properties

### ISSUE THREAD

**Issue by dheerajpv** [discordjs/discord.js#6167]
**Is your feature request related to a problem? Please describe.**
No, this is an enhancement so there will be fewer people relying on private APIs that can change at any time.

**Describe the ideal solution**
When v13 releases, make private fields actually private (according to the spec, preface them with `#`)

**Describe alternatives you've considered**
Use TypeScript and private fields that way, but compiling to more recent versions would result in the same behavior, and it is too much work to re-write the entire codebase.

**Additional context**
I have seen way too many people using private items like `Client#api` to manually send requests to Discord when there are new unsupported features (esp recently with slash commands and buttons). Using language-enforced privacy as opposed to just "this is private please don't use it" slapped on it would be a much better solution.

P.S: If I have to work on it, I would be open to doing it (might need some pointers as it would be my first time really diving into the code)

**Comment by vBread** [comment]
How is `client#api` supposed to be used internally if it's private?

**Comment by shinotheshino** [comment]
^ Some "private" properties aren't really private, per se; they are accessed internally by other classes. Since JS has no concept of [friends](https://en.wikipedia.org/wiki/Friend_function), such properties can't be actually private. The best we could do for those properties is use a `Symbol`, but that isn't very elegant and is more trouble than it's worth IMO.

I do agree, however, that some properties should be switched to use actual private properties; just not all of them.

**Comment by DTrombett** [comment]
IMO private methods and properties should be used by the user at their own risk. There's no reason why we should block them.

**Comment by monbrey** [comment]
Thumbs up because I agree with the premise - private properties should be concealed and unusable.

Unfortunately JS just isn't robust enough, and it's private properties mature enough to achieve this properly.

**Comment by iCrawl** [comment]
https://github.com/discordjs/discord.js/issues/3801
