### ISSUE TITLE
Retro-compatibly of channels types for stored data

### ISSUE THREAD

**Issue by DraftProducts** [discordjs/discord.js#6189]
**Is your feature request related to a problem? Please describe.**

Everyone knows that v13 brings a lot of breaking changes, but some of those are more problematic than others.
We can do without Structures (it's a huge pain in the ass but it's better for everyone), a naming convention can be replaced, but types that can be stored to be referenced like channel types are more difficult.

For all bots witch were used before this v13, a disgusting think like that is needed.
```js
const compatibilityTypes = {
    'text': 'GUILD_TEXT',
    'voice': 'GUILD_VOICE',
    'category': 'GUILD_CATEGORY',
    'news': 'GUILD_NEWS',
    'store':'GUILD_STORE',
    'GUILD_TEXT': 'GUILD_TEXT',
    'GUILD_VOICE': 'GUILD_VOICE',
    'GUILD_CATEGORY': 'GUILD_CATEGORY',
    'GUILD_NEWS': 'GUILD_NEWS',
    'GUILD_STORE':'GUILD_STORE',
    'GUILD_NEWS_THREAD': 'GUILD_NEWS_THREAD',
    'GUILD_PUBLIC_THREAD': 'GUILD_PUBLIC_THREAD',
    'GUILD_PRIVATE_THREAD': 'GUILD_PRIVATE_THREAD',
    'GUILD_STAGE_VOICE': 'GUILD_STAGE_VOICE',
};
```

**Describe the ideal solution**
Add an intern retro-compatibly in `TypeResolvable`.
I can work on it if it's needed.

**Describe alternatives you've considered**
We could roll back this commit because it brings only breaking changes and nothing new.

**Comment by monbrey** [comment]
You haven't explained at all what exactly this is needed for - I'm going to guess something like having these old type values stored in a database?

Run an update.

```sql
update channel_table
set type = 'GUILD_TEXT'
where type = 'text';
```
Or maybe you use mongo
```js
db.collection('channel_table').updateMany(
  { type: 'text' },
  { $set: { type: 'GUILD_TEXT' } }
);
```
Or use your little object map.

The change was not breaking just for the sake of breaking - it makes the types more consistent with both Discords channel type names, and the uppercase nature of other constants in the lib.

This wouldn't even be breaking if you used the `ChannelTypes` constant instead of magic strings.

**Comment by iCrawl** [comment]
For future proof thinking I think it would be better if people didn't rely on some output we give them, especially not for their own data structures and map them always to their own 👍
