### ISSUE TITLE
How to get invitations uses ?

### ISSUE THREAD

**Issue by LProgead** [discordjs/discord.js#6346]
Hi !
Discord.JS documentation says that only `code`, `channel` and `url` properties are guaranteed. 

Is there a way to "force" the return on a properties, like the `uses` one ?

Also, I use DiscordJS v13 with Node v16.6.1. 

Thanks in advance,
LProgead.

**Comment by advaith1** [comment]
use [guild.invites.fetch()](https://discord.js.org/#/docs/main/master/class/GuildInviteManager?scrollTo=fetch) or [channel.fetchinvites()](https://discord.js.org/#/docs/main/master/class/BaseGuildTextChannel?scrollTo=fetchInvites).

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/djs) instead of opening an issue – you will get redirected there anyway.**

**Comment by LProgead** [comment]
@advaith1, I use `guild.invites.fetch`. However, `uses` is never returned. 

I thought that it was a bug. That's why I opened an issue here.

**Comment by advaith1** [comment]
works fine for me 
![image](https://user-images.githubusercontent.com/11778454/128624869-12355a0c-5687-46b5-beb5-2ed9917f263a.png)

**Comment by LProgead** [comment]
Ow... 
Weird...

I'll try different things to make it working. 

Thanks a lot for your time 😄
