### ISSUE TITLE
messageCreate event don't trigger with DMs

### ISSUE THREAD

**Issue by ThePedroo** [discordjs/discord.js#6370]
```js
client.on('messageCreate', async (message) => {
console.log(message.content)
})
```

**Further details:**

- discord.js version: 13.0.1
- Node.js version: 16.6.1
- Operating system: Linux Ubuntu 20.04 in a container
- Priority this issue should have: medium

**Relevant client options:**

- partials: none
- gateway intents: tried all
- other: none

I tried message & messageCreate, but the event don't trigger if someone DM the BOT

**Comment by GoldenAngel2** [comment]
You need the `CHANNEL` partial for the bot to get DMs
https://discordjs.guide/additional-info/changes-in-v13.html#dm-channels

> Also use the [support server](https://discord.gg/djs)

**Comment by almostSouji** [comment]
As many other changes this is listed on the v13 update guide:<https://discordjs.guide/additional-info/changes-in-v13.html#dm-channels>

The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/djs) instead of opening an issue – you will get redirected there anyway.
