### ISSUE TITLE
Couldn't create context menu with name containing spaces

### ISSUE THREAD

**Issue by KurokuTetsuya** [discordjs/discord.js#6389]
**Please describe the problem you are having in as much detail as possible:**
I'm trying to create a CHAT_INPUT context menu with discord.js function, but it throwing this error:
![image](https://user-images.githubusercontent.com/45705890/129025172-db41504c-f8de-4f5d-adde-db6accec3f8a.png)
I'm asking discord devs community and they say its possible to add spaces on context menu name. The manual way seems working:
![image](https://user-images.githubusercontent.com/45705890/129025268-24f34351-5d9a-49b9-bffc-e292b0e9415e.png)

**Include a reproducible code sample here, if possible:**
```js
Guil.prototype.commands.create({ name: 'some name with spaces', type: 'CHAT_INPUT'})
```

**Further details:**

- discord.js version: main branch
- Node.js version: 16.6.1
- Operating system: Arch (WSL)
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by advaith1** [comment]
you're on an old commit

**Comment by nyapat** [comment]
seems like you made a typo that this is for `CHAT_INPUT`, as builders verifies the name for SlashCommands (currently our only builder for application commands) this is a valid issue

**Comment by advaith1** [comment]
`CHAT_INPUT` input commands are **not** context menu items, they are normal slash commands. The error you're getting is from Discord, since slash commands still have their name and description restrictions. Only the `USER` and `MESSAGE` types are context menu item commands.

https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-types

**Comment by KurokuTetsuya** [comment]
oh, I misread it. my apologies, thanks for replying. Closing this quickly
