### ISSUE TITLE
messageCreate event not getting emitted

### ISSUE THREAD

**Issue by thorsten451** [discordjs/discord.js#6442]
**Please describe the problem you are having in as much detail as possible:**
If I send a message after the bot gets ready, the messageCreate does not get emitted. 

**Include a reproducible code sample here, if possible:**

```js
const dc = require('discord.js');
const client = new dc.Client({intents: [dc.Intents.FLAGS.GUILDS]});
client.on('messageCreate', (a) => {
    console.log(a.content)
})
client.on('ready', () => {
    console.log('ready as ' + client.user.tag)
})
client.login(token)
```

**Further details:**

- discord.js version: 13.1.0 (stable)
- Node.js version: v16.6.2
- Operating system: GNU/Linux Pop!_OS, but can be reproduced on a different machine with Ubuntu 18.04.5 LTS
- Priority this issue should have – please be realistic and elaborate if possible: If this is not my fault, i would consider it quite high as messages are quite relevant for most bots

**Relevant client options:**

- partials: none
- gateway intents: GUILD

**Comment by vladfrangu** [comment]
You're missing the GUILD_MESSAGES intent.

__**This issue tracker is only for bug reports and suggesting enhancements.**__

If you have a question, please ask it in the **[Discord Server](https://discord.gg/djs) or in [GitHub Discussions](https://github.com/discordjs/discord.js/discussions)** instead of opening an issue – you'll be redirected there anyways.

**Comment by thorsten451** [comment]
Same issue with the GUILD_MESSAGES intent.
