### ISSUE TITLE
Missing type property for interaction#options#getMentionable

### ISSUE THREAD

**Issue by SquareIsNotCool** [discordjs/discord.js#6456]
**Is your feature request related to a problem? Please describe.**
When using interaction#options#getMentionable there's no easy way of telling whether it's a role or user. Meaning we have to resolve to several instanceof checks

**Describe the ideal solution**
a simple interaction#options#getMentionable#type property would be great

**Describe alternatives you've considered**
¯\\\_(ツ)\_/¯

**Additional context**
None

**Comment by monbrey** [comment]
This would mean that `getMentionable` would have to return some sort of complex and/or composite type, such as `{ type: "USER", value: <User> }`, since we aren't going to add `type` properties to the User or Role objects it currently returns.

Can you provide an example of how you're using this type where it matters if its a User or a Role, but can't use the separate USER/ROLE type options instead?

**Comment by SquareIsNotCool** [comment]
I don't have such a situation where I can't just use the separate USER/ROLE type options, but it'd be nice if we could use the MENTIONABLE type without having to resort to the several instanceof checks.

**Comment by vladfrangu** [comment]
> Can you provide an example of how you're using this type where it matters if its a User or a Role, but can't use the separate USER/ROLE type options instead?

Use case: adding / removing an overwrite on a user or a role..there's others too if you dig into thinking

**Comment by ImRodry** [comment]
I don't think it would be a good idea because then you'd be receiving an object with a type property and the actual object you want inside which would also be a pain to design and document. You should technically only need one instanceof check because if it isn't a role then it's either a member (if it's in a guild) or a user so I don't see how this would be an issue

**Comment by SquareIsNotCool** [comment]
> I don't think it would be a good idea because then you'd be receiving an object with a type property and the actual object you want inside which would also be a pain to design and document. You should technically only need one instanceof check because if it isn't a role then it's either a member (if it's in a guild) or a user so I don't see how this would be an issue

There's both `Role` and `APIRole`

**Comment by ImRodry** [comment]
You should know which one of those it is though if your bot is on the guild or not

**Comment by SquareIsNotCool** [comment]
> You should know which one of those it is though if your bot is on the guild or not

I'm not too familiar with v13. Mind explaining this a but further?

**Comment by ImRodry** [comment]
> > You should know which one of those it is though if your bot is on the guild or not
> 
> I'm not too familiar with v13. Mind explaining this a bit further?

You can only get the raw API data if your bot is not on the guild the command was ran in, otherwise you will always get the djs object
