### ISSUE TITLE
Possibility of same old & new structure for `Client#threadMembersUpdate`

### ISSUE THREAD

**Issue by Jiralite** [discordjs/discord.js#6513]
**Please describe the problem you are having in as much detail as possible:**
`<Client>.threadMembersUpdate` has the possibility of emitting the same `Collection` for both the `oldMembers` & `newMembers` parameters.

This is achieved by the following:
1. Join a thread
2. Restart your bot to ensure reproducibility. **Do not fetch active threads**!
3. Leave the thread

Upon leaving the thread, `oldMembers` and `newMembers` will emit the same `Collection`. Needless to say, this is quite... pointless! This is because the thread channel's members didn't have the member in question cached, ergo the same structures.

**Include a reproducible code sample here, if possible:**

```js
const client = new (require("discord.js").Client)({
  intents: [
    "GUILDS",
    "GUILD_MEMBERS"
  ]
});

client.once("ready", () => {
  const thread = client.channels.resolve("thread_id"); // Thread
  console.log(thread.members.cache); // Collection(0) [Map] {}
});

// Emitting from thread_id
client.on("threadMembersUpdate", (oldMembers, newMembers) => {
  console.log(oldMembers.equals(newMembers)); // true
});

client.login("token");
```

**Possible Fixes:**
I guess the simple answer is the make the `oldMembers` parameter nullable after these operations:
https://github.com/discordjs/discord.js/blob/70cc0295f833cd988ea627b37d20536f73e21630/src/client/actions/ThreadMembersUpdate.js#L11-L20
We could just check to see if the size is equal and return `null` if so. By sending out `null`, we are essentially saying that an event occurred that we did not have enough data about (the old cache was unreliable).

~~I guess another way to do it would be to emit a "fake" `ThreadMember` that we create solely for it to be removed here just to ensure that the event fires with an actual `ThreadMember`. I'm unsure if this is possible.~~

**Further details:**

- discord.js version: 13.2.0-dev
- Node.js version: 16.6.1
- Operating system: macOS Big Sur 11.5.2
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Relevant client options:**

- partials: none
- gateway intents: GUILDS & GUILD_MEMBERS
- other: none
- I have also tested the issue on latest main; Commit hash: f39b597e3120701287e86acdb247b4815f693c91

**Comment by DTrombett** [comment]
In my opinion, the problem is that both the old and new members may be partials, as Discord only sends us the added/removed members, so, if a member is added in a thread of which members are not cached, the emitted event will only contain eventually added members and, incredibly, if another member is added, the newMembers collection will contain the new member, the previously added member, but not all the members added before, which seems quite useless.
A solution would be to emit the event with two parameters: a collection of removed members and a collection of added members, as these are surely sent by the API, but this would probably be a breaking change.
