### ISSUE TITLE
No awaitMessageComponent() function for audit log executor's dmChannel object

### ISSUE THREAD

**Issue by imbyoe** [discordjs/discord.js#6541]
there's No awaitMessageComponent() function for audit log executor's DM channel object, it shows it on autocomplete then gives me an error when I use it.

```js
last.executor.dmChannel
      .awaitMessageComponent({
        filter: (x) => x.user.id == last.executor.id,
        componentType: "SELECT_MENU",
        time})
```

Error: TypeError: Cannot read property 'awaitMessageComponent' of null

**Further details:**

- discord.js version: 13.1.0
- Node.js version: v16.4.0
- Operating system: macOS
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**
- gateway intents: GUILDS

**Comment by almostSouji** [comment]
[`User#dmChannel`](https://discord.js.org/#/docs/main/stable/class/User?scrollTo=dmChannel) is nullable, and will be null if there is no DM with this user in the current session. [`User#createDM`](https://discord.js.org/#/docs/main/stable/class/User?scrollTo=createDM) can open a DM channel, however, it is generally surprising to wait for an action in DMs out of nowhere. 

Seeing that you are waiting for an action on a component, that component is presumably placed in DM's and you are probably better off starting it on the message you send with the component in the first place. Please visit our discord server for support requests:

--- 

The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/djs) instead of opening an issue – you will get redirected there anyway.
