### ISSUE TITLE
New convenience method: replyOrFollowUp

### ISSUE THREAD

**Issue by Togira123** [discordjs/discord.js#6545]
**Is your feature request related to a problem? Please describe.**
Sometimes you don't know whether you've already replied to an interaction, and always checking if that's the case and if it is calling `followUp()` is annoying.

**Describe the ideal solution**
The ideal solution would in my opinion be a new method called `replyOrFollowUp` which would check if the interaction was already replied to. If it wasn't, the method would call `reply`, and if it was it would call `followUp`.

**Describe alternatives you've considered**
Checking if an interaction was already replied, but as I said I think it's annoying. 

**Additional context**
none

**Comment by xMooddyy** [comment]
This can be easily achieved using an if statement.

```typescript
if (interaction.replied || interaction.deffered) {
   interaction.followUp(...args);
} else {
   interaction.reply(...args);
}```

**Comment by Togira123** [comment]
> This can be easily achieved using an if statement.
> 
> ```ts
> if (interaction.replied || interaction.deferred) {
>    interaction.followUp(...args);
> } else {
>    interaction.reply(...args);
> }```
> ```

I mean yes but I'm saying in my message that I think that's annoying, and this is exactly the reason why I'm making this feature request

**Comment by iCrawl** [comment]
What would be the use case where you would not know when to followUp or reply?

**Comment by ImRodry** [comment]
> This can be easily achieved using an if statement.
> 
> ```ts
> if (interaction.replied || interaction.deferred) {
>    interaction.followUp(...args);
> } else {
>    interaction.reply(...args);
> }```
> ```

or even better

```js
const reply = interaction.replied || interaction.deferred ? await interaction.followUp(...args) : await interaction.reply(...args)
```
I don't see any problem with this and this would just be a rather useless shortcut imo

**Comment by Togira123** [comment]
> What would be the use case where you would not know when to followUp or reply?

If, for example, you have a method which replies (or follows up) on an interaction and this method is used in multple places and sometimes called before the interaction was replied and sometimes called after.

**Comment by Milo123459** [comment]
I'm happy to implement this. I completely agree, and think this is cleaner. Proposed usage is going to be something like: `interaction.replyOrFollowUp(..)`?

And this only needs to be done on Interaction, right? No other Class'?

**Comment by ImRodry** [comment]
Should go in InteractionResponses I think

**Comment by Milo123459** [comment]
As well? I'm just curious about webhooks.

**Comment by ImRodry** [comment]
Only in InteractionResponses, not Interaction. Also webhooks don't have a followUp method, it's just webhook.send so it probably doesn't need to be added there

**Comment by Milo123459** [comment]
Alright sounds good

**Comment by ImRodry** [comment]
@Milo123459 Just to clarify you only need to add the empty method in the interaction class files for documentation purposes, no need to duplicate the code on those files since it's implemented by InteractionResponses

**Comment by Milo123459** [comment]
Yea, figured that one out by the helpful comment

**Comment by ckohen** [comment]
So, I built this into my initial implementation, and while it works decently well, I don't actually think its something the library should implement.

1. Typings on this are extremely hard, we don't get a message back from discord when using reply() but we do when using editReply() or followUp(). If you want to guaranteed return a message, you have to make an extra API call (which reply would do for you when options are set appropriately).
2. This is a simple helper that is very easy for users to implement in their own desired way, like so:
```js
// Somewhere in a util file or something
function replyOrFollowUp(interaction, ...args) {
  if (interaction.replied) {
    return interaction.followUp(...args);
  }
  if (interaction.deferred) {  // Currently behaves the same but could change in the future
    return interaction.editReply(...args);
  }
  return interaction.reply(...args);
}

// Command file
function run(interaction) {
  replyOrFollowUp(interaction, 'Some content')
}
```
Doing it this way also gives you the dev flexibility to change how things behave when the interaction is already replied to. For example, ephemeral can't be changed when editing a reply, but otherwise it can be, so that's undefined behavior if written into the lib.

**Comment by Milo123459** [comment]
I believe there is a way to type it with some TS magic. I can figure it out tomorrow on my￼￼ branch.

**Comment by monbrey** [comment]
Would rather developers handle this behaviour in their own code, as ckohen suggested. Replies and followups are not the same and should not be grouped together to enable lazy developers

**Comment by Deivu** [comment]
You could just implement your own interaction context class, where it accepts the initial interaction from interaction create, then add your own methods onto that, like this replyOrFollowUp, Discord.JS provides the properties you need for this check, so personally it would be better for this to be in Developer's impl rather than Discord.JS
