### ISSUE TITLE
Misleading `GuildMember#pending` boolean on partial guild members

### ISSUE THREAD

**Issue by Jiralite** [discordjs/discord.js#6546]
**Please describe the problem you are having in as much detail as possible:**
On the `guildMemberUpdate` event when an uncached guild member does something (most notably: joining the server via passing Membership Screening), `oldMember.pending` is `false`. This is incorrect.

**Include a reproducible code sample here, if possible:**
1. Ensure a guild member has not passed Membership Screening in the guild
2. Start the bot up:

```JavaScript
const client = new (require("discord.js").Client)({
  partials: [
    "GUILD_MEMBER"
  ],
  intents: [
    "GUILDS",
    "GUILD_MEMBERS"
  ]
});

client.on("guildMemberUpdate", (oldMember, newMember) => console.log(oldMember.pending, newMember.pending));
client.login(token);
```

3. Have them pass Membership Screening or change their nickname or give them a role etc.

<details>
<summary>Response</summary>
Under the assumption this was the guild member passing Membership Screening:

```JavaScript
false false
```
</details>

I was using this event to detect who passed Membership Screening in a server for which the bot does not have the guild member cached, as I do something upon them passing said feature. I would rather discord.js not assure that the property is `false` in this scenario, but rather, have it as `null`!

**Further details:**

- discord.js version: 13.2.0-dev
- Node.js version: 16.6.1
- Operating system: macOS Big Sur 11.5.2
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Relevant client options:**

- partials: GUILD_MEMBER
- gateway intents: GUILDS, GUILD_MEMBERS
- other: none
- I have also tested the issue on latest main; Commit hash: b89280a1dd19513b06991aae1d3b720aa3a1c542

**Comment by ImRodry** [comment]
I think this issue is happening because the property is instantiated as false, as you can see here
https://github.com/discordjs/discord.js/blob/b89280a1dd19513b06991aae1d3b720aa3a1c542/src/structures/GuildMember.js#L58
This can be misleading like you mentioned so it seems to me that setting this to null would be the better approach, however, this would be a semver major as it would change the type of the property so it’s better to hold off for now and fix it in v14.

**Comment by DTrombett** [comment]
> setting this to null would be the best approach

This is sadly not so easy. It was defaulted to `false` because the `pending` property may be missing when the member is not pending as per discord/discord-api-docs@2fe4e62a86f1d6b79bb57e3b46f0016b03391261:
> pending won't be serialized if null, that's just it's internal value, [...]
> not serialized -> member is not pending

So, when a new GuildMember structure is created, `pending` would be defaulted to null if not sent by the API too, even if the member is not actually pending.
A solution may be to default it to null and do this in the `_patch()` method, so that it's null only when the structure is partial, although it seems a bit tricky:
```js
if ('pending' in data) this.pending = data.pending;
else if (!this.partial) this.pending = false;
```
