### ISSUE TITLE
``ContextMenuInteraction`` add inMessage() and inUser() function

### ISSUE THREAD

**Issue by AwaDeQlo** [discordjs/discord.js#6556]
Hi!

I was thinking that these functions might be useful and I don't know if they plan to add them

**Comment by ImRodry** [comment]
Hey! I believe you probably got this idea from the inGuild() or isX() methods, however these exist because they provide type assertion for TypeScript users. I believe these two methods you suggested would be simple booleans and you can always check the type of context menu interaction through the targetType property.
That being said, unless you have a specific use case where these methods would be better than checking for the targetType property, or if you have an idea of what types to assert with these methods, I don't think these should be added

**Comment by AwaDeQlo** [comment]
> ¡Oye! Creo que probablemente sacaste esta idea de los métodos inGuild () o isX (), sin embargo, existen porque proporcionan una afirmación de tipo para los usuarios de TypeScript. Creo que estos dos métodos que sugirió serían booleanos simples y siempre puede verificar el tipo de interacción del menú contextual a través de la propiedad targetType.
> Dicho esto, a menos que tenga un caso de uso específico en el que estos métodos serían mejores que verificar la propiedad targetType, o si tiene una idea de qué tipos afirmar con estos métodos, no creo que se deban agregar.

Oh! thanks for informing me

**Comment by ImRodry** [comment]
r/unexpectedlySpanish
