### ISSUE TITLE
Bug: banAdd event wrong type

### ISSUE THREAD

**Issue by AlexZeDim** [discordjs/discord.js#6624]
### Issue description

Start your client (unverified bot) with the following intentions:

```ts 
    this.client = new Client({
      intents: [
        Intents.FLAGS.GUILDS,
        Intents.FLAGS.GUILD_MESSAGES,
        Intents.FLAGS.GUILD_INVITES,
        Intents.FLAGS.GUILD_BANS,
      ],
      presence: {
        status: 'online',
        activities: [{
          name: 'users',
          type: 3,
        }]
      }
    });
```
Listen for the guild event `guildBanAdd`:
```ts
   this.client.on('guildBanAdd', async (guildBan: GuildBan) => {
     console.log(guildBan)
   })
```
and the print in the console will have `guild` and `user` props, but not reason, and everything else, like it's described at [GuildBan](https://discord.js.org/#/docs/main/stable/class/GuildBan)

### discord.js version

13.1.0

### Node.js version

16.9.1

### Operating system

Windows 11

### Priority this issue should have

Medium (should be fixed soon)

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_MESSAGES

**Comment by BenjammingKirby** [comment]
well partial is a getter and reason is an optional property, so i think this works as intended

**Comment by ImRodry** [comment]
As described in [Discord's API documentation](https://discord.com/developers/docs/topics/gateway#guild-ban-add-guild-ban-add-event-fields), the guildBanAdd event does not emit a full GuildBan object. In order to obtain the full object, including the reason, you must use [GuildBan#fetch](https://discord.js.org/#/docs/main/stable/class/GuildBan?scrollTo=fetch). This is not a bug with the library as this is working as intended per Discord's documentation.
