### ISSUE TITLE
Feature request: Make Collection .map() consistent with .filter()?

### ISSUE THREAD

**Issue by 2mill** [discordjs/discord.js#6645]
### Feature

Hi everyone,

So Collection.filter() produces a Map from id to object, but I was wondering if it's possible to have the framework produce a map given a function for the map() function? It believe it would make Collection more consistent?

-Yannick

### Ideal solution or implementation

Make Collection.map() return a map instead of an array like filter() does.

**Comment by almostSouji** [comment]
Collection is developed at https://github.com/discordjs/collection, so this is the wrong place for this feature suggestion.

However, Collection#map is one of the array-like methods, which maps values in a map to an array of transformed values, consistent with Array#map. Making this a Map -> Map function would require some more thought, as you'd still need to map to a key-value pair (unless you imply that it should keep the key and just transform the values). If anything this could probably be considered as a new method, not a consistency patch to the already existing and widely used #map method.

(returning a filtered subset is less of an issue, because it does not allow transformation, it simply returns a subset of this)

closing because not relevant to discord.js itself.
