### ISSUE TITLE
Bug: Role.toJSON() Returns Invalid JSON

### ISSUE THREAD

**Issue by acd124** [discordjs/discord.js#6648]
### Issue description

When converting a Role to JSON, discord.js returns the permissions field as a BigInt. Since BigInts do not have a default representation in JSON, this causes it to error with the message `Do not know how to serialize a BigInt`.

### Codesample

```typescript
const { Client } = require('discord.js');
const client = new Client({ intents: 'GUILDS' });
client.on('ready', () => {
    JSON.stringify(client.guilds.cache.first().roles.highest);
});
client.login('TOKEN');
```

### discord.js version

13.0.1

### Node.js version

16.6.1

### Operating system

MacOS

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS

### I have tested this issue on a development release

88e2622

**Comment by Dev-CasperTheGhost** [comment]
Had a similar issue before, this fixed it for me. This doesn't seem like a bug with Discord.js, for questions you can always [use the Discord server](https://discord.gg/djs)

```ts
JSON.stringify(client.guilds.cache.first().roles.highest, (_, value) => {
	return typeof value === "bigint" ? value.toString() : value;
}),
```

**Comment by VoltrexMaster** [comment]
This is not a bug, as the JSON spec does not have a way to represent bigint values, the lib returns it as a bigint to correctly represent the permission bitfield of the role for consistency. Casting the bigint to a primitive number would just return incorrect bitfield values if the value is an integer with a higher precision than 32-bits, this is why it's returned as a bigint.

All you can do right now is to cast the bigints to a string using `JSON.stringify()` method's second method to pass a replacer.

**Comment by acd124** [comment]
> Had a similar issue before, this fixed it for me. This doesn't seem like a bug with Discord.js, for questions you can always [use the Discord server](https://discord.gg/djs)
> 
> ```ts
> JSON.stringify(client.guilds.cache.first().roles.highest, (_, value) => {
> 	return typeof value === "bigint" ? value.toString() : value;
> }),
> ```

This does not work for a case like `ShardClientUtil.broadcastEval` which does not let you provide any options to the `JSON.stringify` because the stringifying is in the implementation of the inter-process messaging.

**Comment by acd124** [comment]
> This is not a bug, as the JSON spec does not have a way to represent bigint values, the lib returns it as a bigint to correctly represent the permission bitfield of the role for consistency. Casting the bigint to a primitive number would just return incorrect bitfield values if the value is an integer with a higher precision than 32-bits, this is why it's returned as a bigint.
> 
> All you can do right now is to cast the bigints to a string using `JSON.stringify()` method's second parameter to pass a replacer.

The BitField class includes a toJSON method, which returns bigints as their string representation. The Role toJSON however does not use it, it instead uses the valueOf the bitfield. This is proof that the library knows how to represent bigints in JSON but fails to do so in this case. That is why I consider this a bug.

**Comment by kyranet** [comment]
What @acd124 is right, `BitField#toJSON` already accounts for bigints:

https://github.com/discordjs/discord.js/blob/3b14883e349c23a15aec225bb133ce49ed440817/src/util/BitField.js#L117-L119

However, `BitField#valueOf` does not:

https://github.com/discordjs/discord.js/blob/3b14883e349c23a15aec225bb133ce49ed440817/src/util/BitField.js#L121-L123

This bit of code is intentional, `valueOf` is never supposed to be used when serializing to JSON, and it returns the direct number representation, as recommended ([mdn docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/valueOf)).

`Role#toJSON`, calls `Util#flatten`, and while the method often outputs JSON-serializable data, it calls `valueOf` instead of `toJSON`:

https://github.com/discordjs/discord.js/blob/3b14883e349c23a15aec225bb133ce49ed440817/src/util/Util.js#L39

Changing the `valueOf` check and call to `toJSON`, as well as adding a `toJSON` step before `valueOf`, are both semver-major, as the values returned by `Role#toJSON` (as well as manual `Util.flatten` calls) will change. The third option is something I suggested a while ago, which is getting rid of the utility and define the properties to serialize manually.

The fastest and hybrid approach is to simply change the following code:

https://github.com/discordjs/discord.js/blob/3b14883e349c23a15aec225bb133ce49ed440817/src/structures/Role.js#L377-L379

Into an object spread with manual object assignments:

```js
  toJSON() {
    return {
      ...super.toJSON({ createdTimestamp: true }),
      permissions: this.permissions.toJSON(),
    };
  }
```

And I believe this fix will classify as semver-patch, since it fixes `Role#toJSON()`'s behavior and doesn't change the behavior of `Util.flatten` in breaking ways.
