### ISSUE TITLE
Bug: API Error when trying to add an array of roles to a member if roles arent removed prior

### ISSUE THREAD

**Issue by JustSxm** [discordjs/discord.js#6673]
### Issue description

1. Create two roles
2. Add yourself those two roles
3. Use the code sample below
4. Get a duplicate value error

Currently to counter this, you must remove the roles who are gonna be added first and then add the roles. This is really inconvenient.

### Codesample

```typescript
client.guilds.cache
      .get("guildId")
      .members.fetch("yourId")
      .then((m) =>
        m.roles.add([role1Id, role2Id])
      );
```

### discord.js version

13.1.0

### Node.js version

v16.9.1

### Operating system

Windows 10

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS

**Comment by Jiralite** [comment]
Seems the fault lies here:

https://github.com/discordjs/discord.js/blob/92f6471e8e37e5f852d2c310e7c1b43cd42bc44d/src/managers/GuildMemberRoleManager.js#L105

The cached values (`..this.cache.values()`) wouldn't be the same as ids (`resolvedRoles`), so that `new Set()` wasn't really going to work. Could replace it with this:

```JavaScript
const newRoles = [...new Set(resolvedRoles.concat(...this.cache.map(({ id }) => id)))];
```

**Comment by ImRodry** [comment]
Yeah that seems to be correct and I believe I've also come across this issue before, just never really bothered to look into why and just assumed it was my fault. Could you open a PR @Jiralite?
