### ISSUE TITLE
Bug: Voice channel loses properties after being received as interaction option

### ISSUE THREAD

**Issue by xXLoloGameplayXx** [discordjs/discord.js#6688]
### Issue description

1. Fetch a voice channel.
2. Execute an interaction that has channel parameters and do a getChannel of the same channel.
3. Observe that some properties of the voice channel were lost (they existed before and ceased to exist).

### Codesample

```typescript
// In the ready event.

const channel = await client.channels.fetch("699644022804840468");
console.log(channel.bitrate); // In my case it returns 128000

// In the interactionCreate event.

const { id } = interaction.options.getChannel("channel");
const channel = await client.channels.fetch(id);
console.log(channel.bitrate); // Returns undefined.
```

### discord.js version

13.2.0-dev

### Node.js version

16.6.2

### Operating system

Ubuntu 18 Server

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_EMOJIS_AND_STICKERS, GUILD_INVITES, GUILD_MESSAGES, DIRECT_MESSAGES

### I have tested this issue on a development release

839974c

**Comment by ImRodry** [comment]
Can reproduce this bug and it seems to be caused by the fact that the data sent by Discord is very limited (see screenshot below). This can probably be improved by sending the channel from cache when it can be found there, will look into this possibility.
![image](https://user-images.githubusercontent.com/38259440/134775020-5e67f08a-85d6-4572-a66d-2dd62d2cc004.png)

**Comment by ImRodry** [comment]
Seems like the bug is caused by these lines so the fix should be fairly easy, we just need to check if the property we received is undefined, and not replace the existing property if so. Will open the PR to fix this and try to cover all scenarios where this happens too.
https://github.com/discordjs/discord.js/blob/839974ca432c70d57e82e9b47334f743e0c20281/src/structures/BaseGuildVoiceChannel.js#L12-L32
