### ISSUE TITLE
replying to someone message count as mention

### ISSUE THREAD

**Issue by XzFrosT** [discordjs/discord.js#6775]
### Issue description

steps to reproduce:
1 reply to any message
2 run a command that requires mention

I'm using message.mentions.members.first() I've tried with Parse on clientOptions yah not help so I guess it's a bug? or it's a feature??
![IMG-20211006-WA0050](https://user-images.githubusercontent.com/75160414/136208574-6bfd64f3-af41-4527-afc7-ad89c3cb2af7.jpg)

### Code sample

```typescript
const targetMember = message.mentions.members.first()

if(!targetMember) {
...
}

...

return message.channel.send({ ... })
```

### discord.js version

13.2.0

### Node.js version

16.6+

### Operating system

linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

USER, CHANNEL, GUILD_MEMBER, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILD_MEMBERS, GUILD_INTEGRATIONS, GUILD_WEBHOOKS, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING

**Comment by almostSouji** [comment]
This is not a bug, but the expected behavior. `Message#mentions#members` includes all members for all users that are included in the message payload. These included users are the people that get mentioned (this probably enables the client to be able and resolve the mentions to the `@name` mention format, even if the user wasn't cached before).

If you disable the notification in the reply [`allowedMentions: {repliedUser}`](https://discord.js.org/#/docs/main/stable/typedef/MessageMentionOptions) the user will no longer be included.

If you expect the mention to come in a certain part of the message content (or the message content in general) you might find this guide page useful: <https://discordjs.guide/miscellaneous/parsing-mention-arguments.html#parsing-mention-arguments>

**Comment by almostSouji** [comment]
Please elaborate? that option will not notify on reply and is the equivalent to you, in the GUI disabling the mention via this symbol:
![image](https://user-images.githubusercontent.com/26532370/136213682-5ebc4fae-2e24-4241-a43c-f5cd533972c8.png)

If the replied to user is not notified (the above mentioned option is supplied), the `.mentions.members/users` collections are empty.
