### ISSUE TITLE
Bot not fetching all server members

### ISSUE THREAD

**Issue by Phydose** [discordjs/discord.js#6803]
### Issue description

intents are enabled and everything is on 

### Code sample

```typescript
const client = new Client ({
  makeCache: Options.cacheEverything(),
    intents: [
    Intents.FLAGS.GUILDS,
    Intents.FLAGS.GUILD_MESSAGES,
    Intents.FLAGS.DIRECT_MESSAGES,
    Intents.FLAGS.DIRECT_MESSAGE_REACTIONS,
    Intents.FLAGS.GUILD_MEMBERS,
    Intents.FLAGS.GUILD_MESSAGE_REACTIONS,
    Intents.FLAGS.GUILD_WEBHOOKS,
    Intents.FLAGS.GUILD_VOICE_STATES,
    Intents.FLAGS.GUILD_INVITES,
    Intents.FLAGS.GUILD_BANS,
],
partials: ["CHANNEL"]
})
```

### discord.js version

13.2.0

### Node.js version

16.6.1

### Operating system

Linux/techhost

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

GUILD_MEMBER

### Which gateway intents are you subscribing to?

GUILD_MEMBERS, GUILD_WEBHOOKS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS

### I have tested this issue on a development release

it was run on the default version

**Comment by ImRodry** [comment]
You need the GUILD_PRESENCES intent in order to get all members on startup. Not sure if this is what you mean though since you included no details whatsoever.
Anyway the issue tracker is for issues within the library, which this doesn't seem to be. Please use the [Discord server](discord.gg/djs) for questions
