### ISSUE TITLE
Proposal: Split `index.d.ts` into structure-specific declaration file

### ISSUE THREAD

**Issue by suneettipirneni** [discordjs/discord.js#6854]
### Feature

As it stands now, the `index.d.ts` file is ~5000 lines. This has some disadvantages one being that it makes it hard to navigate, the other being that there's no specified structure/order as to which types belong where. They all live in the same file. The most obvious for me is that linters and formatters run noticeably slower because of the massive file size. 

To workaround these issues, I'm proposing the `index.d.ts` file be split up into separate declaration files. Then `index.d.ts` would just be a place where types from other files are reexported.

### Ideal solution or implementation

A corresponding `d.ts` file would be made for every structure. So for example `Message.js` would have a corresponding type file called `Message.d.ts`. All the types relevant to the message type would be placed in that file.

The great thing is that, this conversion process can be done gradually. We can move some types over one at a time without breaking the usage of those types.

### Alternative solutions or implementations

none

**Comment by ImRodry** [comment]
I don't see how this would make it easier to navigate these files because instead of having only 1 file in which you can use Ctrl + F to find whatever you want, now you have multiple files where you first gotta find the one you want and then find what you want inside that file. This also brings up the question of where we'd put interfaces since these are often used by multiple classes and I don't think importing/exporting through the multiple files would be any better performance-wise.
Besides that, the issue you mentioned with linters is barely noticeable since they're run on commit (if you're committing properly) which already takes a considerable amount of time and could possibly take even longer if it had to iterate through more files. Yes, Prettier does take 1/2 seconds to run on the file, but it's not that big of a deal since we're not talking about anything in the minutes' range.
