### ISSUE TITLE
Consider an object approach for `MessageEmbed#setAuthor()`

### ISSUE THREAD

**Issue by Jiralite** [discordjs/discord.js#6963]
### Feature

I'm always frustrated when I have to pass `undefined` through `MessageEmbed#setAuthor()` in order to reach the last parameter:

```JavaScript
const { MessageEmbed } = require("discord.js");
const embed = new MessageEmbed();
// data is an object from an API
embed.setAuthor(data.author, undefined, data.link);
```

I don't want an icon appearing in the embed, but discord.js enforces that the `iconURL` parameter must be provided before supplying the `url` parameter (of which I only want). Supplying `undefined` here seems... off; `null` would be a better choice, no?

### Ideal solution or implementation

Pass an object as the sole parameter:

```JavaScript
const { MessageEmbed } = require("discord.js");
const embed = new MessageEmbed();
// data is an object from an API
embed.setAuthor({ name: data.author, url: data.link });
```

This will allow one to not specify an `undefined` property to reach one's desired parameters.

### Alternative solutions or implementations

An alternative solution could be to simply replace `undefined` with `null` (allow a `null` value). TypeScript insists that this cannot be done. However, with the object approach, this wouldn't even be needed.

Another alternative solution would be to swap the priorities with the last two arguments. Whilst that does solve _this_ issue, the same problem will be encountered for wanting the `iconURL` parameter without specifying `undefined`.

**Comment by ImRodry** [comment]
I actually like this idea but I would give a different, controversial, opinion: I think we should still be able to pass a string for the author name or the object like you mentioned (much like sending messages works). This is because we often only want to specify an author name and no icon or URL, so it would make that easier. We'd only need to remove support for the other 2 parameters and put them exclusively in the object.
