### ISSUE TITLE
This code doesn't work.

### ISSUE THREAD

**Issue by vega0** [discordjs/discord.js#6973]
### Issue description

1. run
2. don't affect on user typing

### Code sample

```typescript
const msg_filter = (m) => m.author.id === i.message.author.id;

  i.message.channel.awaitMessages(msg_filter, {
                                    max: 1,
                                    time: 30000,
                                    errors: ['time']
  }).then(message => {
                                    console.log(message);
  }).catch(collected => {
                                    message.channel.send('Timeout');
  });
```

### discord.js version

13.3.1

### Node.js version

16.13.0

### Operating system

Windows 11

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

CHANNEL, GUILD_MEMBER, MESSAGE

### Which gateway intents are you subscribing to?

GUILDS

**Comment by VoltrexMaster** [comment]
That does not work because you're passing the filter as the first parameter, this was changed in discord.js v13 to only accept the filter through the options object as the first parameter. Consider the following as an example:
```js
message.channel.awaitMessages({
  filter: (m) => m.content === 'hi',
  max: 1,
  time: 15000,
  errors: ['time']
}).then((m) => { ... });

...
```

Refer to the [v12 to v13 changes](https://discordjs.guide/additional-info/changes-in-v13.html) section in the [guide](https://discordjs.guide).

For more issues like this, please refer to the [official discord.js support server](https://discord.gg/djs).
