### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by BierDav** [discordjs/discord.js#7065]
### Feature

Make this repository compatible with Deno and provide a URL.

Please Deno is so much better than node.js if many great libraries like yours support would support it, than it can grow much faster.

### Ideal solution or implementation

Any URL to a mod.ts file provided in the README.ts

**Comment by BierDav** [comment]
As far as I know you are right, but I think many discord bots (as mine) rely on your repository and if you would support deno all those bots would benefit form that. Because at the moment deno has very big advantages to node.js.

**Comment by iCrawl** [comment]
I don't know why you'd think deno has any big advantages over node (when it really doesn't).

Do you mean all those "secure" features they talk about, which you would have to disable anyway to run a discord bot?

**Comment by BierDav** [comment]
Advantages:

- You don't have to compile TypeScript
- You don't have to care about those annoying files like: package.json, package-lock.json, .tsconfig
- There is no node_modules folder
- You can import packages with ease
- Performance wise there are some pleasures and drawbacks according to the use case (https://medium.com/deno-the-complete-reference/deno-vs-node-performance-comparison-hello-world-774eda0b9c31)
- it's simpler to work with
- it makes it simpler to just separate the bot into two modules, because you just have to host them somewhere on the internet
- and the most important factor in my opinion is how fast you can get into debugging mode: As far as I know there aren't many Discord bots written in JavaScript in comparison to those which are written in TypeScript. And it's a fact that compiling typescript and starting a JavaScript file is more effort and takes more time than just execute "deno index.ts".

I meant the phrase "big advantages" like "in general deno is better as node.js, because it has in my opinion more advantages against node.js than node.js does against deno. Sorry if that arrived wrong.

**Comment by kyranet** [comment]
As a developer who has used Node.js for longer than 5 years, I'll reply to each one of them:

- Admitedly, those aren't much of a bother, at least they allow dependencies to be installed a lot faster, specially in large projects.
- There isn't, but also the release system is quite messy and currently requires expanding like a virus: repositories that support Deno are forced to have a `deno` folder with code modified specifically so it can run there, since it uses GitHub releases. Also, doesn't it require a library's dependencies to also have Deno support? Otherwise we cannot translate well to Deno.
- There isn't for Yarn PnP either, it's just stored somewhere else, however, that comes with many issues, specially when you depend on peer dependencies.
- While I admit it's nice to be able to just pull a dependency out of the blue, you're also forced to use specific versions instead of letting a package manager optimize all the dependencies by grouping the different minors and patches to the highest version among the major, also, it doesn't allow for mechanisms such as package resolutions (which some of us use to override a version of a library to another, e.g. when dealing with mismatching versions or transient dependencies with vulnerabilities).
  Also, isn't it common to have a module just to re-export all dependencies? Since otherwise you'd be at risk of importing different versions of the same library. That feels a bit troublesome, specially if those dependencies share some exports.
- I can see Deno is getting faster than Node.js, heh.
- That is relative, honestly I think that depends on each one. Most of us are used to Node.js and its rather large set of features it provides. Sure, Deno might have some modules for that, everything has a solution.
- I'm not sure what you mean with that, microservicing is already a thing that's done a lot in Node.js.
- I can use the debugger in my TypeScript bot using Node.js, and is very quick as well, although I admit it also took a bit of time to configure it to just work.

On the other hand, Node.js has a much larger ecosystem with great stability.

Deno was made extremely focused on fixing the design issues from Node.js, but of course, Node.js has also adapted to the times and fixed parts of their general API. Each runtime has its pluses and its drawbacks.

The side note is that we might take a while before we're able to change Discord.js to support Deno. Our next major, v14, will drop out soon featuring a lot of clean-ups and improvements, however, the TypeScript rewrite is delayed until at least v15, which should happen at least 4-6 months after v14, then, we'll most likely have to update all the dependencies we use to also support Deno, then write a rather complex script (possibly more complex than [discord-api-types's](https://github.com/discordjs/discord-api-types/blob/main/scripts/deno.mjs)) to make the imports work perfectly while also removing/translating imports to specific third-party packages with their specified versions from `package.json`.

Furthermore, our Deno support can be delayed or even cancelled depending on the state of the ecosystem, once we add support for Deno, we won't be able to add support for packages that do not support it (see second point above), which can lead to higher development cost and stress among our team.

Obviously, dropping Node.js support is out of question, most of our users use Node.js.

There's just a lot of things to do first, this is no simple request, but rather one of the most complex ones we have received, and that's why you'll see some resistance to that at first.

**Comment by xHyroM** [comment]
> Advantages:
> 
> * You don't have to care about those annoying files like: package.json, package-lock.json, .tsconfig
> * There is no node_modules folder
> * You can import packages with ease
> * Performance wise there are some pleasures and drawbacks according to the use case (https://medium.com/deno-the-complete-reference/deno-vs-node-performance-comparison-hello-world-774eda0b9c31)
> * it's simpler to work with (in my experience)
> * it makes it simpler to just separate the bot into two modules, because you just have to host them somewhere on the internet
> * and the most important factor in my opinion is how fast you can get into debugging mode: As far as I know there aren't many Discord bots written in JavaScript in comparison to those which are written in TypeScript. And it's a fact that compiling typescript and starting a JavaScript file is more effort and takes more time than just execute "deno index.ts".
> 
> I meant the phrase "big advantages" like "in general deno is better as node.js, because it has in my opinion more advantages against node.js than node.js does against deno. Sorry if that arrived wrong.

https://github.com/nodejs/node/pull/36328

**Comment by BierDav** [comment]
@kyranet I see your point. Yes I agree that's probably the best way to go.

**Comment by eliyya** [comment]
Currently in the latest versions of Deno they have been adding compatibility with Node and with NPM, it can already be imported without problems, but it seems that it is not totally yet compatible, however, discord.js may end up being compatible without having to change much

![image](https://user-images.githubusercontent.com/62972439/198866263-17bcd42a-46ee-49b5-b1a5-4d9b4bdd02c8.png)

**Comment by imranbarbhuiya** [comment]
vladdy is already working on it to make it deno compatible https://github.com/discordjs/discord.js/tree/feat/no-de-no-de

**Comment by BlobTheKat** [comment]
> ![image](https://user-images.githubusercontent.com/62972439/198866263-17bcd42a-46ee-49b5-b1a5-4d9b4bdd02c8.png)

I need that font asap where did you get it?
