### ISSUE TITLE
Shards remaining in a ghost state after being invalidated.

### ISSUE THREAD

**Issue by widepeepoclap** [discordjs/discord.js#7113]
### Issue description

Sometimes, Discord invalidates an already established gateway websocket connection, resulting in a dead shard since djs doesn't try to reconnect on opcode 9 with `d: false`.
The shards just dies silently and stays in the reconnecting status but never gets queued for reconnection.

Debug logs only show this line: `[INVALID SESSION] Resumable: false.`

### discord.js version

13.3.1

### Node.js version

16.13.1

### Operating system

ubuntu

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_BANS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_MESSAGES, DIRECT_MESSAGES

**Comment by legendhimslef** [comment]
is it still happening? Does not exists in 13.9.0 at least

**Comment by legendhimslef** [comment]
> 14.4.0 still has this issue.
> 
> Also this function is causing more issues than what it's intended to fix.
> 
> https://github.com/discordjs/discord.js/blob/3f8656115bf9df0dbf8391de68a3401535325895/packages/discord.js/src/client/websocket/WebSocketShard.js#L569
> 
> 
> When a shards reconnects, it reconnects (identifies) twice, sometimes gets stuck in a loop and keeps reconnecting up to 60+ times. I've removed it more than a week ago and never had any more issues.

Interesting, we never had any such issues with that function, We have around 40+ shards.

**Comment by AppEternal** [comment]
Also running into this issue myself.

I'm running two bots, one with 20 shards and one with 1200 shards, both ran into this issue on some of the shards.
(Noticed after 20hs runtime)

Shard: 1
- 11/16/2022, 3:56:56 PM [WS => Shard 1] Setting a HELLO timeout for 20s.
- 11/16/2022, 3:56:56 PM [WS => Shard 1] [CONNECTED] Took 128ms
- 11/16/2022, 3:56:56 PM [WS => Shard 1] Clearing the HELLO timeout.
- 11/16/2022, 3:56:56 PM [WS => Shard 1] [RESUME] Session ed6a3a2376bc251e679c9b909f0beef3, sequence 1040186
- 11/16/2022, 3:56:56 PM [WS => Shard 1] [RESUMED] Session ed6a3a2376bc251e679c9b909f0beef3 | Replayed 3 events.
- 11/16/2022, 4:04:54 PM [WS => Shard 1] [INVALID SESSION] Resumable: true.
- 11/16/2022, 4:04:54 PM [WS => Shard 1] [RESUME] Session ed6a3a2376bc251e679c9b909f0beef3, sequence 1040186
- 11/16/2022, 4:04:54 PM [WS => Shard 1] [INVALID SESSION] Resumable: false.

This is the last response we got from shard 1 for 45 minutes, I've since restarted the shard.
(Other shard logs look pretty identical to this.)

Shard: 750
- 11/16/2022, 3:22:53 PM [WS => Shard 750] Setting a HELLO timeout for 20s.
- 11/16/2022, 3:22:53 PM [WS => Shard 750] [CONNECTED] Took 49ms
- 11/16/2022, 3:22:53 PM [WS => Shard 750] Clearing the HELLO timeout.
- 11/16/2022, 3:22:53 PM [WS => Shard 750] [IDENTIFY] Shard 750/1200 with intents: 112207
- 11/16/2022, 3:22:55 PM [WS => Shard 750] [INVALID SESSION] Resumable: false.
- 11/16/2022, 3:22:55 PM [WS => Shard 750] Failed to connect to the gateway, requeueing...
- 11/16/2022, 3:23:00 PM [WS => Shard 750] An open connection was found, attempting an immediate identify.
- 11/16/2022, 3:23:00 PM [WS => Shard 750] [IDENTIFY] Shard 750/1200 with intents: 112207
- 11/16/2022, 3:23:03 PM [WS => Shard 750] [READY] Session 6e2793cc4da81f7a222ebdff7c76db73.

This is one of the rare cases where it got `Resumable: false` and still managed to resume.

**Comment by Jiralite** [comment]
We've since changed the underlying WebSocket implementation. Feel free to make a new issue if you still encounter this.
