### ISSUE TITLE
MessageEmbed field parses maps no reason

### ISSUE THREAD

**Issue by elbkr** [discordjs/discord.js#7314]
### Which package is this bug report for?

discord.js

### Issue description

When you map an array and join it using the new line \n, when you add that value to an embed field value it parses the first value.

### Code sample

```typescript
const arr = [first, second, third]

let map = arr.map(e => `This is ${e}`).join("\n")

console.log(map) /* returns:
first
second
third */

let emb = new MessageEmbed()
.addField("Field", `${map}`)

/* the embed field shows:
second
third

instead of: 
first
second
third
*/
```

### Package version

13.6.0

### Node.js version

16.10.0

### Operating system

windows 10

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_BANS, GUILD_EMOJIS_AND_STICKERS, GUILD_INTEGRATIONS, GUILD_WEBHOOKS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS, DIRECT_MESSAGE_TYPING, GUILD_SCHEDULED_EVENTS

**Comment by ImRodry** [comment]
Assuming you meant to put strings in your array, I cannot reproduce this as I get the expected behavior with the provided code
![image](https://user-images.githubusercontent.com/38259440/150424570-9e48751b-b4c5-42c2-9752-9bc2912e779c.png)
I suggest you use the [Discord server](discord.gg/djs) for help as this does not seem to be an issue with the library
