### ISSUE TITLE
rest clears token on 401s

### ISSUE THREAD

**Issue by advaith1** [discordjs/discord.js#7492]
### Which package is this bug report for?

rest

### Issue description

djs/rest clears the stored token whenever it gets a 401. however, this is causing issues in production, since Discord returns 401s for issues other than an invalid bot token (such as an invalid webhook token).

djs/rest seems to even do this when auth is set to false.

https://github.com/discordjs/discord.js/blob/298b22604b6e0ad0f19c2fb59513a60c682f4f17/packages/rest/src/lib/handlers/SequentialHandler.ts#L480-L482

Vlad told me to make a gh issue

### Package version

@discordjs/rest@0.3.0

### Node.js version

16.14.0

### Priority this issue should have

Medium (should be fixed soon)

**Comment by ckohen** [comment]
FYI, I looked into things that 401 with valid tokens before we migrated to /rest because I noticed it could be a problem. I went through a bunch of endpoints and made an [issue](https://github.com/discord/discord-api-docs/issues/3945) with the only one I found, didn't try webhooks though. That's gonna be a problem. We probably want to just check if auth is set on the request before calling that
