### ISSUE TITLE
Error when editing a webhook ( DiscordAPIError: 401: Unauthorized )

### ISSUE THREAD

**Issue by voxlinou1** [discordjs/discord.js#7518]
### Which package is this bug report for?

discord.js

### Issue description

1. Create a webhook :
```js
const webhook = new Discord.WebhookClient({
            url: 'https://discord.com/api/webhooks/<id>/<hidden>'
});
```
(Yes i changed "<id>" and "<hidden>" but I put them here bc i can't show my token)
```js
webhook.edit({
  name : message.author.username,
  channel : channel.id,
  avatar: 'https://i.imgur.com/AfFp7pu.png'
}).catch(console.error)
```
Then run to get the following error : 
![image](https://user-images.githubusercontent.com/71925280/154855081-d13bbc6f-7fd8-4078-a153-ab627ac2c742.png)

The thing is I can successfully send a message (a little after this there's a `await webhook.send('test')` that works just fine :/ The problem is the edit 
### Code sample

```typescript
const Discord = require('discord.js')
const webhook = new Discord.WebhookClient({
            url: 'https://discord.com/api/webhooks/<id>/<hidden>'
});
webhook.edit({
  name : "test",
  channel : "740353119703007242", // Change to your channel id on the guild the webhook is in.
  avatar: 'https://i.imgur.com/AfFp7pu.png'
}).catch(console.error)
```

### Package version

^13.6.0

### Node.js version

v17.0.1

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction

### Which gateway intents are you subscribing to?

GuildWebhooks

**Comment by DTrombett** [comment]
Not sure if related at all to this issue but tried to reproduce this in dev and got `Expected token to be set for this request, but none was present` although I provided a valid URL and logged the token to the console...

**Comment by almeidx** [comment]
This happens because you used the `channel` option, which makes it use the [Modify Webhook](https://discord.com/developers/docs/resources/webhook#modify-webhook) endpoint, which requires authentication

If you omit the `channel` option, it will use the [Modify Webhook with Token](https://discord.com/developers/docs/resources/webhook#modify-webhook-with-token) endpoint

https://github.com/discordjs/discord.js/blob/988a51b7641f8b33cc9387664605ddc02134859d/src/structures/Webhook.js#L252-L256

Since you're creating the Webhook Client using the webhook URL, the token is set automatically, so there's no reason (that I can see) to be using the `channel` option there

This should work:
```js
webhook.edit({
  name : "test",
  avatar: 'https://i.imgur.com/AfFp7pu.png'
}).catch(console.error)
```

**Comment by voxlinou1** [comment]
@almeidx Oh okay thanks ! So there's no way to change with the channel where my webhook will start sending messages ?

**Comment by advaith1** [comment]
To change a webhook's channel, you will need to use a bot with the Manage Webhooks permission, not a WebhookClient. Discord does not let webhooks change their own channel.

**Comment by vladfrangu** [comment]
See above. Please follow up if you think this is still an issue and I'll reopen the issue 👍
