### ISSUE TITLE
message.embeds becomes empty during in interaction message

### ISSUE THREAD

**Issue by oniiichannnn** [discordjs/discord.js#7697]
### Which package is this bug report for?

discord.js

### Issue description

i am trying to get the list of embeds from a interaction message sent by another bot:
```js
Client.on("messageCreate", async message => {
 console.log(message.embeds)
})
```
it logs the embeds if the message was sent like a normal message but it does not log the embeds if the message was a interaction reply, why is this?

for example:
![image](https://user-images.githubusercontent.com/67128188/159194982-4880cd51-c53b-4077-837e-57e698b8f7a8.png)
logs:
```js
[]
```

### Package version

13.6.0

### Node.js version

16.13.2

### Operating system

windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages

**Comment by almostSouji** [comment]
This is not a bug, but caused by an oddity with how Discord handles embeds.
Messages are always sent without embeds at first at `MESSAGE_CREATE` (~ `"messageCreate"`) and then edited into the message via a `MESSAGE_UPDATE` (~ `"messaegUpdate"`) payload.

This behaviour is subject to race conditions as the message object may already be updated in cache when the event emits.

**Comment by oniiichannnn** [comment]
@almostSouji so what should i do? fetch the message?
