### ISSUE TITLE
Broadcast eval erroring

### ISSUE THREAD

**Issue by ZeldaFan0225** [discordjs/discord.js#8347]
### Which package is this bug report for?

discord.js

### Issue description

When trying to boradcast eval anything I'm getting this error, if i give `() => true` for example (a simple function that shouldn't error).
I can't find what is causing it and it is broken since I updated to djs v14

### Code sample

```typescript
await client.shard?.broadcastEval((c) => true)
```

### Package version

14.0.3

### Node.js version

NodeJS: 16.14.0; Typescript: 4.3.5

### Operating system

Windows/Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages

**Comment by didinele** [comment]
This has been gone over here: https://canary.discord.com/channels/222078108977594368/1000492352999272511/1000492352999272511

We don't have a relevant error/stack trace here since the thrown error is outdated: https://github.com/discordjs/discord.js/blob/df42fdfc421f1190f0a2267a66efd3c921ec2348/packages/discord.js/src/sharding/ShardClientUtil.js#L209

Will be making a PR to fix that aspect shortly, after which we might be able to get something better to debug this problem (if it's even on our end, which I doubt).

**Comment by kyranet** [comment]
Can you update to v14.1.2 and tell me if it works? I seem to be unable to reproduce this error anymore.

![Code_vIkWmc2lMB](https://user-images.githubusercontent.com/24852502/183979845-ffe1b04a-0607-433c-83ee-6edbba893ce2.png)

**Comment by ZeldaFan0225** [comment]
It is fixed now, thanks
