### ISSUE TITLE
My bot not lunch on Linux

### ISSUE THREAD

**Issue by theohdg2** [discordjs/discord.js#8415]
### Which package is this bug report for?

discord.js

### Issue description

to contextualize the problem
I have a minecraft server that uses a lot of webhook (they are sent)

on this vps I also host a discord bot in js
 my bot is not starting to contextualize the problem
I have a minecraft server that uses a lot of webhook (they are sent)

on this vps I also host a discord bot in js
 my bot is not starting

I deduced that the webhook ratelimit interacts with that of the bot which causes me a lot of problems because I don't want to pay 2vps just to host a discord bot
![E8901B36-0F00-4CC1-B1B4-E283BC9470DD](https://user-images.githubusercontent.com/66752727/182452185-7cf06e45-6fab-4a0d-a1af-94d1d92891a1.jpeg)
![665723B3-73B4-462C-8418-F7188D7572D4](https://user-images.githubusercontent.com/66752727/182452195-b2fea4f1-9927-4770-9d9b-ed9cda239b0c.jpeg)

### Package version

discordjs@14.0.3

### Node.js version

Nodejs v16.16.0

### Operating system

Débian 1a

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers

**Comment by ImRodry** [comment]
All that log shows is that the bot connected properly so there’s really nothing to work on here
Also bots can’t have lunch yet, maybe that’s a problem for you

**Comment by vinsdragonis** [comment]
What he probably meant was that there was an issue launching starting the bot on a Linux environment 😅

The problem you have described here doesn't show precisely why the bot doesn't work as expected on a Linux machine. Could you please elaborate a bit more? Does it work on other platforms or was the problem encountered on other machines?

Also, if you just recently cloned it on your Linux machine, installed the required packages, and ran directly on localhost, I suspect you may have missed out on adding the bot's token since it is added using an environment variable. If none of the above apply, please do mention a bit more about it. I can try to have a look at it.

Thanks.
