### ISSUE TITLE
(Guild).members.me.permissions.has

### ISSUE THREAD

**Issue by KingTeox** [discordjs/discord.js#8536]
### Which package is this bug report for?

discord.js

### Issue description

1. create a if
2. use the method permissions.has
3. put invalid bit field flag or number
4. run

### Code sample

```typescript
if ((Guild).members.me.permissions.has("THANKS")) {
  console.log("Perm");
} else {
  console.log("No");
}
```

### Package version

14.2.0

### Node.js version

17.7.0

### Operating system

Windows 10 19044.1889

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, MessageContent

**Comment by KingTeox** [comment]
my bot is with administrator permission so this could be giving this problem, I don't know.

**Comment by Jiralite** [comment]
If a bot has administrator permission (and you `checkAdmin`), we perform an early exit since it will have any permission. If not, we do check to see if the input is of respective permission and throw accordingly.

One could argue why you are supplying an incorrect permission in the first place. If you truly care, you should use the enumerations (`PermissionsBitField` or `PermissionFlagsBits`) to ensure you are using a correct permission or simply use TypeScript.

**Comment by almostSouji** [comment]
Skipping checks if `8` is present is API spec <https://discord.com/developers/docs/topics/permissions#permission-overwrites>. In any other case we do validate permission flags with `RangeError [BitFieldInvalid]: Invalid bitfield flag or number: <value_provided>`
