### ISSUE TITLE
REST client returns promise that doesn't resolve during CloudFlare bans

### ISSUE THREAD

**Issue by aetheryx** [discordjs/discord.js#8574]
### Which package is this bug report for?

rest

### Issue description

requests made with the REST client during a [CloudFlare ban](https://discord.com/developers/docs/topics/rate-limits#invalid-request-limit-aka-cloudflare-bans) return a promise that never resolves (or rejects).

sample curl request:
```sh
$ curl -X POST https://discord.com/api/v10/webhooks/123/abc -i
HTTP/2 429 
date: Tue, 30 Aug 2022 06:58:06 GMT
content-type: text/plain; charset=UTF-8
content-length: 16
retry-after: 66271 # in seconds
x-frame-options: SAMEORIGIN
referrer-policy: same-origin
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Thu, 01 Jan 1970 00:00:01 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=sEudC7Le3PhOTY92gfFAKknI3HueQXnPdV3cUGPLJ1oNV1F0qPGEpgYEGGOGggEgW%2FWQToIIHOJjMEiY1Mzyzr6h3RNCKhBgvfgQWDEsvV8s%2BKD4dF5Ohzpt%2Fizr"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 742ba2d8dca607c2-ATL
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400

error code: 1015 # the body returned by cloudflare
```

sample script output:
```
/home/node/aa # node index.js 
making request to /webhooks/123/abc
/home/node/aa # echo $?
13
```
Exit code 13:
> Unfinished Top-Level Await: await was used outside of a function in the top-level code, but the passed Promise never resolved.  

which seems to indicate the promise will indeed _never_ resolve, even after the ban expires (although it waiting for the ban to expire doesn't sound good either)

### Code sample

```typescript
import { REST } from '@discordjs/rest';
import { APIVersion, Routes } from 'discord-api-types/v10';

const rest = new REST({
  version: APIVersion,
});

const url = Routes.webhook('123', 'abc');
console.log('making request to', url);
await rest.post(url, { auth: false });
console.log('finished');
```

### Package version

1.1.0

### Node.js version

18.7.0

### Operating system

Alpine (node:18.7-alpine3.15 docker image)

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

fd97da9

**Comment by ckohen** [comment]
This is currently functioning correctly. Not sure why ESM decides to not fully wait for the Promise, there is a blocking sleep operation occuring (the only non-blocking sleep is the one that happens during fetch, which is blocking in itself anyways).

The design of the ratelimitter is to wait the returned retry-after time because that is the best way to handle making sure subsequent requests aren't allowed through.

However, if you really want to change this behavior, you can use the `rejectOnRateLimit` option in the REST instance to tell the ratelimitter when to reject instead of waiting if it encounters a ratelimit. I'd recommend using a function and setting a threshold  of time that would be okay to retry for, and reject anything over that if you want to do this.
E.g
```ts
rejectOnRateLimit: (rateLimitData) => rateLimitData.timeToReset > fiveMins;
```
