### ISSUE TITLE
Inconsistency with content property in MessageOptions

### ISSUE THREAD

**Issue by MaksiRose** [discordjs/discord.js#8587]
### Which package is this bug report for?

discord.js

### Issue description

I have noticed that when looking at MessageOptions and MessageEditOptions, the embeds property is not the same, namely MessageOptions is missing the `null` option for it. This makes sense since null is only provided to remove all embeds that existed prior.
The problem is that the same is not true for the content field. Even though you can't remove content from a message that you are about to create, the `null` option still exists.

![Screenshot](https://media.discordapp.net/attachments/824411059443204127/1015575970528374784/unknown.png?width=960&height=94)

Qjuh informed me that this would be a **breaking change** due to [MessagePayload#makeContent](https://github.com/discordjs/discord.js/blob/d08a57cadd9d69a734077cc1902d931ab10336db/packages/discord.js/src/structures/MessagePayload.js#L107).

### Package version

14.3.0

### Node.js version

17.5.0

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by MaksiRose** [comment]
@Jiralite I believe this might have been fixed now with v14.4.0. I also noticed that setting content to null instead of setting it to undefined didn't work anymore in a lot of places of my code which makes me wonder why a minor update can also contain breaking changes. I can't find MessageOptions and I am not sure what it was replaced by, though. Do you know whether this is fixed now?

**Comment by Jiralite** [comment]
Thank you for the heads up - this issue is indeed resolved.

> I also noticed that setting content to null instead of setting it to undefined didn't work anymore

`content` may only be `null` when editing a message [as documented](https://discord.com/developers/docs/resources/channel#edit-message). When creating a message, it is [not documented](https://discord.com/developers/docs/resources/channel#create-message) to be `null`. The typings seemed to have always been wrong here so I'd say this is a bug fix for utilising undocumented behaviour (but that won't stop JavaScript users, I suppose).

> I can't find MessageOptions and I am not sure what it was replaced by

`MessageCreateOptions` and `MessageEditOptions` (also consistent with other names) - see the linked pull request for the changes.
