### ISSUE TITLE
Listing guild channels returns null on Forum Channels

### ISSUE THREAD

**Issue by anventia** [discordjs/discord.js#8849]
### Which package is this bug report for?

discord.js

### Issue description

1. Put bot in a server with Forum Channels
2: Put the following code in the bot:
```js
let all_channels = await guild.channels.fetch();
let test = all_channels.filter(c => console.log(c));
```
3: Console output would look something like this:
```
<#id>  // normal channels
<#id>
<#id> 
null  // forum channel
```

This breaks something such as `let num_categories = all_channels.filter(c => c.type === "GUILD_CATEGORY").size;` because it errors when trying to get `type` from the null object.

### Code sample

```typescript
let all_channels = await guild.channels.fetch();
let test = all_channels.filter(c => console.log(c));
let num_categories = all_channels.filter(c => c.type === "GUILD_CATEGORY").size;
```

### Package version

13.12.0

### Node.js version

17.0.1

### Operating system

Windows 11

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildEmojisAndStickers

**Comment by Jiralite** [comment]
This is because version 13 does not currently support forum channels.

If you look at the [documentation](https://discord.js.org/#/docs/discord.js/main/class/GuildChannelManager?scrollTo=fetch), this is documented as nullable in case we receive unknown/unparsed channel types. There seems to be no breaking behaviour here and everything is working as documented and typed.

This pull request to introduce forum channels to version 13 may interest you: #8651
