### ISSUE TITLE
Color from string not applying due to case sensitivity, yet no error

### ISSUE THREAD

**Issue by Ethorbit** [discordjs/discord.js#8932]
### Which package is this bug report for?

discord.js

### Issue description

1. Make bot post embed message, but set the embed color to one of [these strings](https://discord.js.org/#/docs/discord.js/main/typedef/ColorResolvable) in all lowercase
2. In the Discord client, the embed will appear black, instead of the color it is supposed to be. 

Usually when you pass a color that's not valid, it generates an error, but for some reason the case insensitive colors pass without error and then don't apply.

![Example](https://imgur.com/S7MXnFu.png)

### Code sample

```typescript
client.on("messageCreate", msg => {
    if (msg.author.bot)
        return;

    try
    {
        const embed = new EmbedBuilder();
        embed.setColor(msg.content); 
        embed.setTitle("Selected color");
        embed.setDescription(msg.content);
        msg.channel.send({embeds: [embed]});
    }  
    catch 
    {
        const embed = new EmbedBuilder();
        embed.setTitle("Incorrect color");
        embed.setDescription(`${msg.content} is not a valid color.`);
        msg.channel.send({embeds: [embed]});
    }
});
```

### Package version

14.7.1

### Node.js version

19.2.0

### Operating system

Arch Linux 5.15.83-1-lts

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, MessageContent

**Comment by Jiralite** [comment]
The issue lies on this line:

https://github.com/discordjs/discord.js/blob/6540914b4a7f244f5e40fe2a3b7e73986763d81b/packages/discord.js/src/util/Util.js#L480

As we already know, a lower case variant of any colour is not valid. Thus, `parseInt(color.replace('#', ''), 16)` is used for `color` instead. This is doing `parseInt('b', 16)` (in this case) and returns 11 - the first & only match.

I am not sure if fixing this would be major, however.
