### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by rodycouto** [discordjs/discord.js#9089]
### Which package is this bug report for?

discord.js

### Issue description

```js
TypeError: Cannot read properties of undefined (reading 'replace')
    at get nameAcronym [as nameAcronym] (/home/node/node_modules/discord.js/src/structures/BaseGuild.js:67:8)
    at flatten (/home/node/node_modules/discord.js/src/util/Util.js:32:24)
    at Guild.toJSON (/home/node/node_modules/discord.js/src/structures/Base.js:35:12)
    at Guild.toJSON (/home/node/node_modules/discord.js/src/structures/Guild.js:1235:24)
    at stringify (<anonymous>)
    at writeChannelMessage (node:internal/child_process/serialization:159:20)
    at target._send (node:internal/child_process:838:17)
    at target.send (node:internal/child_process:738:19)
    at /home/node/node_modules/discord.js/src/sharding/ShardClientUtil.js:85:17
```
![image](https://user-images.githubusercontent.com/70030588/214489617-3d76c4eb-39e1-4abe-be1e-72f42d32a8db.png)

### Code sample

```typescript
I login my bot and sometimes i receive this error. It's like if code tried to read a Unknown Guild
```

### Package version

14.7.1

### Node.js version

v18.12.1

### Operating system

Windows 11

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction, GuildScheduledEvent, ThreadMember

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildMessages, GuildMessageReactions, GuildMessageTyping, MessageContent, GuildScheduledEvents

**Comment by Jiralite** [comment]
Are you checking if the guild is available?

**Comment by rodycouto** [comment]
> Are you checking if the guild is available?

The bot just turn on. Sometimes, at login, that error spawn in my console. I don't make a loop or some like it.

**Comment by Jiralite** [comment]
It looks like you are calling `.toJSON()` on a guild that is not available, hence the question. Without any supplied code, this is just speculation.

The name of a guild is always sent, so this is highly unlikely to be a discord.js issue. Check to see if a guild is available or not.

**Comment by rodycouto** [comment]
> It looks like you are calling `.toJSON()` on a guild that is not available, hence the question. Without any supplied code, this is just speculation.
> 
> The name of a guild is always sent, so this is highly unlikely to be a discord.js issue. Check to see if a guild is available or not.

Dude, the error come from .login().
Don't have code.

**Comment by kyranet** [comment]
The stack trace reveals the error comes from those lines:

https://github.com/discordjs/discord.js/blob/8b70f497a1207e30edebdecd12b926c981c13d28/packages/discord.js/src/sharding/ShardClientUtil.js#L79-L93

There are very few things that call this, namely:

- `ShardClientUtil#fetchClientValues` (can't access to guilds)
- `ShardClientUtil#broadcastEval`
- `ShardClientUtil#respawnAll` (safe)
- `ShardClientUtil#_respond` (private)

> **Note**: There is only one `ShardClientUtil`, for reference, this is created as a singleton:
> 
> https://github.com/discordjs/discord.js/blob/8b70f497a1207e30edebdecd12b926c981c13d28/packages/discord.js/src/client/Client.js#L99-L105

Now we can clearly see what really calls `ShardClientUtil` from Discord.js... there's nothing calling any of the 4 methods. There is, however, a `WebSocketShard#send` that *is* called, however, as you can see, it sends data to a `WebSocket` instance (aka Discord), and does not use `ShardClientUtil`:

https://github.com/discordjs/discord.js/blob/8b70f497a1207e30edebdecd12b926c981c13d28/packages/discord.js/src/client/websocket/WebSocketShard.js#L739-L773

> **Note**: This is because `ShardClientUtil` is used only when process/worker sharding is on, and both because it's not always available (the a very tiny minority of the community uses this system) and because it's very application-specific to define how processes "talk" with each other, Discord.js **does not** use this class internally, it's intended for developers to use it instead.

---

Now that we know Discord.js does not call this method at all, it is, at the end, most likely the end-user's fault. Your stack trace is a bit limited but you can try using the `--stack-trace-limit` [V8 option](https://nodejs.org/dist/latest-v18.x/docs/api/cli.html) to expand it further than 9 lines. If that doesn't work, you can try using a debugger and set a breakpoint to that function, see what calls it.

Furthermore, you have not provided a single line of code that can help us determine the cause of this error ("I don't have code" is also a bad excuse: no code ⇔ no logic ⇔ no error), but I hope this information is enough to help you find the issue.

Finally, I may ask you to be a bit less disrespectful towards other members, they're trying to help you and are trying to give very valuable information to you, but we ask for cooperation, otherwise we won't have enough information to help you.
