### ISSUE TITLE
@discordjs/ws Unexpected network conditions cause crash when reconnecting

### ISSUE THREAD

**Issue by timotejroiko** [discordjs/discord.js#9103]
### Which package is this bug report for?

ws

### Issue description

When a close event is emitted, the library attempts to reconnect via onClose -> destroy -> connect.

At this point, if there is a network issue or unexpected network condition, the function `waitForEvent` may throw an error, for example if `ws` emits an error event, which will bubble up back to `onClose` and cause a crash.

An example of a possible error:

```
Error: Unexpected server response: 520
  at ClientRequest.<anonymous> (/app/node_modules/ws/lib/websocket.js:888:7)
  at ClientRequest.emit (node:events:513:28)
  at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:695:27)
  at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
  at TLSSocket.socketOnData (node:_http_client:536:22)
  at TLSSocket.emit (node:events:513:28)
  at addChunk (node:internal/streams/readable:324:12)
  at readableAddChunk (node:internal/streams/readable:297:9)
  at Readable.push (node:internal/streams/readable:234:10)
  at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)

node:internal/process/promises:288
  triggerUncaughtException(err, true /* fromPromise */);
```

Adding a `.catch` to either the `destroy` method when called from `onClose`, or the `connect` method when called from `destroy`, fixes the issue

### Package version

@discordjs/ws@0.6.1-dev.1674129868-56ef3ad.0

### Node.js version

19.3.0

### Operating system

windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

56ef3ad

**Comment by didinele** [comment]
I'm not sure I follow your description looking at the source code.

> At this point, if there is a network issue or unexpected network condition, the function waitForEvent may throw an error

I was with you here, since `waitForEvent` can throw if it times out, but then

> for example if ws emits an error event, which will bubble up back to onClose and cause a crash.

and the error you provided completely lose me.

I'm not quite sure how what you ran into is at all related to `waitForEvent` and it's also still rather unclear to me what threw that Unexpected Server Response. Was it sent to `onClose`? Was it just thrown from WS internals some time after `new WS()`?

**Comment by timotejroiko** [comment]
Sorry, i should have been more specific.

`waitForEvent` uses `once` from `node:events`, which according to the node docs `Creates a Promise that is fulfilled when the EventEmitter emits the given event or that is rejected if the EventEmitter emits 'error' while waiting.`.

`ws` will emit an error event if it fails to establish a websocket connection for any reason, for example:

```js
// invalid url
w = new WebSocket("wss://google.com");
w.on("error", console.log); // Unexpected server response 400

// turn off internet
w = new WebSocket("wss://gateway.discord.gg");
w.on("error", console.log); // getaddrinfo ENOTFOUND gateway.discord.gg
```

This can happen for any kind of connection failure. In my case i was investigating this error in a rather large bot (~300k guilds), and it appears to occasionally happen due to momentary network congestion.

The reason i pointed at `onClose` is that when `connect` is called by the user, it can be catch'ed and handled by the user, but when `connect` is called internally originating from `onClose`, there is no error handling at any point during that code path, so an error emitted by `ws` will be thrown by `once` and bubble up uncaught.

During my testing (forcing disconnections and simulating network issues), i was not able to prevent a process crash in any way from the user's side, but after modifying the library and adding a `.catch()` somewhere between `onClose` and `once` i was finally able to catch the error and get a proper stack trace.

**Comment by didinele** [comment]
Thank you, that's a lot more clear now. I'll look into a proper way to mitigate this.

**Comment by Deivu** [comment]
```
[CRITICAL](Cluster => 0) Error: Opening handshake has timed out
    at ClientRequest.<anonymous> (/home/kashima/bot/prod/node_modules/ws/lib/websocket.js:848:7)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.emitRequestTimeout (node:_http_client:771:9)
    at Object.onceWrapper (node:events:641:28)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket.Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) 
    
```

Can repro, one of the main issue here is the worker sharding, I don't know about the non worker sharding, is *not* throwing errors properly back to main process, causing an uncaught exception. Adding more issue, is the package doesn't try to reconnect once connect() throws an error, which is really problematic in my case. 

A good fix here is first, properly handling errors, and forwarding it to main process properly, and properly handling a reconnect IF the initial connect fails.

https://github.com/discordjs/discord.js/blob/8b70f497a1207e30edebdecd12b926c981c13d28/packages/ws/src/ws/WebSocketShard.ts#L217
There is also a possible issue in the code inside the if statement here, if you close the websocket before it actually tries to reconnect, which also causes a program wide crash due to uncaught exception. 
https://stackoverflow.com/questions/74788744/websocket-is-closed-before-the-connection-is-established
