### ISSUE TITLE
This error is occurring again as of the last 12 hours. No code changes. Was working perfectly 12 hours ago.

### ISSUE THREAD

**Issue by NotSoEvilDead** [discordjs/discord.js#9255]
Issue was closed without comment despite the issue recurring in the same fashion as previously reported.  Please do not flippantly close bug reports.  Thanks.

Original text below:

              This error is occurring again as of the last 12 hours. No code changes. Was working perfectly 12 hours ago.

Bot has been getting the same bogus authentication error upon trying to join VC. Bot will correctly enter the voice room, but authentication timeout after 15 seconds because discord broke something on their end.

Please fix this immediately and stop pushing backend changes with no notification. Thanks.

_Originally posted by @NotSoEvilDead in https://github.com/discordjs/discord.js/issues/2979#issuecomment-1476630146_

**Comment by NotSoEvilDead** [comment]
Original issue: https://github.com/discordjs/discord.js/issues/2979

**Comment by kyranet** [comment]
Please do not ignore the issue template.

The issue you commented for is over 4 years old and only applies to discord.js v11 (and to a lesser extent, v12). Considering the only way to do voice in a supported way right now is via `@discordjs/voice`, which is a completely different codebase, that issue was deemed irrelevant. You necro'd an issue that not longer applies to this day, that's why I locked the issue.

If you want to file an issue for `@discordjs/voice` (only supported way by us of doing voice with Discord.js), please fill the bug report template.

As for your comment, it makes no sense because we don't push background/backend updates, that's on you updating your dependencies or accidentally doing so by not having a lockfile. If you had no dependency changes and this issue just happened, you're most likely having issues with your host's network performance, and not with the library, there's only so much we can do on our end to provide the best software, but as soon as packets leave your host, it's only up for the internet protocols to do their job.

**Comment by kyranet** [comment]
It's standard protocol to lock irrelevant issues after they have been closed/resolved for years, though we only do so when somebody necroes it.

The issue resolving itself after a rollback may just be coincidence that your networking issues resolved themselves as you finished it, [`@discordjs/voice@0.15.0`](https://www.npmjs.com/package/@discordjs/voice?activeTab=versions) was released 8 days ago, with the previous version being 4 months old, it didn't happen in the last 12-14 hours.

The only outstanding change in that version was the removal of the KeepAlive mechanism, see the release [here](https://github.com/discordjs/discord.js/releases/tag/%40discordjs%2Fvoice%400.15.0), however, this removal (which was because changes on Discord's end) does not in any way or capacity cause a timeout issue.

**Comment by s01rice** [comment]
I am also affected by the  `Authenticate failed - VOICE_CONNECTION_TIMEOUT`  issue. It started happening 2 days ago. I doubt it is on discordjs's end since I'm using the deprecated discordjs 12. There may have been a change on Discord's end. If more people came forward with it then we would know for certain.

**Comment by Jiralite** [comment]
Discord has modified the behaviour of sending UDP packets. This was announced in 2019 and again just before the modification. Yes, 2019, that's how outdated the source of this issue is. Voice in discord.js version 12 does not account for this.

A reminder that both discord.js and the API version 12 uses (7) are deprecated. In fact, any day now, the API version will become [decommissioned](https://github.com/discord/discord-api-docs/discussions/4510). This change is the least of one's worries—one's bot is going to completely break.

**Comment by NotSoEvilDead** [comment]
Another user has confirmed their bot's voice connectivity has broken in the
exact same way.  This problem is 100% reproducible an is on discord's end.
I will require you to figure out what has changed and revert it.

Thanks

**Comment by NotSoEvilDead** [comment]
Your own link says the information you are refusing to provide will be
clearly communicated.  So I would appreciate if you took this more
seriously, because a major discord authentication issue should not be swept
under the rug.

"API v10 will become the Default version, and the default version for API
requests Plans for default versions will be communicated in the future"

**Comment by vladfrangu** [comment]
> I will require you to figure out what has changed and revert it.

Where do I even begin to reply when reading this... From reminding you that we are **not** Discord, the company, to the fact several contributors and collaborators told you *why* this is happening *and* also told you _how_ to fix it (update from djs v12 to v13 or v14, and our new voice system, as we will *not* be supporting or patching deprecated versions of discord.js), I think we did our best.

This isn't a bug, but rather a change Discord has postponed for 4! years finally going effect! We are not in control of what Discord does (or doesn't do), we can only work with their APIs and fix any issues on our side!
