### ISSUE TITLE
Over 2k of personally identifying information leaked because .followUp does not warn against ephemeral usage

### ISSUE THREAD

**Issue by bruhmomentlol** [discordjs/discord.js#9306]
### Which package is this bug report for?

discord.js

### Issue description

My Discord bot ended up being a doxxing machine thanks to me not knowing about ephemeral on follow up wouldn't work so people abused it and downloaded off random people's PII and got me banned off discord by reporting me.

For god's sake add a warning if you pass {ephemeral:true} to a follow up

### Code sample

```typescript
client.on('interactionCreate', (event) => {
    if(event.isCommand()) {
        event.reply('Hey thats fine', {ephemeral: true})
        event.followUp('That\'s not fine :(', {ephemeral: true})
    }
})
```

### Package version

14

### Node.js version

v16.20.0

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Guilds

**Comment by Jiralite** [comment]
This is not a bug, you are not using the method correctly.

**Comment by almostSouji** [comment]
JavaScript generally accepts arbitrary objects and function parameters, we cannot guard any method against misuse on our end, just because some combinations of option keys and function parameters might look plausible to end users.

The solution is to use a strongly typed wrapper ([TypeScript](https://www.typescriptlang.org/)), which validates these things (discord.js ships with in-house typings and does not rely on third-party repositories like definitelytyped).

We recommend deploying your commands to a trusted dev-only server as a [guild-based application command](https://discordjs.guide/creating-your-bot/command-deployment.html#guild-commands) and testing it thoroughly before a global deployment (especially when personal data and access control are required).
