### ISSUE TITLE
using rejectOnRateLimit, the RateLimitError.timeToReset property does not provide useful data when updating a channel name is rate limited

### ISSUE THREAD

**Issue by patters-code** [discordjs/discord.js#9572]
### Which package is this bug report for?

discord.js

### Issue description

When you encounter the rate limit associated with updating a channel, if you set the route up to rejectOnRateLimit - the timeToReset field returned in the RateLimitError does not seem valid/useful. It almost always returns 10100 (sometimes slightly lower, never more) - just over 10 seconds, The documentation for this property of the error (via RateLimitData) states "The time, in milliseconds, until the request-lock is reset".

My expectation was that this would be the amount of time in milliseconds until the limit would reset, if this value is something related to how discord.js queues rate limited requests it doesn't seem like a valid return value for this configuration - the calling code should be able to get access to the relevant information the API returns, in order to avoid hitting the rate limit on subsequent requests and continuing to hit this error.

### Steps to reproduce: 
1. replace channelId with a valid guild text channel
2. replace token with a valid bot token
3. run script

I'm hoping I've covered everything for this to be a useful issue, if there is anything I've missed (or something I have misconfigured somehow to be in this state) let me know

### Code sample

```typescript
import { RateLimitData, Client, GatewayIntentBits, Partials, GuildTextBasedChannel } from "discord.js";

const channelId = 'someTextChannelId';
const token = 'someToken';

const shouldRejectOnRateLimit = (data: RateLimitData) => {
	return data.method === 'PATCH' && data.route === '/channels/:id';
}

const client = new Client({ intents: [GatewayIntentBits.Guilds] , partials: [Partials.Channel], rest: { rejectOnRateLimit: shouldRejectOnRateLimit } });

client.once('ready',async () => {
	const channel = await client.channels.fetch(channelId) as GuildTextBasedChannel;
	
	const messages = await channel.messages.fetch();
	try {
		await channel.edit({ name: 'name1'});
		await channel.edit({ name: 'name2'});
		await channel.edit({ name: 'name3'});
	} catch(ex: any) {
		console.log(ex.timeToReset);
	}	
});

client.login(token);
```

### Versions

- discord.js 14.8.0 (also tested 14.11.0 and 14.12.0-dev.1684152278-590f5bc.0
- typescript 5.0.4
- Node.js v18.16.0
- OS: ubuntu 22.04

Additional: using ES modules rather than CJS

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Channel

### Which gateway intents are you subscribing to?

Guilds

### I have tested this issue on a development release

590f5bc

**Comment by D4isDAVID** [comment]
Seems like correct behavior to me.

When you get rate limited, the RequestManager catches it and saves all the rate limit data, and in this case the time to reset is ~10 seconds. To complete the requests following the one that got rate limited, the RequestManager waits those 10 seconds instead of hitting more rate limits, therefore the rate limit event won't be emitted and you are never given anything below 10 seconds.

**Comment by patters-code** [comment]
The problem here is that rate limit for this type of request is 2 requests in 10 minutes. The 10~ seconds returned bears no relationship to any actual rate limit imposed by the discord API - this type of request wont (or shouldn't) be retried in 10 seconds, the discord API returns vastly different rate limit headers and having configured my app to reject and throw an error when this request is limited (therefore taking responsibility on my end for handling rate limits on this request) I would expect to receive meaningful data about when I can next make a request (especially since as far as I can tell in this case the limit data required is returned by the discord API and simply discarded)

my expectation of behaviour in this instance was basically:

1. Configure my app to reject/throw an error when rate limited on this endpoint (channel update) rather than retrying with an update that will be out of date when the 10 minute rate limit is up 
2. Make requests as needed until I make enough to hit the rate limit
3. Catch the rejection and get useful information about when I can next safely make a request of this kind
4. Use the information returned to ensure the next time I make a request of this kind I just discard it myself if it comes in before the limit expires

This is not possible if discord.js returns a flat 10 seconds when the limit is hit instead of the information the discord API actually returns when discord.js makes the request. if `timeToReset` is an internal limit which discord.js imposes to support the "standard" configuration (i.e. when by default requests are queued and retried rather than rejected when rate limited), then it's neither managing this rate limit itself (which is correct behaviour, as it's been configured not to), nor giving the calling code the meaningful information returned by the discord API (which at the point the promise is rejected has already been returned by the discord API) to manage the rate limit directly.

I hope that helps explain what the problem here is.

**Comment by D4isDAVID** [comment]
I see now, I totally missed that.
After trying out standalone HTTP requests it seems like discord.js indeed does give misleading info

**Comment by ckohen** [comment]
> the discord API returns vastly different rate limit headers

Last I checked it doesn't. The `X-Ratelimit` headers return the values for the route as a whole no matter which ratelimit you are hitting (including sublimits). For most routes, not a big deal, but any route with a sublimit it's a pain in the ass. The only useful header is the traditional `Retry-After` header (only present on actual 429's), that has the only information on when we should actually retry the request.

> this type of request wont (or shouldn't) be retried in 10 seconds

Got you covered there, it'll be retried after 10 minutes (or whatever the header returns), and subsequent requests for sublimits we know (only channel topic / name atm, also since it's a very large difference in time for this one) will be split into requests that can pass immediately and ones that must wait. For all other sublimits, all requests in that queue will wait for the sublimit since discord gives us exactly 0 information on what triggered it.

This is all, of course, only if the onRateLimit hook doesn't decide to throw for the running request.

> The documentation for this property of the error (via RateLimitData) states "The time, in milliseconds, until the request-lock is reset".

Given the logic outlined above, I understand how this doc string may be slightly confusing, but can you see how it describes the actual behavior?
Granted, in a lot of cases, the queue will entirely lock, but we can't guarantee when that happens. It would probably be more technically correct to set this value to the sublimit's retry value, but it would be more correct to provide both values separately.

Honestly, the fact that `retryAfter`  and `sublimitTimeout` aren't in `RateLimitData` confuses me. They'd be optional properties so you'd need to check if they exist, but they are quite important. They're also both in the debug string that is emitted immediately after checking to see if the request should be rejected, so something went wonky at some point.

**Comment by patters-code** [comment]
> Got you covered there, it'll be retried after 10 minutes (or whatever the header returns), and subsequent requests for sublimits we know (only channel topic / name atm, also since it's a very large difference in time for this one) will be split into requests that can pass immediately and ones that must wait. For all other sublimits, all requests in that queue will wait for the sublimit since discord gives us exactly 0 information on what triggered it.
>

Yeah I experienced that the queueing seemed like it was working correctly and waiting the correct amount of time when using the default behaviour, but it seemed like it queued all requests and for this endpoint at least (and I accept generalising wouldn't work) I would prefer more of a switchMap approach which didn't seem to be what happened (although it was over 2 months ago so my memory of the iterations I tried when I was looking at this is fuzzy)

I definitely remember stepping through the discordjs code and finding headers from a discord response that matched up to my expectation of when the next request could be made, but can't remember the exact detail of which header said what anymore, so I'm pretty sure you're correct about `Retry-After` being what I was thinking of on that.


> Given the logic outlined above, I understand how this doc string may be slightly confusing, but can you see how it describes the actual behavior? Granted, in a lot of cases, the queue will entirely lock, but we can't guarantee when that happens. It would probably be more technically correct to set this value to the sublimit's retry value, but it would be more correct to provide both values separately.

Agreed, I raised the issue on the assumption that the schema would already be considered "complete" and the data was just not being recorded, but adding additional fields for these values definitely makes more sense than putting them here.

> Honestly, the fact that `retryAfter` and `sublimitTimeout` aren't in `RateLimitData` confuses me. They'd be optional properties so you'd need to check if they exist, but they are quite important. They're also both in the debug string that is emitted immediately after checking to see if the request should be rejected, so something went wonky at some point.

Yeah, it feels like they are basically required information for the case where you set up a route to reject rather than retry like this, which was why I assumed I should be looking at the existing fields rather than requesting additional ones.

Thanks!
