### ISSUE TITLE
# There is an error in ModalSubmitInteraction.js

### ISSUE THREAD

**Issue by KasaiKonoru** [discordjs/discord.js#9731]
### Which package is this bug report for?

discord.js

### Issue description

Always get the MODAL_SUBMIT_INTERACTION_FIELD_NOT_FOUND error because of this failure in code:
interaction.fields.getField() never got the custom ID of the field
https://github.com/discordjs/discord.js/blob/cb11c56a0b93c802b024cc9c8d95250ddf1a5246/src/structures/ModalSubmitInteraction.js#L93
"c.custom_id" needs to be "c.customId" 
Now TextInputComponent() and getField() get the customId again!

### Code sample

```typescript
static transformComponent(rawComponent) {     
return rawComponent.components.map(c => ({       
value: c.value,       
type: MessageComponentTypes[c.type],       
customId: c.customId, // << was c.custom_id before     })); 
}
//Now TextInputComponent() and getField() get the customId again!
```

### Versions

discord.js@13.16.0
Node: v18.15.0

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by Jiralite** [comment]
> `customId: c.customId, // << was c.custom_id before     }));`

Git blame states this has never been `c.custom_id`.

I have not looked into this yet, but I doubt this is the case.

**Comment by Jiralite** [comment]
> I have not looked into this yet, but I doubt this is the case.

I have now looked into this.

I cannot reproduce this issue. My code sample is actually simply copied from the [version 13 guide](https://v13.discordjs.guide/interactions/modals.html#responding-to-modal-submissions).

Moreover, this seems to be impossible. This method is referenced in one place only:

https://github.com/discordjs/discord.js/blob/cb11c56a0b93c802b024cc9c8d95250ddf1a5246/src/structures/ModalSubmitInteraction.js#L37-L45

`c` is raw data, so `custom_id` is the correct property use.

<hr>

The more likely scenario is you are doing something incorrectly or the internal behaviour of discord.js has been edited (especially since this has not changed since implementation and no one has complained).

**Comment by KasaiKonoru** [comment]
ok thanks. But many people in the discord server have this issue. I reinstalled discord v13 and used a new bot with the guide copied and pasted. But I always get the same error

**Comment by KasaiKonoru** [comment]
the textinout was only logged without error when I modified c.custom_id to c.customId

**Comment by Jiralite** [comment]
> But many people in the discord server have this issue.

I have a hard time believing that, considering modal support was added over a year ago and this code has been untouched. Care to link these many people in the server?

**Comment by Jiralite** [comment]
From Discord, it was found that the reporter had a third-party package installed which modified the internal behaviour of discord.js resulting in this error (posting for transparency).
